In [35]:
import torch
import torch.nn as nn
import numpy as np
import matplotlib.pyplot as plt
import torchvision

In [6]:
def dropout(x,drop_prob):
    x=x.float()
    assert 0<=drop_prob<=1
    keep_prob=1-drop_prob
    
    if keep_prob==0:
        return torch.zeros_like(x)
    mask=(torch.randn(x.shape)<keep_prob).float()
    return mask * x /keep_prob

In [7]:
a=np.array([[1,2,3],[1,2,3],[1,2,3]])
b=np.array([[10,20,30],[11,22,33],[111,222,333]])
a.dot(b)

array([[ 365,  730, 1095],
       [ 365,  730, 1095],
       [ 365,  730, 1095]])

In [8]:
x=torch.arange(16).view(2,8)
dropout(x,0)

tensor([[ 0.,  1.,  2.,  0.,  0.,  5.,  6.,  0.],
        [ 8.,  0.,  0., 11.,  0., 13., 14.,  0.]])

In [18]:
dropout(x,0.5)

tensor([[ 0.,  2.,  4.,  6.,  8., 10.,  0., 14.],
        [16.,  0.,  0., 22., 24.,  0., 28., 30.]])

In [10]:
dropout(x,1)

tensor([[0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0.]])

In [19]:
drop_prob1,drop_prob2=0.2,0.5
def net(x,is_training=True):
    x=x.view(-1,num_inputs)
    h1=(torch.matmul(x,w1)+b1).relu()
    if is_training:
        h1=dropout(h1,drop_prob)
    h2=(torch.matmul(h1,w2)+b2).relu()
    if is_training:
        h2=dropout(h2,drop_prob2)
    return torch.matmul(h2,w3)+b3

In [21]:
def evaluate_accuracy(data_iter,net):
    acc_sum,n=0.0,0
    for x,y in data_iter:
        if isinstance(net,torch.nn.Module):
            net.eval()
            acc_sum+=(net(x).argmax(dim=1)==y).float().sum().item()
            net.train()
        else:
            if('is_training' in net.__code__.co_varnames):
                acc_sum+=(net(x,is_training=False).argmax(dim=1)==y).float().sum().item()
            else:
                acc_sum +=(net(x).argmax(dim=1)==y).float().sum().item()
        n+=y.shape(0)
    return acc_sum/n
                

In [22]:
a=torch.randn((5,2))
b=torch.randn((2,3))
torch.matmul(a,b)

tensor([[-2.5824,  0.2950, -2.1648],
        [ 0.1487, -0.1043,  0.1647],
        [-3.4969, -4.6589, -0.6081],
        [-1.0640,  1.7218, -1.6269],
        [ 1.3708,  3.2520, -0.4164]])

In [30]:
c=torch.mm(a,b)
c.argmax(dim=1)==1

tensor([1, 0, 0, 1, 1], dtype=torch.uint8)

In [32]:
n_train,n_test,num_inputs=20,100,200
true_w,true_b=torch.ones(num_inputs,1)*0.01,0.05
features=torch.randn((n_train+n_test,num_inputs))
labels=torch.matmul(features,true_w)+true_b
labels+=torch.tensor(np.random.normal(0,0.01,size=labels.size()),dtype=torch.float)
train_features,test_features=features[:n_train,:],features[n_train:,:]
train_labels,test_labels=labels[:n_train,:],labels[n_train:,:]

In [36]:
num_epochs,lr,batch_size=5,100.0,256
loss=torch.nn.CrossEntropyLoss()
dataset = torch.utils.data.TensorDataset(train_features, train_labels)
train_iter = torch.utils.data.DataLoader(dataset, batch_size, shuffle=True)

In [ ]:
optimizer=torch.optim.SGD(net.parameters(),lr=0.5)
