In [2]:
import torch
import torch.utils.data as Data
import numpy as np

In [31]:
num_samples=1000
num_inputs=2
true_w=[2,-3,4]
true_b=4.2
features=torch.tensor(np.random.normal(0,1,(num_samples,num_inputs)),dtype=torch.float32)
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels += torch.tensor(np.random.normal(0,0.01,1000),dtype=torch.float32)

In [32]:
batch_size=10
dataset=Data.TensorDataset(features,labels)
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)

In [33]:
for i,j in data_iter:
    print(i,j)
    break

tensor([[-0.8193,  0.1205],
        [ 1.2172, -0.0620],
        [-0.5016, -0.4161],
        [-0.3574,  0.2443],
        [-0.7772, -0.8293],
        [-0.2589, -0.3171],
        [ 1.0357, -2.3186],
        [-0.1209, -0.1241],
        [-0.1387,  0.0978],
        [ 1.0730,  0.8894]]) tensor([ 2.2001,  6.8213,  4.4449,  2.7641,  5.1328,  4.6169, 13.2273,  4.3101,
         3.6213,  3.6628])


In [34]:
import torch.nn as nn

In [35]:
net=nn.Sequential()
net.add_module('linear',nn.Linear(num_inputs,1))
print(net)
print(net[0])

Sequential(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [36]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.5437, -0.4162]], requires_grad=True)
Parameter containing:
tensor([0.2707], requires_grad=True)


In [37]:
from torch.nn import init

In [46]:
init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [39]:
loss=nn.MSELoss()

In [40]:
import torch.optim as optim

In [41]:
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [42]:
# optimizer1=optim.SGD([{'params':net.subnet1.paramseters()},
#                      {'params':net.subnet2.parameters(),'lr':0.01}],
#                     lr=0.03)

In [43]:
# for param_group in optimizer.param_groups:
#     param_group['lr'] *=0.01

In [44]:
num_epochs=3
for epoch in range(1,num_epochs+1):
    for x,y in data_iter:
        output=net(x)
        l=loss(output,y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d,loss %f' % (epoch,l.item()))
        

epoch 1,loss 0.000116
epoch 2,loss 0.000061
epoch 3,loss 0.000108
