In [6]:
import torch
import numpy as np

In [2]:
A=torch.arange(20,dtype=torch.float32).reshape(5,4)
B=A.clone()
A,A+B

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [12., 13., 14., 15.],
         [16., 17., 18., 19.]]), tensor([[ 0.,  2.,  4.,  6.],
         [ 8., 10., 12., 14.],
         [16., 18., 20., 22.],
         [24., 26., 28., 30.],
         [32., 34., 36., 38.]]))

In [3]:
A*B

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.],
        [144., 169., 196., 225.],
        [256., 289., 324., 361.]])

In [9]:
x=torch.tensor(np.arange(0,4),dtype=torch.float32)
y=torch.ones(4,dtype=torch.float32)
x,y,torch.dot(x,y)

(tensor([0., 1., 2., 3.]), tensor([1., 1., 1., 1.]), tensor(6.))

In [11]:
torch.sum(x*y)

tensor(6.)

In [14]:
A

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  6.,  7.],
        [ 8.,  9., 10., 11.],
        [12., 13., 14., 15.],
        [16., 17., 18., 19.]])

In [15]:
x

tensor([0., 1., 2., 3.])

In [13]:
A.shape,x.shape,torch.mv(A,x)

(torch.Size([5, 4]), torch.Size([4]), tensor([ 14.,  38.,  62.,  86., 110.]))

In [17]:
B=np.random.normal(0,1,(2,3,4))
B.sum(axis=0).shape,B.sum(axis=1).shape,B.sum(axis=2).shape

((3, 4), (2, 4), (2, 3))

In [19]:
np.linalg.norm(B,axis=0)

array([[2.42539983, 0.91209983, 0.72234459, 0.30467431],
       [0.92006646, 1.41497551, 1.56337941, 0.64827685],
       [1.90021993, 0.65862691, 1.65446445, 2.02121777]])

In [10]:
(8.9*4+6)/(4*4)

2.6

In [11]:
32/12

2.6666666666666665