In [1]:
import xgboost as xgb
import numpy as np

In [6]:
def log_reg(y_hat,y):
    p=1.0 / (1.0+np.exp(-y_hat))
    g=p-y.get_label()
    h=p*(1.0-p)
    return g,h

In [7]:
def error_rate(y_hat,y):
    return 'error',float(sum(y.get_label() !=(y_hat >0.5))) / len(y_hat)

In [8]:
data_train=xgb.DMatrix(r'F:\study\ml\DoctorZou\11Boost\12.XGBoost\12.agaricus_train.txt')
data_test=xgb.DMatrix(r'F:\study\ml\DoctorZou\11Boost\12.XGBoost\12.agaricus_test.txt')

[13:33:33] 6513x126 matrix with 143286 entries loaded from F:\study\ml\DoctorZou\11Boost\12.XGBoost\12.agaricus_train.txt
[13:33:33] 1611x126 matrix with 35442 entries loaded from F:\study\ml\DoctorZou\11Boost\12.XGBoost\12.agaricus_test.txt


In [9]:
data_test.get_label()

array([ 0.,  1.,  0., ...,  1.,  0.,  1.], dtype=float32)

In [10]:
param={'max_depth':2,'eta':1,'silent':1,'objective':'binary:logitraw'}
watchlist=[(data_test,'eval'),(data_train,'train')]
n_round=3
bst=xgb.train(param,data_train,num_boost_round=n_round,evals=watchlist,
             obj=log_reg,feval=error_rate)

[13:33:34] WARNING: C:\Users\Administrator\workspace\xgboost-win64_release_1.1.0\src\learner.cc:480: 
Parameters: { silent } might not be used.

  This may not be accurate due to some parameters are only used in language bindings but
  passed down to XGBoost core.  Or some parameters are not used but slip through this
  verification. Please open an issue if you find above cases.


[0]	eval-auc:0.96037	train-auc:0.95823	eval-error:0.04283	train-error:0.04652
[1]	eval-auc:0.97993	train-auc:0.98141	eval-error:0.02173	train-error:0.02226
[2]	eval-auc:0.99852	train-auc:0.99707	eval-error:0.01800	train-error:0.01520


In [11]:
y_hat=bst.predict(data_test)


In [12]:
y_hat

array([-1.70712996,  1.70548773, -1.70712996, ...,  3.15561986,
       -3.70064616,  3.15561986], dtype=float32)

In [13]:
y=data_test.get_label()

In [14]:
y

array([ 0.,  1.,  0., ...,  1.,  0.,  1.], dtype=float32)

In [15]:
y_hat>0

array([False,  True, False, ...,  True, False,  True], dtype=bool)

In [16]:
y!=(y_hat>0)

array([False, False, False, ..., False, False, False], dtype=bool)

In [17]:
np.array([0,1]) !=np.array([True,False])

array([ True,  True], dtype=bool)

In [18]:
error = sum(y != (y_hat > 0))
error_rate = float(error) / len(y_hat)
error_rate

0.006207324643078833

array([-1.70712996,  1.70548773, -1.70712996, ...,  3.15561986,
       -3.70064616,  3.15561986], dtype=float32)

In [23]:
data_test.slice

<bound method DMatrix.slice of <xgboost.core.DMatrix object at 0x000000000BEE6EB8>>