In [1]:
from keras import models
from keras import layers

D:\ProgramData\Anaconda3\lib\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:
model=models.Sequential()
model.add(layers.Dense(32,activation='relu',input_shape=(784,)))
model.add(layers.Dense(10,activation='softmax'))

In [3]:
input_tensor=layers.Input(shape=(784,))
x=layers.Dense(32,activation='relu')(input_tensor)
output_tensor=layers.Dense(10,activation='softmax')(x)
model=models.Model(inputs=input_tensor,outputs=output_tensor)

In [4]:
from keras import optimizers

In [5]:
model.compile(optimizer=optimizers.RMSprop(lr=0.001),loss='mse',metrics=['accuracy'])

#3.1

In [6]:
from keras.datasets import imdb
import numpy as np

In [7]:
(train_data,train_labels),(test_data,test_labels)=imdb.load_data(num_words=10000)

In [8]:
train_data[0]

[1,
 14,
 22,
 16,
 43,
 530,
 973,
 1622,
 1385,
 65,
 458,
 4468,
 66,
 3941,
 4,
 173,
 36,
 256,
 5,
 25,
 100,
 43,
 838,
 112,
 50,
 670,
 2,
 9,
 35,
 480,
 284,
 5,
 150,
 4,
 172,
 112,
 167,
 2,
 336,
 385,
 39,
 4,
 172,
 4536,
 1111,
 17,
 546,
 38,
 13,
 447,
 4,
 192,
 50,
 16,
 6,
 147,
 2025,
 19,
 14,
 22,
 4,
 1920,
 4613,
 469,
 4,
 22,
 71,
 87,
 12,
 16,
 43,
 530,
 38,
 76,
 15,
 13,
 1247,
 4,
 22,
 17,
 515,
 17,
 12,
 16,
 626,
 18,
 2,
 5,
 62,
 386,
 12,
 8,
 316,
 8,
 106,
 5,
 4,
 2223,
 5244,
 16,
 480,
 66,
 3785,
 33,
 4,
 130,
 12,
 16,
 38,
 619,
 5,
 25,
 124,
 51,
 36,
 135,
 48,
 25,
 1415,
 33,
 6,
 22,
 12,
 215,
 28,
 77,
 52,
 5,
 14,
 407,
 16,
 82,
 2,
 8,
 4,
 107,
 117,
 5952,
 15,
 256,
 4,
 2,
 7,
 3766,
 5,
 723,
 36,
 71,
 43,
 530,
 476,
 26,
 400,
 317,
 46,
 7,
 4,
 2,
 1029,
 13,
 104,
 88,
 4,
 381,
 15,
 297,
 98,
 32,
 2071,
 56,
 26,
 141,
 6,
 194,
 7486,
 18,
 4,
 226,
 22,
 21,
 134,
 476,
 26,
 480,
 5,
 144,
 30,
 5535,
 18,

In [9]:
train_labels[0]

1

In [10]:
max([max(sequence) for sequence in train_data])

9999

In [11]:
word_index=imdb.get_word_index()
reverse_word_index=dict(
[(value,key) for (key,value) in word_index.items()])
decoded_review=' '.join(
[reverse_word_index.get(i-3,'?') for i in train_data[0]])

In [12]:
def vectorize_sequences(sequences,dimension=10000):
    results=np.zeros((len(sequences),dimension))
    for i ,sequence in enumerate(sequences):
        results[i,sequence]=1.
    return results
    

In [13]:
X_train=vectorize_sequences(train_data)
X_test=vectorize_sequences(test_data)

In [14]:
X_train[0]

array([0., 1., 1., ..., 0., 0., 0.])

In [15]:
y_train=np.asarray(train_labels).astype('float32')
y_test=np.asarray(test_labels).astype('float32')

In [19]:
model=models.Sequential()
model.add(layers.Dense(16,activation='relu',input_shape=(10000,)))
model.add(layers.Dense(16,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))

In [21]:
model.compile(optimizer=optimizers.RMSprop(lr=0.001),
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [22]:
X_train.shape

(25000, 10000)

In [23]:
x_val=X_train[:10000]
partial_x_train=X_train[10000:]

y_val=y_train[:10000]
partial_y_train=y_train[10000:]


In [24]:
history=model.fit(partial_x_train,
                 partial_y_train,
                 epochs=20,
                 validation_data=(x_val,y_val))

Train on 15000 samples, validate on 10000 samples
Epoch 1/20
15000/15000 [==============================] - 4s 242us/step - loss: 0.3513 - acc: 0.8554 - val_loss: 0.2806 - val_acc: 0.8862
Epoch 2/20
15000/15000 [==============================] - 3s 203us/step - loss: 0.2031 - acc: 0.9223 - val_loss: 0.2882 - val_acc: 0.8873
Epoch 3/20
15000/15000 [==============================] - 3s 198us/step - loss: 0.1567 - acc: 0.9423 - val_loss: 0.3158 - val_acc: 0.8858
Epoch 4/20
15000/15000 [==============================] - 3s 202us/step - loss: 0.1253 - acc: 0.9557 - val_loss: 0.3556 - val_acc: 0.8856
Epoch 5/20
15000/15000 [==============================] - 3s 203us/step - loss: 0.1014 - acc: 0.9635 - val_loss: 0.4051 - val_acc: 0.8769
Epoch 6/20
15000/15000 [==============================] - 3s 204us/step - loss: 0.0797 - acc: 0.9716 - val_loss: 0.4599 - val_acc: 0.8786
Epoch 7/20
15000/15000 [==============================] - 3s 206us/step - loss: 0.0631 - acc: 0.9779 - val_loss: 0.5223 - 

In [26]:
history_dict=history.history
history_dict.keys()

dict_keys(['val_loss', 'val_acc', 'loss', 'acc'])

In [33]:
model=models.Sequential()
model.add(layers.Dense(64,activation='relu',input_shape=(10000,)))
model.add(layers.Dense(64,activation='relu'))
model.add(layers.Dense(1,activation='sigmoid'))

In [34]:
model.compile(optimizer='rmsprop',
             loss='binary_crossentropy',
             metrics=['accuracy'])

In [35]:
model.fit(X_train,y_train,epochs=4,batch_size=512)
results=model.evaluate(X_test,y_test)

Epoch 1/4
25000/25000 [==============================] - 3s 127us/step - loss: 0.4294 - acc: 0.8080
Epoch 2/4
25000/25000 [==============================] - 3s 106us/step - loss: 0.2382 - acc: 0.9093
Epoch 3/4
25000/25000 [==============================] - 3s 105us/step - loss: 0.1829 - acc: 0.9310
Epoch 4/4
25000/25000 [==============================] - 3s 126us/step


In [36]:
results

[0.3383116394090652, 0.8726]

In [ ]:
[0.32425593941688535, 0.8732]

In [32]:
model.predict(X_test)

array([[0.14250116],
       [0.99970406],
       [0.28931814],
       ...,
       [0.07107645],
       [0.04292201],
       [0.47185946]], dtype=float32)

In [37]:
from keras.datasets import reuters

In [38]:
(train_data,train_labels),(test_data,test_labels)=reuters.load_data(num_words=10000)

2113536/2110848 [==============================] - 11s 5us/step


In [39]:
train_data.shape

(8982,)

In [40]:
test_data.shape

(2246,)

In [41]:
train_data[10]

[1,
 245,
 273,
 207,
 156,
 53,
 74,
 160,
 26,
 14,
 46,
 296,
 26,
 39,
 74,
 2979,
 3554,
 14,
 46,
 4689,
 4329,
 86,
 61,
 3499,
 4795,
 14,
 61,
 451,
 4329,
 17,
 12]

In [42]:
word_index=reuters.get_word_index()
reverse_word_index=dict([(value,key) for (key,value) in word_index.items()])
decoded_newswire=' '.join ([reverse_word_index.get(i-3,'?') for i in train_data[0]])

557056/550378 [==============================] - 16s 29us/step


In [48]:
np.max(train_labels)

45

In [49]:
np.min(train_labels)

0

In [52]:
def vectorize_sequences(sequences,dimension=10000):
    results=np.zeros((len(sequences),dimension))
    for i ,sequence in enumerate(sequences):
        results[i,sequence]=1.
    return results

In [53]:
x_train=vectorize_sequences(train_data)
x_test=vectorize_sequences(test_data)

In [58]:
def to_one_hot(labels,dimension=46):
    results=np.zeros((len(labels),dimension))
    for i ,labels in enumerate(labels):
        results[i,labels]=1.0
    return results

In [59]:
one_hot_train_labels=to_one_hot(train_labels)
one_hot_test_labels=to_one_hot(test_labels)

In [60]:
from keras.utils.np_utils import to_categorical

In [61]:
one_hot_train_labels1=to_categorical(train_labels)
one_hot_test_labels1=to_categorical(test_labels)

In [64]:
x_train.shape

(8982, 10000)

In [66]:
model1=models.Sequential()
model1.add(layers.Dense(64,activation='relu',input_shape=(10000,)))
model1.add(layers.Dense(64,activation='relu'))
model1.add(layers.Dense(46,activation='softmax'))

In [67]:
model1.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['acc'])

In [68]:
x_val=x_train[:1000]
partial_x_train=x_train[1000:]

y_val=one_hot_train_labels[:1000]
partial_y_train=one_hot_train_labels[1000:]

In [71]:
history=model1.fit(partial_x_train,
                 partial_y_train,
                 epochs=20,
                 batch_size=512,
                 validation_data=(x_val,y_val))

Train on 7982 samples, validate on 1000 samples
Epoch 1/20
7982/7982 [==============================] - 1s 124us/step - loss: 1.4465 - acc: 0.6858 - val_loss: 1.3506 - val_acc: 0.7130
Epoch 2/20
7982/7982 [==============================] - 1s 125us/step - loss: 1.1010 - acc: 0.7618 - val_loss: 1.1777 - val_acc: 0.7370
Epoch 3/20
7982/7982 [==============================] - 1s 125us/step - loss: 0.8792 - acc: 0.8084 - val_loss: 1.0696 - val_acc: 0.7610
Epoch 4/20
7982/7982 [==============================] - 1s 126us/step - loss: 0.7072 - acc: 0.8478 - val_loss: 1.0003 - val_acc: 0.7830
Epoch 5/20
7982/7982 [==============================] - 1s 125us/step - loss: 0.5700 - acc: 0.8794 - val_loss: 0.9977 - val_acc: 0.7730
Epoch 6/20
7982/7982 [==============================] - 1s 123us/step - loss: 0.4587 - acc: 0.9049 - val_loss: 0.8901 - val_acc: 0.8150
Epoch 7/20
7982/7982 [==============================] - 1s 124us/step - loss: 0.3687 - acc: 0.9223 - val_loss: 0.8870 - val_acc: 0.8120


In [72]:
history=model1.fit(partial_x_train,
                 partial_y_train,
                 epochs=9,
                 batch_size=512,
                 validation_data=(x_val,y_val))
results=model1.evaluate(x_test,one_hot_test_labels)

Train on 7982 samples, validate on 1000 samples
Epoch 1/9
7982/7982 [==============================] - 1s 128us/step - loss: 0.1035 - acc: 0.9589 - val_loss: 1.0883 - val_acc: 0.8080
Epoch 2/9
7982/7982 [==============================] - 1s 126us/step - loss: 0.1018 - acc: 0.9577 - val_loss: 1.1182 - val_acc: 0.8040
Epoch 3/9
7982/7982 [==============================] - 1s 125us/step - loss: 0.0995 - acc: 0.9585 - val_loss: 1.1371 - val_acc: 0.7920
Epoch 4/9
7982/7982 [==============================] - 1s 129us/step - loss: 0.0960 - acc: 0.9600 - val_loss: 1.1722 - val_acc: 0.7900
Epoch 5/9
7982/7982 [==============================] - 1s 127us/step - loss: 0.0977 - acc: 0.9592 - val_loss: 1.1491 - val_acc: 0.7930
Epoch 6/9
7982/7982 [==============================] - 1s 128us/step - loss: 0.0936 - acc: 0.9575 - val_loss: 1.1871 - val_acc: 0.8000
Epoch 7/9
7982/7982 [==============================] - 1s 125us/step - loss: 0.0968 - acc: 0.9575 - val_loss: 1.1628 - val_acc: 0.8000
Epoch 8

In [73]:
results

[1.4009787361216355, 0.7675868210682143]

In [75]:
import copy

In [76]:
test_labels_copy=copy.copy(test_labels)
np.random.shuffle(test_labels_copy)
hist_array=np.array(test_labels)==np.array(test_labels_copy)
float(np.sum(hist_array))/len(test_labels)

0.17586821015138024

In [77]:
hist_array


array([ True, False, False, ..., False,  True, False])

In [79]:
np.array([1,2,3])==np.array([1,3,4])

array([ True, False, False])

In [80]:
predictions=model1.predict(x_test)

In [81]:
predictions[0].shape

(46,)

In [82]:
predictions

array([[3.7760284e-08, 6.1208866e-08, 1.6162452e-10, ..., 1.6908431e-11,
        9.3914806e-13, 5.0967407e-12],
       [4.6087640e-05, 5.2540302e-03, 1.5483463e-08, ..., 4.9509879e-11,
        4.0505065e-12, 8.1391374e-07],
       [5.9238183e-03, 9.1465008e-01, 1.8382951e-04, ..., 1.4678280e-06,
        1.1789758e-07, 3.3837644e-06],
       ...,
       [3.9465085e-08, 3.5966750e-07, 4.8329087e-09, ..., 5.2782851e-11,
        7.7629958e-11, 9.9827759e-12],
       [6.6929759e-04, 5.2991327e-02, 3.2482727e-05, ..., 2.5519032e-06,
        1.8739136e-08, 5.8256258e-08],
       [1.3519943e-05, 7.7712184e-01, 2.0129967e-02, ..., 6.6056942e-09,
        2.2745185e-12, 1.4069607e-07]], dtype=float32)

In [84]:
np.sum(predictions[2])

1.0000001

In [86]:
np.argmax(predictions[1])

10

In [87]:
y_train=np.array(train_labels)
y_test=np.array(test_labels)

In [95]:
model1.compile(optimizer='rmsprop',
              loss='sparse_categorical_crossentropy',
              metrics=['acc'])

In [100]:
history=model1.fit(x_train,
                 y_train,
                 epochs=20,
                 batch_size=512)

Epoch 1/20
8982/8982 [==============================] - 1s 154us/step - loss: 0.2312 - acc: 0.9404
Epoch 2/20
8982/8982 [==============================] - 1s 115us/step - loss: 0.1581 - acc: 0.9469
Epoch 3/20
8982/8982 [==============================] - 1s 113us/step - loss: 0.1393 - acc: 0.9516
Epoch 4/20
8982/8982 [==============================] - 1s 113us/step - loss: 0.1248 - acc: 0.9532
Epoch 5/20
8982/8982 [==============================] - 1s 112us/step - loss: 0.1159 - acc: 0.9561
Epoch 6/20
8982/8982 [==============================] - 1s 114us/step - loss: 0.1146 - acc: 0.9541
Epoch 7/20
8982/8982 [==============================] - 1s 113us/step - loss: 0.1079 - acc: 0.9541
Epoch 8/20
8982/8982 [==============================] - 1s 114us/step - loss: 0.1068 - acc: 0.9544
Epoch 9/20
8982/8982 [==============================] - 1s 114us/step - loss: 0.1033 - acc: 0.9554
Epoch 10/20
8982/8982 [==============================] - 1s 112us/step - loss: 0.1025 - acc: 0.9571
Epoch 11/

In [98]:
x_train.shape

(8982, 10000)

In [99]:
y_train.shape

(8982,)

In [101]:
results=model1.evaluate(x_test,y_test)
results

2246/2246 [==============================] - 0s 155us/step


[1.480849994258592, 0.7809439003202179]