In [1]:
import numpy as np

In [7]:
timesteps = 100
input_features = 32
output_features = 64

inputs = np.random.random((timesteps, input_features))
state_t = np.zeros((output_features, ))

W = np.random.random((output_features, input_features))
U = np.random.random((output_features, output_features))
b = np.random.random((output_features, ))

successive_outputs = []
for input_t in inputs:
    output_t = np.tanh(np.dot(W, input_t) * np.dot(U, state_t) + b)
    print(np.dot(W, input_t).shape)
    print(np.dot(U, state_t).shape)
    #     print(output_t.shape)
    successive_outputs.append(output_t)
    state_t = output_t
final_output_sequence = np.stack(successive_outputs, axis=0)

(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,)
(64,

In [11]:
a = np.random.random((2, 3))
b = np.random.random(3, )
np.dot(a, b).shape

(2,)

In [12]:
a

array([[0.43944754, 0.75982889, 0.54102391],
       [0.1008274 , 0.95923869, 0.75957365]])

In [13]:
b

array([0.37091718, 0.48685274, 0.73550355])

In [14]:
a * b

array([[0.16299864, 0.36992477, 0.39792501],
       [0.03739861, 0.46700798, 0.55866912]])

In [4]:
final_output_sequence.shape

(100, 64)

simple RNN

In [18]:
from keras.layers import SimpleRNN
from keras import models, layers

In [21]:
model = models.Sequential()
model.add(layers.Embedding(10000, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_2 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
simple_rnn_2 (SimpleRNN)     (None, None, 32)          2080      
Total params: 322,080
Trainable params: 322,080
Non-trainable params: 0
_________________________________________________________________


In [22]:
model = models.Sequential()
model.add(layers.Embedding(10000, 32))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32, return_sequences=True))
model.add(SimpleRNN(32))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_3 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
simple_rnn_3 (SimpleRNN)     (None, None, 32)          2080      
_________________________________________________________________
simple_rnn_4 (SimpleRNN)     (None, None, 32)          2080      
_________________________________________________________________
simple_rnn_5 (SimpleRNN)     (None, None, 32)          2080      
_________________________________________________________________
simple_rnn_6 (SimpleRNN)     (None, 32)                2080      
Total params: 328,320
Trainable params: 328,320
Non-trainable params: 0
_________________________________________________________________


In [24]:
from keras.datasets import imdb
from keras.preprocessing import sequence

In [25]:
max_features = 10000
maxlen = 500
batch_size = 32

(input_train, y_train), (input_test,
                         y_test) = imdb.load_data(num_words=max_features)
print('train shape', input_train.shape)
print('test shape', input_test.shape)

train shape (25000,)
test shape (25000,)


In [27]:
type(input_train)

numpy.ndarray

In [28]:
input_train = sequence.pad_sequences(input_train, maxlen=maxlen)
input_test = sequence.pad_sequences(input_test, maxlen=maxlen)
print('train shape', input_train.shape)
print('test shape', input_test.shape)

train shape (25000, 500)
test shape (25000, 500)


In [29]:
model = models.Sequential()
model.add(layers.Embedding(max_features, 32))
model.add(SimpleRNN(32))
model.add(layers.Dense(1, activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_4 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
simple_rnn_7 (SimpleRNN)     (None, 32)                2080      
_________________________________________________________________
dense_1 (Dense)              (None, 1)                 33        
Total params: 322,113
Trainable params: 322,113
Non-trainable params: 0
_________________________________________________________________


In [30]:
model.compile(optimizer='rmsprop', loss='binary_crossentropy', metrics=['acc'])

In [33]:
history = model.fit(
    input_train,
    y_train,
    epochs=10,
    batch_size=128,
#     validation_split=0.3,
    validation_data=(input_test,y_test)
)

Train on 25000 samples, validate on 25000 samples
Epoch 1/10
25000/25000 [==============================] - 21s 832us/step - loss: 0.2027 - acc: 0.9470 - val_loss: 0.6860 - val_acc: 0.7873
Epoch 2/10
25000/25000 [==============================] - 21s 835us/step - loss: 0.1125 - acc: 0.9640 - val_loss: 0.8077 - val_acc: 0.7618
Epoch 3/10
25000/25000 [==============================] - 21s 838us/step - loss: 0.0691 - acc: 0.9771 - val_loss: 0.7272 - val_acc: 0.7886
Epoch 4/10
25000/25000 [==============================] - 21s 837us/step - loss: 0.0313 - acc: 0.9907 - val_loss: 0.7945 - val_acc: 0.7895
Epoch 5/10
25000/25000 [==============================] - 21s 839us/step - loss: 0.0179 - acc: 0.9945 - val_loss: 0.8379 - val_acc: 0.7888
Epoch 6/10
25000/25000 [==============================] - 21s 834us/step - loss: 0.0097 - acc: 0.9976 - val_loss: 1.0910 - val_acc: 0.7337
Epoch 7/10
25000/25000 [==============================] - 21s 834us/step - loss: 0.0096 - acc: 0.9971 - val_loss: 0.

LSTM

In [34]:
from keras.layers import LSTM

In [36]:
model=models.Sequential()
model.add(layers.Embedding(max_features,32))
model.add(LSTM(32))
model.add(layers.Dense(1,activation='sigmoid'))
model.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
embedding_5 (Embedding)      (None, None, 32)          320000    
_________________________________________________________________
lstm_1 (LSTM)                (None, 32)                8320      
_________________________________________________________________
dense_2 (Dense)              (None, 1)                 33        
Total params: 328,353
Trainable params: 328,353
Non-trainable params: 0
_________________________________________________________________


In [38]:
model.compile(optimizer='rmsprop',loss='binary_crossentropy',metrics=['acc'])

In [40]:
history=model.fit(input_train,y_train,
                 epochs=10,
                 batch_size=128,
                 validation_split=0.2)

Train on 20000 samples, validate on 5000 samples
Epoch 1/10
20000/20000 [==============================] - 44s 2ms/step - loss: 0.5135 - acc: 0.7566 - val_loss: 0.3591 - val_acc: 0.8618
Epoch 2/10
20000/20000 [==============================] - 43s 2ms/step - loss: 0.2984 - acc: 0.8814 - val_loss: 0.3018 - val_acc: 0.8724
Epoch 3/10
20000/20000 [==============================] - 44s 2ms/step - loss: 0.2357 - acc: 0.9108 - val_loss: 0.4518 - val_acc: 0.8332
Epoch 4/10
20000/20000 [==============================] - 43s 2ms/step - loss: 0.2041 - acc: 0.9249 - val_loss: 0.2920 - val_acc: 0.8928
Epoch 5/10
20000/20000 [==============================] - 42s 2ms/step - loss: 0.1747 - acc: 0.9362 - val_loss: 0.5029 - val_acc: 0.8344
Epoch 6/10
20000/20000 [==============================] - 42s 2ms/step - loss: 0.1580 - acc: 0.9431 - val_loss: 0.3215 - val_acc: 0.8694
Epoch 7/10
20000/20000 [==============================] - 43s 2ms/step - loss: 0.1456 - acc: 0.9476 - val_loss: 0.3856 - val_acc: