In [1]:
import torch
import torch.nn as nn

In [3]:
class MyDense(nn.Module):
    def __init__(self):
        super().__init__()
        self.params = nn.ParameterList(
            [nn.Parameter(torch.randn(4, 4)) for i in range(3)])
        self.params.append(nn.Parameter(torch.randn(4, 1)))

    def forward(self, x):
        for i in range(len(self.params)):
            x = torch.mm(x, self.params(i))
        return x

In [4]:
net=MyDense()
print(net)

MyDense(
  (params): ParameterList(
      (0): Parameter containing: [torch.FloatTensor of size 4x4]
      (1): Parameter containing: [torch.FloatTensor of size 4x4]
      (2): Parameter containing: [torch.FloatTensor of size 4x4]
      (3): Parameter containing: [torch.FloatTensor of size 4x1]
  )
)


In [5]:
for name,param in net.named_parameters():
    print(name,param)

params.0 Parameter containing:
tensor([[ 1.0099,  0.5158,  1.0606, -0.5733],
        [-0.3525,  0.0515,  0.0579, -0.9683],
        [-0.7151,  0.6750, -1.0326,  0.5828],
        [-0.1999,  1.0208,  0.4795, -1.1017]], requires_grad=True)
params.1 Parameter containing:
tensor([[-0.5101,  1.5720, -1.0204, -0.6349],
        [-0.8790, -0.7066, -1.0050,  0.7380],
        [-0.2220,  1.3313, -1.1594, -1.9360],
        [ 0.3923, -1.3781, -0.9208, -0.7986]], requires_grad=True)
params.2 Parameter containing:
tensor([[ 0.5977,  0.3003,  0.0580, -0.3036],
        [-0.4008, -0.6201,  0.3158,  0.1258],
        [ 0.3838,  1.0939, -0.2876, -2.2555],
        [-0.6423,  1.0438,  0.2701, -0.1838]], requires_grad=True)
params.3 Parameter containing:
tensor([[ 0.7046],
        [ 0.0374],
        [ 0.0364],
        [-0.4158]], requires_grad=True)


In [8]:
class MyDictDense(nn.Module):
    def __init__(self):
        super().__init__()
        self.params=nn.ParameterDict({
            'linear1':nn.Parameter(torch.randn(4,4)),
            'linear2':nn.Parameter(torch.randn(4,1))
        })
        self.params.update({'linear3':nn.Parameter(
            torch.randn(4,2))})
        
    def forward(self,x,choice='linear1'):
        return torch.mm(x,self.params[choice])

In [9]:
net=MyDictDense()
print(net)

MyDictDense(
  (params): ParameterDict(
      (linear1): Parameter containing: [torch.FloatTensor of size 4x4]
      (linear2): Parameter containing: [torch.FloatTensor of size 4x1]
      (linear3): Parameter containing: [torch.FloatTensor of size 4x2]
  )
)
