In [17]:
import numpy as np
from hmmlearn import hmm
import matplotlib.pyplot as plt
import matplotlib as mpl
from sklearn.metrics.pairwise import pairwise_distances_argmin
import warnings
%matplotlib

Using matplotlib backend: Qt5Agg


In [18]:
def expand(a,b):
    d=(b-a)*0.05
    return a-d,b+d

In [19]:
## # 0日期  1开盘  2最高  3最低  4收盘  5成交量  6成交额
x=np.loadtxt(r'F:\study\ml\DoctorZou\24HMMII\24.HMM\24.SH600000.txt',
            delimiter='\t',skiprows=3,usecols=(4,5,6,2,3),encoding='gbk')

np.set_printoptions(suppress=True)
x

array([[1.01500000e+01, 1.15147943e+08, 2.43689088e+09, 1.02900000e+01,
        9.82000000e+00],
       [9.91000000e+00, 9.67825750e+07, 2.03417408e+09, 1.01200000e+01,
        9.88000000e+00],
       [9.63000000e+00, 8.52360720e+07, 1.76180096e+09, 9.97000000e+00,
        9.53000000e+00],
       ...,
       [1.82900000e+01, 3.56315260e+07, 6.50177344e+08, 1.84000000e+01,
        1.79200000e+01],
       [1.81900000e+01, 1.83124240e+07, 3.33790688e+08, 1.83500000e+01,
        1.81300000e+01],
       [1.80200000e+01, 1.77865250e+07, 3.21768768e+08, 1.83000000e+01,
        1.79300000e+01]])

In [20]:
close_price=x[:,0] #收盘
volumn=x[:,1]  #成交量
amount=x[:,2]  #成交额
amplitude_price=x[:,3]-x[:,4] #最高2 -最低3 每天的最高价与最低价的差
diff_price=np.diff(close_price) #涨跌值
volumn=volumn[1:]  #因为diff price 少了一行,所以其他的都从第二行取
amount=amount[1:]
amplitude_price=amplitude_price[1:]
sample=np.column_stack((diff_price,volumn,amount,amplitude_price))

In [21]:
n=5
model=hmm.GaussianHMM(n_components=n,covariance_type='full')
model.fit(sample)

GaussianHMM(algorithm='viterbi', covariance_type='full', covars_prior=0.01,
      covars_weight=1, init_params='stmc', means_prior=0, means_weight=0,
      min_covar=0.001, n_components=5, n_iter=10, params='stmc',
      random_state=None, startprob_prior=1.0, tol=0.01, transmat_prior=1.0,
      verbose=False)

In [22]:
y=model.predict_proba(sample)
np.set_printoptions(suppress=True)
y

array([[0.        , 0.        , 0.        , 0.        , 1.        ],
       [0.01113344, 0.000457  , 0.        , 0.00002736, 0.9883822 ],
       [0.4314479 , 0.00074667, 0.        , 0.00003994, 0.56776549],
       ...,
       [0.98656417, 0.00000004, 0.        , 0.        , 0.01343579],
       [0.99860137, 0.0000007 , 0.00067077, 0.        , 0.00072715],
       [0.99308993, 0.00006616, 0.00000861, 0.00000043, 0.00683488]])

In [29]:
t=np.arange(len(diff_price))
plt.figure(figsize=(8,6),facecolor='w')
plt.subplot(421)
plt.plot(t,diff_price,'r-')
plt.grid(True)
plt.title('amplitude_price')
plt.subplot(422)
plt.plot(t,volumn,'g-')
plt.grid(True)
plt.title('Volumn')

clrs=plt.cm.terrain(np.linspace(0,0.8,n))
plt.subplot(423)
for i,clr in enumerate(clrs):
    plt.plot(t,y[:,i],'-',color=clr,alpha=0.7)
plt.title('all group')
plt.grid(True)
for i,clr in enumerate(clrs):
    axes=plt.subplot(4,2,i+4)
    plt.plot(t,y[:,i],'-',color=clr)
    plt.title('group : %d' % (i+1))
    plt.grid(True)
plt.suptitle('stock : GauessianHMM',fontsize=15)
plt.tight_layout()
plt.subplots_adjust(top=0.9)
plt.show()

In [30]:
plt.cm.terrain(np.linspace(0,0.8,n))

array([[0.2  , 0.2  , 0.6  , 1.   ],
       [0.   , 0.7  , 0.7  , 1.   ],
       [0.6  , 0.92 , 0.52 , 1.   ],
       [0.8  , 0.744, 0.492, 1.   ],
       [0.6  , 0.488, 0.464, 1.   ]])

In [31]:
np.linspace(0,0.8,n)

array([0. , 0.2, 0.4, 0.6, 0.8])