In [1]:
import torch
import torch.nn.functional as F
from torch import nn

In [2]:
class CenteredLayer(nn.Module):
    def __init__(self):
        super().__init__()
    
    def forward(self,X):
        return X-X.mean()

In [3]:
layer=CenteredLayer()
layer(torch.FloatTensor([1,2,3,4,5]))

tensor([-2., -1.,  0.,  1.,  2.])

In [6]:
net=nn.Sequential(nn.Linear(8,128),CenteredLayer())
Y=net(torch.rand(4,8))
Y.mean()

tensor(-1.0128e-08, grad_fn=<MeanBackward0>)

In [7]:
class MyLinear(nn.Module):
    def __init__(self,in_units,untis):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(in_units,untis))
        self.bias=nn.Parameter(torch.rand(untis,))
    
    def forward(self,X):
        linear=torch.matmul(X,self.weight.data)+self.bias.data
        return F.relu(linear)

In [8]:
linear=MyLinear(5,3)
linear.weight

Parameter containing:
tensor([[ 0.1805, -1.1236,  0.2263],
        [-2.2103,  0.9254, -1.5881],
        [-0.2484,  0.8257,  1.3524],
        [ 0.3061, -0.8613, -0.3879],
        [ 0.7917, -0.5223,  0.3630]], requires_grad=True)

In [9]:
linear(torch.rand(2,5))

tensor([[0.0000, 0.9769, 0.3570],
        [0.0000, 0.2553, 0.3827]])

In [12]:
net=nn.Sequential(MyLinear(64,8),MyLinear(8,1))
net(torch.rand(2,64))

tensor([[0.2444],
        [0.9226]])