In [1]:
import torch
from torch import nn,optim

In [2]:
torch.__version__

'1.6.0+cpu'

In [3]:
net=torch.nn.Sequential(nn.Linear(1,10),
                       nn.ReLU(),
                       nn.Linear(10,1))

In [4]:
net

Sequential(
  (0): Linear(in_features=1, out_features=10, bias=True)
  (1): ReLU()
  (2): Linear(in_features=10, out_features=1, bias=True)
)

In [5]:
x=torch.arange(-100,100)
x.shape

torch.Size([200])

In [6]:
x

tensor([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90,  -89,
         -88,  -87,  -86,  -85,  -84,  -83,  -82,  -81,  -80,  -79,  -78,  -77,
         -76,  -75,  -74,  -73,  -72,  -71,  -70,  -69,  -68,  -67,  -66,  -65,
         -64,  -63,  -62,  -61,  -60,  -59,  -58,  -57,  -56,  -55,  -54,  -53,
         -52,  -51,  -50,  -49,  -48,  -47,  -46,  -45,  -44,  -43,  -42,  -41,
         -40,  -39,  -38,  -37,  -36,  -35,  -34,  -33,  -32,  -31,  -30,  -29,
         -28,  -27,  -26,  -25,  -24,  -23,  -22,  -21,  -20,  -19,  -18,  -17,
         -16,  -15,  -14,  -13,  -12,  -11,  -10,   -9,   -8,   -7,   -6,   -5,
          -4,   -3,   -2,   -1,    0,    1,    2,    3,    4,    5,    6,    7,
           8,    9,   10,   11,   12,   13,   14,   15,   16,   17,   18,   19,
          20,   21,   22,   23,   24,   25,   26,   27,   28,   29,   30,   31,
          32,   33,   34,   35,   36,   37,   38,   39,   40,   41,   42,   43,
          44,   45,   46,   47,   48,   

In [7]:
x=torch.unsqueeze(torch.arange(-100,100),dim=1).float()
x.shape

torch.Size([200, 1])

In [8]:
x

tensor([[-100.],
        [ -99.],
        [ -98.],
        [ -97.],
        [ -96.],
        [ -95.],
        [ -94.],
        [ -93.],
        [ -92.],
        [ -91.],
        [ -90.],
        [ -89.],
        [ -88.],
        [ -87.],
        [ -86.],
        [ -85.],
        [ -84.],
        [ -83.],
        [ -82.],
        [ -81.],
        [ -80.],
        [ -79.],
        [ -78.],
        [ -77.],
        [ -76.],
        [ -75.],
        [ -74.],
        [ -73.],
        [ -72.],
        [ -71.],
        [ -70.],
        [ -69.],
        [ -68.],
        [ -67.],
        [ -66.],
        [ -65.],
        [ -64.],
        [ -63.],
        [ -62.],
        [ -61.],
        [ -60.],
        [ -59.],
        [ -58.],
        [ -57.],
        [ -56.],
        [ -55.],
        [ -54.],
        [ -53.],
        [ -52.],
        [ -51.],
        [ -50.],
        [ -49.],
        [ -48.],
        [ -47.],
        [ -46.],
        [ -45.],
        [ -44.],
        [ -43.],
        [ -42.

In [9]:
y=x.pow(2)
y.shape

torch.Size([200, 1])

In [10]:
def save1():
    optimizer=optim.Adam(net.parameters(),lr=0.1)
    loss_func=nn.MSELoss()
    for t in range(2000):
        predictions=net(x)
        l=loss_func(predictions,y)
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    torch.save(net,r'F:\study\ml\rknn\models\test_net2.pt')
    input_shape=(1)
    batch_size=1
    
    input_data_shape=torch.randn(batch_size,input_shape)
    torch.onnx.export(net,input_shape,r'F:\study\ml\rknn\models\test_net2.onnx',verbose=True)

In [11]:
save1()

RuntimeError: Only tuples, lists and Variables supported as JIT inputs/outputs. Dictionaries and strings are also accepted but their usage is not recommended. But got unsupported type int

In [ ]:
def save():
    optimizer=optim.Adam(net.parameters(),lr=0.1)
    loss_func=nn.MSELoss()
    for t in range(2000):
        predictions=net(x)
        l=loss_func(predictions,y)
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    torch.save(net,r'F:\study\ml\rknn\models\test_net2.pt')
    input_shape=(1)
    batch_size=1
    
    input_data_shape=torch.randn(batch_size,input_shape)
    torch.onnx.export(net,input_data_shape,r'F:\study\ml\rknn\models\test_net2.onnx',verbose=True)


In [12]:
input_shape=(1)
batch_size=1
type(torch.randn(batch_size,input_shape))

torch.Tensor

In [13]:
type(torch.randn(batch_size))

torch.Tensor

In [14]:
save()

'' was not found in history, as a file, url, nor in the user namespace.


In [15]:
import torch 
import onnxruntime as rt
import numpy as np
input_test_data=torch.Tensor([[15]])
net=torch.load(r'F:\study\ml\rknn\models\test_net2.pt')
prediction=net(input_test_data)
print(prediction)


tensor([[180.4134]], grad_fn=<AddmmBackward>)


D:\ProgramData\Anaconda3\lib\site-packages\onnxruntime\capi\onnxruntime_validation.py:29: UserWarning: Unsupported Windows version (7). ONNX Runtime supports Windows 10 and above, only.
  warnings.warn('Unsupported Windows version (%s). ONNX Runtime supports Windows 10 and above, only.' % __my_distro_ver__)


In [17]:
rt.__version__

'1.1.0'

In [18]:
sess=rt.InferenceSession(r'F:\study\ml\rknn\models\test_net2.onnx')
input_name=sess.get_inputs()[0].name
print(input_name)
pred_oxn=sess.run(None,{input_name:input_test_data.numpy()})[0]
print(pred_oxn)

input.1
[[203.70389]]


In [24]:
from rknnlite.api import RKNNLite as RKNN
import numpy as np

model=r'/tmp/test_net2.rknn'
input_test_data=np.array([15],dtype=np.float32)
rknn=RKNN()
ret=rknn.load_rknn(path=model)
print('---- init runtime env ')
ret=rknn.init_runtime()
if ret !=0:
    print(' ---- init runtime env failed !')
    exit(ret)
print('----init down')
output=rknn.inference(inputs=[input_test_data])
print(output)

ModuleNotFoundError: No module named 'rknnlite'