In [13]:
import torch

In [14]:
def corr2d(X,K):
    print(K.shape)
    kw,kh=K.shape
    w,h=X.shape
    Y=torch.zeros((w-kw+1,h-kh+1))
    for i in range(w-kw+1):
        for j in range(h-kh+1):
            Y[i][j]=(X[i:i+kw,j:j+kh]*K).sum()
    return Y

In [15]:
X = torch.tensor([[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]])
K = torch.tensor([[0.0, 1.0], [2.0, 3.0]])
corr2d(X, K)

torch.Size([2, 2])


tensor([[19., 25.],
        [37., 43.]])

In [16]:
def corr2d_multi_in(X,K):
    return sum(corr2d(x,k) for x, k in zip(X,K))

In [17]:
X = torch.tensor([[[0.0, 1.0, 2.0], [3.0, 4.0, 5.0], [6.0, 7.0, 8.0]],
[[1.0, 2.0, 3.0], [4.0, 5.0, 6.0], [7.0, 8.0, 9.0]]])

In [18]:
K = torch.tensor([[[0.0, 1.0], [2.0, 3.0]], [[1.0, 2.0], [3.0, 4.0]]])

In [19]:
X.shape

torch.Size([2, 3, 3])

In [20]:
K.shape

torch.Size([2, 2, 2])

In [21]:
corr2d_multi_in(X,K)

torch.Size([2, 2])
torch.Size([2, 2])


tensor([[ 56.,  72.],
        [104., 120.]])

In [22]:
def corr2d_multi_in_out(X,K):
    return torch.stack([corr2d_multi_in(X,k) for k in K],0)

In [23]:
K=torch.stack((K,K+1,K+2),0)
K

tensor([[[[0., 1.],
          [2., 3.]],

         [[1., 2.],
          [3., 4.]]],


        [[[1., 2.],
          [3., 4.]],

         [[2., 3.],
          [4., 5.]]],


        [[[2., 3.],
          [4., 5.]],

         [[3., 4.],
          [5., 6.]]]])

In [24]:
K.shape

torch.Size([3, 2, 2, 2])

In [25]:
corr2d_multi_in_out(X,K)

torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])
torch.Size([2, 2])


tensor([[[ 56.,  72.],
         [104., 120.]],

        [[ 76., 100.],
         [148., 172.]],

        [[ 96., 128.],
         [192., 224.]]])

In [26]:
def corr2d_multi_in_out_1x1(X,K):
    ci,h,w=X.shape
    co=K.shape[0]
    X=X.reshape((ci,h*w))
    K=K.reshape((co,ci))
    Y=torch.matmul(K,X)
    return Y.reshape((co,h,w))
    

In [27]:
X = torch.normal(0, 1, (3, 3, 3))
K = torch.normal(0, 1, (2, 3, 1, 1))

In [28]:
Y1 = corr2d_multi_in_out_1x1(X, K)
Y2 = corr2d_multi_in_out(X, K)
assert float(torch.abs(Y1 - Y2).sum()) < 1e-6

torch.Size([1, 1])
torch.Size([1, 1])
torch.Size([1, 1])
torch.Size([1, 1])
torch.Size([1, 1])
torch.Size([1, 1])


In [29]:
Y1.shape

torch.Size([2, 3, 3])