In [66]:
import torch
from time import time
import numpy as np

In [67]:
def iter_data(batch_size,features,labels):
    num_example=len(features)
    indices=list(range(num_example))
    np.random.shuffle(indices)
    for i in range(0,num_example,batch_size):
        j=torch.tensor(indices[i:min(i+batch_size,num_example)])
        yield features.index_select(0,j),labels.index_select(0,j)

In [68]:
def linreg(x,w,b):
    return torch.mm(x,w)+b

In [69]:
def squared_loss(y_hat,y):
    return (y_hat-y.view(y_hat.size()))**2/2

In [70]:
def sgd(params,lr,batch_size):
    for param in params:
        param.data -= lr/batch_size*param.grad

In [71]:
features=torch.tensor(np.random.normal(0,1,(1000,2)),dtype=torch.float32)

In [72]:
features.dtype

torch.float32

In [73]:
w=torch.tensor(np.random.normal(0,0.1,(2,1)),dtype=torch.float32)
b=torch.zeros(1,dtype=torch.float32)

In [74]:
true_w=[2,-3,4]
true_b=4.2
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=torch.tensor(np.random.normal(0.0,0.01,labels.size()),dtype=torch.float32)

In [75]:
batch_size=10
for x1,y1 in iter_data(10,features,labels):
    print(x1,y1)
    break

tensor([[-1.2419, -0.7994],
        [ 0.8396,  0.5751],
        [ 0.3046, -0.7479],
        [ 1.7906,  0.4773],
        [-0.7976,  0.8225],
        [ 0.1485,  0.0592],
        [ 1.0832,  0.7842],
        [-2.5265, -1.9740],
        [-0.3906, -0.3408],
        [-0.0827,  1.1277]]) tensor([4.1129, 4.1507, 7.0295, 6.3530, 0.1402, 4.3257, 4.0136, 5.0594, 4.4581,
        0.6522])


In [76]:
w.requires_grad_(True)
b.requires_grad_(True)

tensor([0.], requires_grad=True)

In [79]:
lr=0.03
epoch=3
for i in range(epoch):
    for x,y in iter_data(batch_size,features,labels):
        l=squared_loss(linreg(x,w,b),y).sum()
        l.backward()
        sgd([w,b],lr,batch_size)
        w.grad.data.zero_()
        b.grad.data.zero_()

    train_l=squared_loss(linreg(features,w,b),labels).sum()
    print('epoch #%d train loss:%f' % (i,train_l))
    
    

epoch #0 train loss:0.047631
epoch #1 train loss:0.047445
epoch #2 train loss:0.047518


In [52]:
print(w)
print(b)

tensor([[ 2.0003],
        [-3.0000]], requires_grad=True)
tensor([4.1996], requires_grad=True)
