In [2]:
import torch
import numpy as np

In [82]:
true_w=[3.5,-4.6,5.7]
true_b=2.5
features=torch.tensor(np.random.normal(0,2,(1000,2)),dtype=torch.float32)

In [83]:
labels=features[:,0]*true_w[0]+features[:,1]*true_w[1]+true_b
labels+=torch.tensor(np.random.normal(0,0.01,(1000)),dtype=torch.float32)

In [84]:
def data_iter(batch_size,features,labels):
    examples_num=len(features)
    indices=list(range(examples_num))
    np.random.shuffle(indices)
    for i in range(0,examples_num,batch_size):
        j=torch.tensor(indices[i:min(i+batch_size,examples_num)])
        yield features.index_select(0,j),labels.index_select(0,j)

In [85]:
batch_size=10
for x,y in data_iter(batch_size,features,labels):
    print(x,y)
    break

tensor([[ 4.9075,  2.9783],
        [-1.9416,  6.8681],
        [-0.2263, -1.7347],
        [-1.7844, -0.1361],
        [-0.7778,  1.3704],
        [-0.8090,  0.0520],
        [ 2.1296,  1.9587],
        [-1.5466, -0.6352],
        [ 0.5957, -3.8579],
        [-2.2502,  1.1304]]) tensor([ 5.9845e+00, -3.5884e+01,  9.6753e+00, -3.1064e+00, -6.5235e+00,
        -5.8488e-01,  9.5984e-01,  5.8146e-03,  2.2336e+01, -1.0587e+01])


In [86]:
w=torch.tensor(np.random.normal(0,0.5,(2,1)),dtype=torch.float32)
b=torch.zeros((1,1),dtype=torch.float32)

In [87]:
w.requires_grad_(True)
b.requires_grad_(True)

tensor([[0.]], requires_grad=True)

In [88]:
def linreg(x,w,b):
    return torch.mm(x,w)+b

In [89]:
def squard_loss(y_hat,y):
    return (y_hat-y.view(y_hat.size()))**2/2

In [90]:
def sgd(params,lr,batch_size):
    for param in params:
        param.data -=param.grad*lr/batch_size

In [93]:
lr=0.05
epochs=10
for i in range(epochs):
    for x,y in data_iter(batch_size,features,labels):
        l=squard_loss(linreg(x,w,b),y).sum()
        l.backward()
        sgd([w,b],lr,batch_size)
        
        w.grad.data.zero_()
        b.grad.data.zero_()
    train_l=squard_loss(linreg(features,w,b),labels).sum()
    print('round #%d loss: %f ' % (i+1,train_l))
        
        
        

round #1 loss: 0.049081 
round #2 loss: 0.050097 
round #3 loss: 0.049199 
round #4 loss: 0.049840 
round #5 loss: 0.050529 
round #6 loss: 0.048393 
round #7 loss: 0.048498 
round #8 loss: 0.050668 
round #9 loss: 0.048765 
round #10 loss: 0.048351 


In [35]:
print(w,b)

tensor([[ 6.1900],
        [-9.1546]], requires_grad=True) tensor([[2.8194]], requires_grad=True)
