In [ ]:
import torch
import numpy as np

In [ ]:
num_inputs=2
num_examples=1000
true_w=[2,3-3.4]
true_b=4.2
features=torch.tensor(np.random.normal(0,1,(num_examples,num_inputs)),dtype=torch.float)

In [ ]:
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=torch.tensor(np.random.normal(0,0.01,labels.size()),dtype=torch.float)

In [4]:
import torch.utils.data as Data

In [5]:
batch_size=10
dataset=Data.TensorDataset(features,labels)
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)

In [6]:
for x,y in data_iter:
    print(x,y)
    break

tensor([[ 0.7392,  1.1222],
        [-0.5580,  1.2157],
        [ 0.1676, -1.4076],
        [ 0.2697,  0.1717],
        [ 0.3225,  1.0654],
        [ 0.3005,  0.8725],
        [ 0.5997, -0.3057],
        [ 1.0199,  0.4925],
        [-0.0588, -0.1725],
        [ 0.5803,  0.7607]]) tensor([5.2335, 2.5712, 5.0939, 4.6775, 4.4274, 4.4442, 5.5344, 6.0527, 4.1652,
        5.0644])


In [8]:
import torch.nn as nn

In [9]:
class LinearNet(nn.Module):
    def __init__(self,n_feature):
        super(LinearNet,self).__init__()
        self.linear=nn.Linear(n_feature,1)
    
    def forward(self,x):
        y=self.linear(x)
        return y

In [10]:
net=LinearNet(num_inputs)
print(net)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [11]:
net=nn.Sequential()
net.add_module('linear',nn.Linear(num_inputs,1))

In [12]:
print(net)
print(net[0])

Sequential(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [13]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[0.6976, 0.2523]], requires_grad=True)
Parameter containing:
tensor([-0.2828], requires_grad=True)


In [14]:
from torch.nn import init

In [15]:
init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [16]:
loss=nn.MSELoss()

In [17]:
import torch.optim as optim

In [18]:
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [20]:
num_epochs=3
for epoch in range(1,num_epochs+1):
    for x,y in data_iter:
        output=net(x)
        l=loss(output,y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    print('epoch %d,loss :%f' % (epoch,l.item()))

epoch 1,loss :0.000104
epoch 2,loss :0.000051
epoch 3,loss :0.000058
