In [1]:
import torch
import numpy as np

In [2]:
batch_size=10
num_inputs=2
num_examples=1000
features=torch.tensor(np.random.normal(0,1,(num_examples,num_inputs)),
                      dtype=torch.float)
true_w=[2,-3,4]
true_b=4.2
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=torch.tensor(np.random.normal(0,0.01,size=labels.size()),dtype=torch.float)

In [3]:
import torch.utils.data as Data

In [4]:
dataset=Data.TensorDataset(features,labels)
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)

In [5]:
type(dataset)

torch.utils.data.dataset.TensorDataset

In [6]:
for x,y in data_iter:
    print(x,y)
    break

tensor([[ 0.3376, -0.1231],
        [-0.3678, -1.5541],
        [-0.5825, -0.6905],
        [ 0.1848,  0.9517],
        [ 0.6958, -1.0191],
        [ 1.6008, -0.3877],
        [ 0.8311,  0.2024],
        [-0.1609,  1.2679],
        [ 0.8361,  1.6201],
        [-1.8695,  1.9877]]) tensor([ 5.2384,  8.1200,  5.1194,  1.7224,  8.6520,  8.5563,  5.2634,  0.0681,
         1.0331, -5.4936])


In [7]:
import torch.nn as nn

In [8]:
net=nn.Sequential()
net.add_module('linearnet',nn.Linear(num_inputs,1))

In [9]:
for param in net.parameters():
    print(param)

Parameter containing:
tensor([[-0.4859,  0.4456]], requires_grad=True)
Parameter containing:
tensor([0.6721], requires_grad=True)


In [10]:
print(net)
print(net[0])

Sequential(
  (linearnet): Linear(in_features=2, out_features=1, bias=True)
)
Linear(in_features=2, out_features=1, bias=True)


In [11]:
from torch.nn import init

In [12]:
init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [13]:
loss=nn.MSELoss()

In [14]:
import torch.optim as optim

In [15]:
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [16]:
num_epochs=3
for epoch in range(num_epochs):
    for x,y in data_iter:
        output=net(x)
        l=loss(output,y.view(output.size()))

        l.backward()
        optimizer.step()
        optimizer.zero_grad()
    print('epoch %d,loss :%f' % (epoch,l.item()))
        
        

epoch 0,loss :0.000394
epoch 1,loss :0.000125
epoch 2,loss :0.000032


In [17]:
print(net[0].weight,net[0].bias)

Parameter containing:
tensor([[ 1.9997, -3.0005]], requires_grad=True) Parameter containing:
tensor([4.1992], requires_grad=True)
