In [ ]:
import torch
import torchvision
import numpy as np
import sys
import torchvision.transforms as transforms

In [2]:
batch_size=256
mnist_train=torchvision.datasets.FashionMNIST(
    root='F:\study\ml\DataSet\FashionMNIST',train=True,
    download=True,transform=transforms.ToTensor())
mnist_test=torchvision.datasets.FashionMNIST(
    root='F:\study\ml\DataSet\FashionMNIST',train=False,
    download=True,transform=transforms.ToTensor())

In [4]:
mnist_train[0][0]

tensor([[[0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000],
         [0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000, 0.0000,
          0.0000, 0.0000, 0.0000, 0.0000, 0.0039, 0.0000, 0.0000, 0.0510,
          0.2863, 0.0000, 0.0000, 0.0039, 0.0157, 0.0000,

In [5]:
train_x,train_y=[],[]
for i in range(len(mnist_train)):
    train_x.append(mnist_train[i][0])
    train_y.append(mnist_train[i][1])

In [7]:
test_x,test_y=[],[]
for i in range(len(mnist_test)):
    test_x.append(mnist_test[i][0])
    test_y.append(mnist_test[i][1])

In [8]:
train_iter=torch.utils.data.DataLoader(mnist_train,batch_size,shuffle=True)

In [9]:
test_iter=torch.utils.data.DataLoader(mnist_test,batch_size,shuffle=True)

In [10]:
num_inputs=784
num_outputs=10

w=torch.tensor(np.random.normal(0,0.01,(num_inputs,num_outputs)),dtype=torch.float)
b=torch.zeros(num_outputs,dtype=torch.float)

In [11]:
w.requires_grad_(True)
b.requires_grad_(True)

tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.], requires_grad=True)

In [12]:
x=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
print(x.sum(dim=0,keepdim=True))
print(x.sum(dim=1,keepdim=True))

tensor([[5., 7., 9.]])
tensor([[ 6.],
        [15.]])


In [13]:
def softmax(x):
    x_exp=x.exp()
    partition=x_exp.sum(dim=1,keepdim=True)
    return x_exp /partition

In [14]:
softmax(x)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [15]:
x.exp()

tensor([[  2.7183,   7.3891,  20.0855],
        [ 54.5981, 148.4132, 403.4288]])

In [16]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
np.exp(5)

In [ ]:
x.exp().sum(dim=1,keepdim=True)

In [17]:
x=torch.tensor([[1,2,3],[4,5,6]],dtype=torch.float)
print(x.sum(dim=0,keepdim=True))
print(x.sum(dim=1,keepdim=True))

tensor([[5., 7., 9.]])
tensor([[ 6.],
        [15.]])


In [18]:
x.dtype

torch.float32

In [ ]:
x=torch.rand((2,5))
x_prob=softmax(x)
print(x_prob,x_prob.sum(dim=1))

In [19]:
x.exp().sum()

tensor(636.6330)

In [21]:
x.exp().sum(dim=1)

tensor([ 30.1929, 606.4401])

In [22]:
softmax(x)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [23]:
def net(x):
    return softmax(torch.mm(x.view((-1,num_inputs)),w)+b)

In [24]:
x

tensor([[1., 2., 3.],
        [4., 5., 6.]])

In [ ]:
w.size()

In [25]:
x.view(-1,2)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])

In [28]:
def accuracy(y_hat,y):
    return (y_hat.argmax(dim=1)==y).float().mean().item()

In [27]:
def evaluate_accuracy(data_iter,net):
    acc_sum,n=0.0,0
    for x,y in data_iter:
        acc_sum+=(net(x).argmax(dim=1)==y).float().sum().item()
        n+=y.shape[0]
    return acc_sum /n

In [ ]:
train_y[0]

In [ ]:
print(evaluate_accuracy(test_iter,net))

In [ ]:
num_epochs,lr=5,0.1

In [ ]:
def sgd(params,lr,batch_size):
    for param in params:
        param.data -=param.grad*lr/batch_size

In [ ]:
def train_ch3(net,train_iter,test_iter,loss,num_epochs,batch_size,params=None
              ,lr=None,optimizer=None):
    for epoch in range(num_epochs):
        train_l_sum,train_acc_sum,n=0.0,0.0,0
        for x,y in train_iter:
            y_hat=net(x)
            l=loss(y_hat,y).sum()
            
            if optimizer is not None:
                optimizer.zero_grad()
            elif params is not None and params[0].grad is not None:
                for param in params:
                    param.grad.data.zero_()
            
            l.backward()
            if optimizer is None:
                sgd(params,lr,batch_size)
            else:
                optimizer.step()
            

In [ ]:
8a1+10a2-2=0
a1=(1-5a2)/4

In [ ]:
13a2+10a1-2=0
13a2+10*((1-5a2)/4)-2=0
13a2+5*(1-5a2)/2-2=26a2+5-25a2-4=0
a2+1=0
a2=-1
a1=3/2


In [ ]:
x1=(3,3),x3=(1,1),x2=(4,3)
w=1/4*x1+(-1/4*x3)=(3/4,3/4)-(1/4,1/4)=(1/2,1/2)
when j=1 ,b=1-(1/4*x1*x1+(-1/4*x3*x1))=-2
when j=2 ,b=1-(1/4*x1*x2+(-1/4*x3*x2))=1-(21/4+(-7/4))=-5/2
when j=3 ,b=-1-(1/4*x1*x3+(-1/4*x3*x3))=-1-(6/4+(-2/4))=-2

In [3]:
26677/28

952.75

In [4]:
365*24

8760

In [5]:
26*6+60

216

In [6]:
216/8

27.0

In [7]:
12.9*0.9

11.610000000000001

In [11]:
140/170

0.8235294117647058

In [10]:
96/6

16.0

In [12]:
96*0.82

78.72

In [13]:
78/6

13.0