In [1]:
import torch

In [2]:
x=torch.empty(5,3)
x

tensor([[1.9198e-43, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 1.3957e-42, 0.0000e+00],
        [0.0000e+00, 6.3367e-39, 0.0000e+00]])

In [3]:
x=torch.rand(5,3)
x

tensor([[0.0833, 0.7465, 0.6916],
        [0.0461, 0.9431, 0.4573],
        [0.4396, 0.3135, 0.3032],
        [0.7038, 0.2091, 0.4151],
        [0.6975, 0.4407, 0.8387]])

In [4]:
x=torch.zeros(5,3,dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [5]:
x=torch.tensor([5.5,3])
x

tensor([5.5000, 3.0000])

In [6]:
x=x.new_ones(5,3,dtype=torch.float64)
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)

In [7]:
x=torch.randn_like(x,dtype=torch.float)
x

tensor([[-0.7602, -1.8718, -0.6580],
        [ 0.6647,  0.6374, -0.1416],
        [-0.9944,  1.0192, -1.3543],
        [-0.8140, -0.0903,  0.2102],
        [ 0.3114,  0.0051,  0.5847]])

In [8]:
x.size()

torch.Size([5, 3])

In [9]:
x.shape

torch.Size([5, 3])

In [10]:
y=torch.rand(5,3)
y

tensor([[0.2322, 0.3927, 0.3917],
        [0.2010, 0.6799, 0.7783],
        [0.0407, 0.6415, 0.2667],
        [0.9234, 0.6290, 0.2160],
        [0.0580, 0.9979, 0.7959]])

In [11]:
x+y


tensor([[-0.5279, -1.4791, -0.2663],
        [ 0.8656,  1.3173,  0.6367],
        [-0.9537,  1.6606, -1.0877],
        [ 0.1094,  0.5388,  0.4262],
        [ 0.3694,  1.0030,  1.3807]])

In [12]:
torch.add(x,y)

tensor([[-0.5279, -1.4791, -0.2663],
        [ 0.8656,  1.3173,  0.6367],
        [-0.9537,  1.6606, -1.0877],
        [ 0.1094,  0.5388,  0.4262],
        [ 0.3694,  1.0030,  1.3807]])

In [13]:
result=torch.empty(5,3)
torch.add(x,y,out=result)
result

tensor([[-0.5279, -1.4791, -0.2663],
        [ 0.8656,  1.3173,  0.6367],
        [-0.9537,  1.6606, -1.0877],
        [ 0.1094,  0.5388,  0.4262],
        [ 0.3694,  1.0030,  1.3807]])

In [14]:
y.add_(x)
y

tensor([[-0.5279, -1.4791, -0.2663],
        [ 0.8656,  1.3173,  0.6367],
        [-0.9537,  1.6606, -1.0877],
        [ 0.1094,  0.5388,  0.4262],
        [ 0.3694,  1.0030,  1.3807]])

In [15]:
y=x[0,:]
y+=1
y

tensor([ 0.2398, -0.8718,  0.3420])

In [16]:
x[0,:]

tensor([ 0.2398, -0.8718,  0.3420])

In [17]:
x

tensor([[ 0.2398, -0.8718,  0.3420],
        [ 0.6647,  0.6374, -0.1416],
        [-0.9944,  1.0192, -1.3543],
        [-0.8140, -0.0903,  0.2102],
        [ 0.3114,  0.0051,  0.5847]])

In [18]:
x.shape

torch.Size([5, 3])

In [19]:
x.view(15)

tensor([ 0.2398, -0.8718,  0.3420,  0.6647,  0.6374, -0.1416, -0.9944,  1.0192,
        -1.3543, -0.8140, -0.0903,  0.2102,  0.3114,  0.0051,  0.5847])

In [20]:
x.view(-1,5)

tensor([[ 0.2398, -0.8718,  0.3420,  0.6647,  0.6374],
        [-0.1416, -0.9944,  1.0192, -1.3543, -0.8140],
        [-0.0903,  0.2102,  0.3114,  0.0051,  0.5847]])

In [21]:
y=x.view(15)
z=x.view(-1,5)

In [22]:
y.shape

torch.Size([15])

In [23]:
z.shape

torch.Size([3, 5])

In [24]:
x+=1
x

tensor([[ 1.2398,  0.1282,  1.3420],
        [ 1.6647,  1.6374,  0.8584],
        [ 0.0056,  2.0192, -0.3543],
        [ 0.1860,  0.9097,  1.2102],
        [ 1.3114,  1.0051,  1.5847]])

In [25]:
y

tensor([ 1.2398,  0.1282,  1.3420,  1.6647,  1.6374,  0.8584,  0.0056,  2.0192,
        -0.3543,  0.1860,  0.9097,  1.2102,  1.3114,  1.0051,  1.5847])

In [26]:
x_cp=x.clone().view(15)
x-=1
x

tensor([[ 0.2398, -0.8718,  0.3420],
        [ 0.6647,  0.6374, -0.1416],
        [-0.9944,  1.0192, -1.3543],
        [-0.8140, -0.0903,  0.2102],
        [ 0.3114,  0.0051,  0.5847]])

In [27]:
x_cp

tensor([ 1.2398,  0.1282,  1.3420,  1.6647,  1.6374,  0.8584,  0.0056,  2.0192,
        -0.3543,  0.1860,  0.9097,  1.2102,  1.3114,  1.0051,  1.5847])

In [28]:
x=torch.randn(1)
x

tensor([0.0652])

In [29]:
torch.tensor([2.3466])

tensor([2.3466])

In [30]:
x.item()

0.06520221382379532

In [31]:
x=torch.arange(1,3).view(1,2)
x

tensor([[1, 2]])

In [32]:
y=torch.arange(1,4).view(3,1)
y

tensor([[1],
        [2],
        [3]])

In [33]:
x+y

tensor([[2, 3],
        [3, 4],
        [4, 5]])

In [34]:
x=torch.tensor([1,2])
y=torch.tensor([3,4])
id_before=id(y)

In [45]:
x=torch.ones(2,2,requires_grad=True)
x.grad_fn

In [46]:
y=x+2
y.grad_fn

In [47]:
z=y*y*3
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [48]:
out=z.mean()
out

tensor(27., grad_fn=<MeanBackward1>)

In [49]:
out.grad_fn

In [50]:
out.backward()

In [51]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [53]:
out.backward()

In [54]:
x=torch.randn((3),dtype=torch.float32,requires_grad=True)
y = torch.randn((3),dtype=torch.float32,requires_grad=True)
z = torch.randn((3),dtype=torch.float32,requires_grad=True)

In [55]:
x

tensor([0.1871, 0.4253, 0.9061], requires_grad=True)

In [56]:
y

tensor([ 0.2042, -0.0777,  0.4503], requires_grad=True)

In [57]:
z

tensor([1.1493, 0.1347, 2.2518], requires_grad=True)

In [58]:
t=x+y

In [59]:
loss=t.dot(z)

In [60]:
loss.backward()

In [61]:
print(z,x.grad,y.grad)

tensor([1.1493, 0.1347, 2.2518], requires_grad=True) tensor([1.1493, 0.1347, 2.2518]) tensor([1.1493, 0.1347, 2.2518])


In [62]:
x+y

tensor([0.3913, 0.3475, 1.3564], grad_fn=<AddBackward0>)

In [63]:
print(t,z.grad)

tensor([0.3913, 0.3475, 1.3564], grad_fn=<AddBackward0>) tensor([0.3913, 0.3475, 1.3564])


In [64]:
t.grad

In [65]:
x

tensor([0.1871, 0.4253, 0.9061], requires_grad=True)

In [124]:
x=torch.ones(2,2,requires_grad=True)
y=x+2
z=y*y*3

In [125]:
z

tensor([[27., 27.],
        [27., 27.]], grad_fn=<MulBackward0>)

In [126]:
out=z.mean()

In [127]:
out.backward()

In [128]:
x.grad

tensor([[4.5000, 4.5000],
        [4.5000, 4.5000]])

In [129]:
out2=x.sum()

In [130]:
out2

tensor(4., grad_fn=<SumBackward0>)

In [131]:
out2.backward()

In [132]:
x.grad

tensor([[5.5000, 5.5000],
        [5.5000, 5.5000]])

In [133]:
out3=x.sum()
# --x.grad.data.zero_()
out3.backward()

In [134]:
x.grad

tensor([[6.5000, 6.5000],
        [6.5000, 6.5000]])

In [141]:
x=torch.tensor([1.0,2.0,3.0,4.0],requires_grad=True)
y=2*x
z=y.view(2,2)
print(z)

tensor([[2., 4.],
        [6., 8.]], grad_fn=<ViewBackward>)


In [142]:
v=torch.tensor([[1.0,0.2],[0.03,0.004]],dtype=torch.float)
z.backward(v)
print(x.grad)

tensor([2.0000, 0.4000, 0.0600, 0.0080])


In [143]:
z*v

tensor([[2.0000, 0.8000],
        [0.1800, 0.0320]], grad_fn=<MulBackward0>)

In [145]:
x=torch.tensor(1.0,requires_grad=True)
y1=x**2
with torch.no_grad():
    y2=x**3
y3=y1+y2
print(x.requires_grad)
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

True
tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [146]:
y1.grad_fn

In [148]:
x=torch.ones(1,requires_grad=True)
x

tensor([1.], requires_grad=True)

In [150]:
x.requires_grad

True

In [ ]:
x.data()

In [169]:
a=torch.tensor([1,2,3.],requires_grad=True)
out=a.sigmoid()
c=out.data
c

tensor([0.7311, 0.8808, 0.9526])

In [170]:
c.zero_()

tensor([0., 0., 0.])

In [171]:
c

tensor([0., 0., 0.])

In [172]:
out.requires_grad

True

In [173]:
out

tensor([0., 0., 0.], grad_fn=<SigmoidBackward>)

In [174]:
out.sum().backward()

In [175]:
a.grad

tensor([0., 0., 0.])

In [176]:
a=torch.tensor([1,2,3.],requires_grad=True)
out=a.sigmoid()
c=out.detach()
c

tensor([0.7311, 0.8808, 0.9526])

In [177]:
c.zero_()

tensor([0., 0., 0.])

In [178]:
c

tensor([0., 0., 0.])

In [179]:
c.requires_grad

False

In [180]:
out.requires_grad

True

In [181]:
out

tensor([0., 0., 0.], grad_fn=<SigmoidBackward>)

In [183]:
out.sum().backward()

RuntimeError: one of the variables needed for gradient computation has been modified by an inplace operation

In [184]:
x=torch.torch.tensor(1.0,requires_grad=True)
y1=x**2
with torch.no_grad():
    y2=x**3
y3=y1+y2
    

In [188]:
print(y1,y1.requires_grad)
print(y2,y2.requires_grad)
print(y3,y3.requires_grad)

tensor(1., grad_fn=<PowBackward0>) True
tensor(1.) False
tensor(2., grad_fn=<AddBackward0>) True


In [190]:
y3.backward()
x.grad

tensor(2.)

In [191]:
x=torch.ones(1,requires_grad=True)
print(x.data)

tensor([1.])


In [192]:
x

tensor([1.], requires_grad=True)

In [193]:
y=2*x
x.data+=100
x

tensor([101.], requires_grad=True)

In [194]:
y

tensor([2.], grad_fn=<MulBackward0>)

In [195]:
y.backward()

In [196]:
x.grad

tensor([2.])

In [197]:
x

tensor([101.], requires_grad=True)