In [1]:
import numpy as np
import torch 
import pandas as pd
import torchvision
from torch import optim,nn
from scipy import stats
from scipy.stats  import norm,skew
import seaborn as sns
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [2]:
train_data=pd.read_csv(r'F:\study\ml\HonyiLee2020\hw1\data\train.csv',encoding='big5')
test_data=pd.read_csv(r'F:\study\ml\HonyiLee2020\hw1\data\test.csv',encoding='big5',header=None)

In [3]:
train_data1=train_data.replace('NR',0)
train_data1=train_data1.iloc[:,3:]

In [4]:
year_data={}
for m in range(12):
    month_data=np.empty((18,20*24))
    for d in range(20):
        month_data[:,24*d:24*(d+1)]=train_data1.iloc[18*(m*20+d):18*(m*20+d+1),:]
    year_data[m]=month_data

In [5]:
train_data1.head()

0     1     2     3     4     5     6     7     8     9  ...     14  \
0    14    14    14    13    12    12    12    12    15    17  ...     22   
1   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  ...    1.8   
2  0.51  0.41  0.39  0.37  0.35   0.3  0.37  0.47  0.78  0.74  ...   0.37   
3   0.2  0.15  0.13  0.12  0.11  0.06   0.1  0.13  0.26  0.23  ...    0.1   
4   0.9   0.6   0.5   1.7   1.8   1.5   1.9   2.2   6.6   7.9  ...    2.5   

     15    16    17    18    19    20    21    22    23  
0    22    21    19    17    16    15    15    15    15  
1   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8   1.8  
2  0.37  0.47  0.69  0.56  0.45  0.38  0.35  0.36  0.32  
3  0.13  0.14  0.23  0.18  0.12   0.1  0.09   0.1  0.08  
4   2.2   2.5   2.3   2.1   1.9   1.5   1.6   1.8   1.5  

[5 rows x 24 columns]

In [6]:
x=np.empty((12*470,9*18))
y=np.empty((12*470,1))

In [7]:
for m in range(12):
    for g in range(471):
        x[m*471+g:m*471+g+1,:]=year_data[m][:,g:g+9].reshape(1,-1)
        y[m*471+g:m*471+g+1,:]=year_data[m][9,g+9]

In [8]:
sns.distplot(y,fit=norm)
plt.show()

In [9]:
t1=pd.DataFrame(year_data[0].transpose())
t1_corr=t1.corr()[9]
t1_corr.sort_values(ascending=False)[:4]


9     1.000000
8     0.896479
12    0.533350
7     0.485685
Name: 9, dtype: float64

In [10]:
for i in range(12):
    t1=pd.DataFrame(year_data[i].transpose())
    t1_corr=t1.corr()[9]
    print(i+1,'month ')
    print(t1_corr.sort_values(ascending=False)[:7])
    print('---------------------')
    

1 month 
9     1.000000
8     0.896479
12    0.533350
7     0.485685
2     0.346491
1     0.329245
13    0.296360
Name: 9, dtype: float64
---------------------
2 month 
9     1.000000
8     0.807604
12    0.469667
5     0.468307
0     0.438273
6     0.416428
2     0.387234
Name: 9, dtype: float64
---------------------
3 month 
9     1.000000
8     0.928373
12    0.677955
5     0.653838
13    0.629512
3     0.622006
6     0.591571
Name: 9, dtype: float64
---------------------
4 month 
9     1.000000
8     0.728939
5     0.356523
12    0.335205
6     0.329000
7     0.319330
13    0.305169
Name: 9, dtype: float64
---------------------
5 month 
9     1.000000
5     0.504182
8     0.478403
6     0.436177
14    0.370249
1     0.369144
15    0.347543
Name: 9, dtype: float64
---------------------
6 month 
9     1.000000
5     0.509864
8     0.503590
12    0.476693
7     0.467704
6     0.446027
2     0.349774
Name: 9, dtype: float64
---------------------
7 month 
9     1.000000
8     0.533007
7

In [11]:
x1=np.empty((471,18*9))
y1=np.empty((471,1))

## test every month data
- test No.1 month data ,I think the num of data is enough(471),since linear reg.
- xx,yy is all year data.
- x1,y1 is No.1 month data.

In [12]:
for g in range(417):
    x1[g:g+1,:]=year_data[0][:,g:g+9].reshape(1,-1)
    y1[g:g+1,:]=year_data[0][9,g+9]

In [13]:
x1[:10]

array([[14. , 14. , 14. , ...,  2. ,  2. ,  0.5],
       [14. , 14. , 13. , ...,  2. ,  0.5,  0.3],
       [14. , 13. , 12. , ...,  0.5,  0.3,  0.8],
       ...,
       [12. , 15. , 17. , ...,  2.6,  2.1,  2.1],
       [15. , 17. , 20. , ...,  2.1,  2.1,  1.9],
       [17. , 20. , 22. , ...,  2.1,  1.9,  1. ]])

In [14]:
x1=pd.DataFrame(x1)
x1=x1.apply(lambda x: (x-x.mean())/x.std())
x1=x1.values

In [15]:
x1.shape

(471, 162)

In [16]:
y1

array([[3.00000000e+001],
       [4.10000000e+001],
       [4.40000000e+001],
       [3.30000000e+001],
       [3.70000000e+001],
       [3.60000000e+001],
       [4.50000000e+001],
       [4.20000000e+001],
       [4.90000000e+001],
       [4.50000000e+001],
       [4.40000000e+001],
       [4.10000000e+001],
       [3.00000000e+001],
       [2.40000000e+001],
       [1.30000000e+001],
       [2.10000000e+001],
       [2.30000000e+001],
       [3.00000000e+001],
       [3.00000000e+001],
       [2.20000000e+001],
       [1.80000000e+001],
       [1.30000000e+001],
       [1.30000000e+001],
       [1.10000000e+001],
       [2.20000000e+001],
       [2.50000000e+001],
       [3.40000000e+001],
       [3.80000000e+001],
       [5.00000000e+001],
       [5.30000000e+001],
       [4.30000000e+001],
       [4.30000000e+001],
       [4.50000000e+001],
       [4.60000000e+001],
       [3.20000000e+001],
       [1.60000000e+001],
       [1.90000000e+001],
       [2.20000000e+001],
       [2.60

In [17]:
x1

array([[-0.02085745, -0.02121657, -0.02193344, ...,  0.94759627,
         0.94600982, -0.85844934],
       [-0.02085745, -0.02121657, -0.19128839, ...,  0.94759627,
        -0.85840686, -1.09890704],
       [-0.02085745, -0.19058956, -0.36064333, ..., -0.85838367,
        -1.09899575, -0.49776277],
       ...,
       [-2.39213361, -2.39243834, -2.39290266, ..., -1.46037698,
        -1.45987909, -1.45959361],
       [-2.39213361, -2.39243834, -2.39290266, ..., -1.46037698,
        -1.45987909, -1.45959361],
       [-2.39213361, -2.39243834, -2.39290266, ..., -1.46037698,
        -1.45987909, -1.45959361]])

In [18]:
def train_pytorch(num_epochs,lr,train_features,train_labels,test_features,test_labels,batch_size):
    net=get_net()
    loss=nn.MSELoss()
    optimizer=optim.SGD(net.parameters(),lr=lr,momentum=0.5)
    dataset=torch.utils.data.TensorDataset(train_features,train_labels)
    data_iter=torch.utils.data.DataLoader(dataset,batch_size,shuffle=True)
    for e in range(num_epochs):
        net.train()
        for x,y in data_iter:
            l=loss(net(x),y)
            optimizer.zero_grad()
            l.backward()
            optimizer.step()
        if (e+1) %100==0:
            net.eval()
            with torch.no_grad():
                print('Saving model , epoch ',(e+1),'train loss : ',loss(net(train_features),train_labels).detach().item(),
                     'test loss : ', loss(net(test_features),test_labels).detach().item())
                torch.save(net.state_dict(),r'F:\study\ml\HonyiLee2020\hw1\models.pth' )
                
        

In [164]:
idx=list(range(len(x1)))
np.random.shuffle(idx)
tr_set=idx[:int(len(idx) * 0.9 )]
tt_set=idx[int(len(idx) * 0.9 ):]

In [170]:
x1_train = torch.Tensor(x1[tr_set])
y1_train = torch.Tensor(y1[tr_set])
x1_test = torch.Tensor(x1[tt_set])
y1_test = torch.Tensor(y1[tt_set])


def get_net():
    return nn.Sequential(nn.Linear(x1.shape[1], 256), nn.ReLU(),
                         nn.Dropout(0.2), nn.Linear(256, 128), nn.ReLU(),
                         nn.Dropout(0.2), nn.Linear(128, 64), nn.ReLU(),
                         nn.Dropout(0.2), nn.Linear(64, 1))


train_pytorch(1000, 0.001, x1_train, y1_train, x1_test, y1_test, 32)

Saving model , epoch  100 train loss :  52.792198181152344 test loss :  123.38261413574219
Saving model , epoch  200 train loss :  43.37519073486328 test loss :  102.82435607910156
Saving model , epoch  300 train loss :  2.179562568664551 test loss :  46.283634185791016
Saving model , epoch  400 train loss :  3.887632131576538 test loss :  45.74293518066406
Saving model , epoch  500 train loss :  7.459926128387451 test loss :  54.11961364746094
Saving model , epoch  600 train loss :  1.6443711519241333 test loss :  46.10467529296875
Saving model , epoch  700 train loss :  39.3121337890625 test loss :  119.57013702392578
Saving model , epoch  800 train loss :  5.680407524108887 test loss :  50.91826629638672
Saving model , epoch  900 train loss :  1.8665581941604614 test loss :  43.989925384521484
Saving model , epoch  1000 train loss :  1.2426741123199463 test loss :  43.25447082519531


In [171]:
idx=list(range(len(x)))
np.random.shuffle(idx)
tr_set=idx[:int(len(idx) * 0.9 )]
tt_set=idx[int(len(idx) * 0.9 ):]

In [172]:
x=pd.DataFrame(x)
x=x.apply(lambda x: (x-x.mean())/x.std())
x=x.values

In [186]:
xx_train = torch.Tensor(x[tr_set])
yy_train = torch.Tensor(y[tr_set])
xx_test = torch.Tensor(x[tt_set])
yy_test = torch.Tensor(y[tt_set])
# def get_net():
#     return nn.Sequential(nn.Linear(x1.shape[1], 256), nn.ReLU(),
#                          nn.Dropout(0.2), nn.Linear(256, 128), nn.ReLU(),
#                          nn.Dropout(0.2), nn.Linear(128, 64), nn.ReLU(),
#                          nn.Dropout(0.2), nn.Linear(64, 1))
def get_net():
    return nn.Sequential(nn.Linear(x1.shape[1], 256), nn.ReLU(),
                         nn.Dropout(0.7), nn.Linear(256, 128), nn.ReLU(),
                         nn.Dropout(0.5), nn.Linear(128, 64), nn.ReLU(),
                         nn.Dropout(0.4), nn.Linear(64, 1))
train_pytorch(5000,0.000001,xx_train,yy_train,xx_test,yy_test,128)

Saving model , epoch  100 train loss :  691.3370971679688 test loss :  681.1600952148438
Saving model , epoch  200 train loss :  190.26803588867188 test loss :  187.50289916992188
Saving model , epoch  300 train loss :  121.43080139160156 test loss :  116.71834564208984
Saving model , epoch  400 train loss :  103.11961364746094 test loss :  98.6387710571289
Saving model , epoch  500 train loss :  91.92455291748047 test loss :  88.15471649169922
Saving model , epoch  600 train loss :  84.02082061767578 test loss :  81.09880828857422
Saving model , epoch  700 train loss :  78.11709594726562 test loss :  75.97876739501953
Saving model , epoch  800 train loss :  73.21366119384766 test loss :  71.70868682861328
Saving model , epoch  900 train loss :  69.44775390625 test loss :  68.49600982666016
Saving model , epoch  1000 train loss :  66.35360717773438 test loss :  65.93922424316406
Saving model , epoch  1100 train loss :  63.33314514160156 test loss :  63.438419342041016
Saving model , ep

#### test No.1 month data Model to fit No.2-12 month data

In [ ]:
x2=np.empty((471,18*9))
y2=np.empty((471,1))
for g in range(417):
    x2[g:g+1,:]=year_data[1][:,g:g+9].reshape(1,-1)
    y2[g:g+1,:]=year_data[1][9,g]

In [ ]:
net=nn.Linear(train_features.shape[1],1)
ckpt = torch.load(r'F:\study\ml\HonyiLee2020\hw1\models.pth')  # Load your best model
net.load_state_dict(ckpt)

In [2]:
import numpy as np
np.sqrt(32)

5.656854249492381