In [1]:
import torch

In [9]:
input=torch.randn(4,3)
input

tensor([[ 0.8816, -3.0139,  0.1374],
        [ 0.6549,  1.9953, -0.7858],
        [ 1.2956,  1.3308, -0.4849],
        [ 0.0284,  0.1294,  0.3026]])

In [10]:
target=torch.tensor([0,1,1,2])

In [11]:
sfm=torch.nn.Softmax(dim=1)
sfm(input)

tensor([[0.6687, 0.0136, 0.3177],
        [0.1977, 0.7555, 0.0468],
        [0.4537, 0.4699, 0.0765],
        [0.2923, 0.3233, 0.3844]])

In [12]:
logsfm=torch.nn.LogSoftmax(dim=1)
logsfm(input)

tensor([[-0.4024, -4.2979, -1.1466],
        [-1.6208, -0.2804, -3.0616],
        [-0.7904, -0.7553, -2.5709],
        [-1.2301, -1.1291, -0.9560]])

In [13]:
torch.log(sfm(input))

tensor([[-0.4024, -4.2979, -1.1466],
        [-1.6208, -0.2804, -3.0616],
        [-0.7904, -0.7553, -2.5709],
        [-1.2301, -1.1291, -0.9560]])

In [15]:
target

tensor([0, 1, 1, 2])

In [14]:
ec=torch.nn.CrossEntropyLoss()
ec(input,target)

tensor(0.5985)

In [16]:
loss=torch.nn.NLLLoss()
loss(logsfm(input),target)

tensor(0.5985)

In [17]:
(0.4024+0.2804+0.7553+0.9560)/4

0.598525