In [35]:
import numpy as np
import keras

In [36]:
from keras.datasets import mnist

In [37]:
(train_images,train_labels),(test_images,test_labels)=mnist.load_data()

In [38]:
train_images.shape

(60000, 28, 28)

In [39]:
train_images.ndim

3

In [40]:
train_images.dtype

dtype('uint8')

In [41]:
digit=train_images[4]

In [42]:
import matplotlib.pylab as plt

In [43]:
plt.imshow(digit,cmap=plt.cm.binary)
# plt.show()

In [44]:
my_slice=train_images[0:100]
my_slice.shape

(100, 28, 28)

In [45]:
my_slice.shape

(100, 28, 28)

In [46]:
my_slice[0][0][2]

0

In [47]:
my_slice[0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [48]:
batch=train_images[:128]

In [49]:
test_labels[0]

7

In [50]:
len(train_images[0])

28

In [51]:
test_images[0][0]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [52]:
test_images[0][1]

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=uint8)

In [53]:
test_images[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  

In [54]:
np.array([[0.5,0.2,0.3],
         [0.3,0.5,0.2],
         [0.2,0.3,0.5]])

array([[0.5, 0.2, 0.3],
       [0.3, 0.5, 0.2],
       [0.2, 0.3, 0.5]])

In [64]:
a=0.028
b=0.054
c=0.042

In [66]:
(a*0.5,b*0.3,c*0.2)

(0.014, 0.0162, 0.008400000000000001)

In [68]:
0.0162*0.5  #2

0.0081

In [69]:
(a*0.2,b*0.5,c*0.3)

(0.005600000000000001, 0.027, 0.0126)

In [70]:
0.027*0.4

0.0108

In [71]:
(a*0.3,b*0.2,c*0.5)

(0.0084, 0.0108, 0.021)

In [72]:
0.021*0.7

0.0147