In [1]:
import numpy as np
import matplotlib
from mpl_toolkits.mplot3d import Axes3D
from matplotlib import cm

import time
from scipy.optimize import leastsq
import scipy.optimize as opt
import scipy
import matplotlib.pyplot as plt
from scipy.stats import norm, poisson
from scipy.interpolate import BarycentricInterpolator
from scipy.interpolate import CubicSpline
import math


In [2]:
plt.style.use(style='ggplot')  #样式
plt.rcParams['figure.figsize']=(8,4)  #横竖大小

In [3]:
a = np.arange(0, 6, 1).reshape(-1, 1) + np.arange(10, 60, 10)
a

array([[10, 20, 30, 40, 50],
       [11, 21, 31, 41, 51],
       [12, 22, 32, 42, 52],
       [13, 23, 33, 43, 53],
       [14, 24, 34, 44, 54],
       [15, 25, 35, 45, 55]])

In [4]:
a.shape

(6, 5)

In [6]:
b = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
b

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [7]:
b.shape

(3, 4)

In [9]:
b.shape=2,-1
b

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [10]:
c=b.reshape((4,-1))
c

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [11]:
b[0][1]=20

In [12]:
b

array([[ 1, 20,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [13]:
c

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [14]:
    d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.float)
    f = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.complex)

In [15]:
d

array([[  1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.],
       [  9.,  10.,  11.,  12.]])

In [16]:
c

array([[ 1, 20,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [17]:
a.dtype

dtype('int32')

In [18]:
c.dtype

dtype('int32')

In [19]:
d.dtype

dtype('float64')

In [20]:
f=d.astype(np.int)
f

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [21]:
f.dtype

dtype('int32')

In [23]:
b=np.linspace(1,10,10)
b

array([  1.,   2.,   3.,   4.,   5.,   6.,   7.,   8.,   9.,  10.])

In [24]:
c=np.linspace(1,10,10,endpoint=False)
c

array([ 1. ,  1.9,  2.8,  3.7,  4.6,  5.5,  6.4,  7.3,  8.2,  9.1])

In [25]:
d=np.logspace(1,2,10)
d

array([  10.        ,   12.91549665,   16.68100537,   21.5443469 ,
         27.82559402,   35.93813664,   46.41588834,   59.94842503,
         77.42636827,  100.        ])

In [27]:
d = np.logspace(1, 2, endpoint=True, base=2)
d

array([ 2.        ,  2.02849277,  2.05739147,  2.08670186,  2.11642982,
        2.1465813 ,  2.17716233,  2.20817903,  2.2396376 ,  2.27154434,
        2.30390564,  2.33672798,  2.37001791,  2.4037821 ,  2.43802731,
        2.47276039,  2.50798829,  2.54371806,  2.57995685,  2.61671192,
        2.65399061,  2.69180039,  2.73014882,  2.76904357,  2.80849244,
        2.84850331,  2.88908419,  2.9302432 ,  2.97198858,  3.01432868,
        3.05727197,  3.10082705,  3.14500263,  3.18980756,  3.23525079,
        3.28134142,  3.32808868,  3.37550192,  3.42359063,  3.47236443,
        3.52183307,  3.57200647,  3.62289466,  3.67450782,  3.72685628,
        3.77995051,  3.83380115,  3.88841897,  3.94381489,  4.        ])

In [28]:
s='abcd'
g=np.fromstring(s,dtype=np.int8)
g

array([ 97,  98,  99, 100], dtype=int8)

In [29]:
a=np.arange(10)
a[3]

3

In [30]:
a[:5]

array([0, 1, 2, 3, 4])

In [31]:
a[1:9:2]

array([1, 3, 5, 7])

In [32]:
a=np.logspace(0,9,10,base=2)
a

array([   1.,    2.,    4.,    8.,   16.,   32.,   64.,  128.,  256.,  512.])

In [33]:
a=np.random.rand(10)
a

array([ 0.68592762,  0.80735179,  0.40132841,  0.57892286,  0.68957529,
        0.07528544,  0.80607398,  0.34086499,  0.3186143 ,  0.03438068])

In [34]:
b=a[a>0.5]
b

array([ 0.68592762,  0.80735179,  0.57892286,  0.68957529,  0.80607398])

In [36]:
a=np.arange(10,60,10).reshape(-1,1)+np.arange(6)
a

array([[10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [40]:
for j in np.logspace(0,7,10):
    j=int(j)
    x=np.linspace(0,10,j)
    start=time.clock()
    y=np.sin(x)
    t1=time.clock()-start
    
    x=x.tolist()
    start=time.clock()
    for i ,t in enumerate(x):
        x[i]=math.sin(t)
    t2=time.clock()-start
    print(j," : ",t1,t2,t2/t1)

1  :  0.0044282260690522435 8.397394566372895e-06 0.0018963337542904982
5  :  3.421160755578967e-06 3.421160755578967e-06 1.0
35  :  2.7991315221242985e-06 1.1196526102708049e-05 4.00000000507688
215  :  3.421160755578967e-06 5.1628425850935855e-05 15.090909062587654
1291  :  3.358957827970244e-05 0.00032096708127937745 9.555555553769246
7742  :  7.060031730077299e-05 0.0019432193060424652 27.52422907341791
46415  :  0.0004102282753848385 0.011742978767344425 28.625473844600887
278255  :  0.0026178100030449514 0.06908567612866534 26.390637994471383
1668100  :  0.016297165754934895 0.43126716995051595 26.462709923651925
10000000  :  0.09913062085047386 2.5243725046908736 25.46511343350279


In [52]:
mu=0
sigma=1
x=np.linspace(mu-3*sigma,mu+3*sigma,50)
y=np.exp(-((x-mu)**2/(2*sigma**2))) / np.sqrt(2*np.pi)*sigma
print("x.shape:",x.shape)
print("y.shape:",y.shape)
# plt.plot(x,y,'ro-',linewidth=2)
plt.plot(x,y,'r-',x,y,'go',linewidth=2)
# plt.show()

x.shape: (50,)
y.shape: (50,)


In [67]:
x=np.array(np.linspace(-2,3,1001,dtype=np.float))
y_logit=np.log(1 + np.exp(-x)) / math.log(2)
y_boost=np.exp(-x)
y_01=x<0
y_hinge=1.0-x
y_hinge[y_hinge<0]=0

plt.plot(x,y_logit,'ro',label='Logistic Loss',linewidth=2)
plt.plot(x, y_01, 'g-', label='0/1 Loss', linewidth=2)
plt.plot(x, y_hinge, 'b-', label='Hinge Loss', linewidth=2)
plt.plot(x, y_boost, 'm--', label='Adaboost Loss', linewidth=2)
# plt.show()

In [111]:
def residual(t, x, y):
    return y - (t[0] * x ** 2 + t[1] * x + t[2])

In [69]:
def residual2(t,x,y):
    print(t[0],t[1])
    return y-t[0] * np.sin(t[1]*x)

In [70]:
def f(x):
    y=np.ones_like(x)
    i=x>0
    y[i]=np.power(x[i],x[i])
    i=x<0
    y[i]=np.power(-x[i],-x[i])
    return y

In [74]:
x=np.linspace(-1.3,1.3,101)
y=f(x)
plt.plot(x,y,'g-',label='x^x',linewidth=2)
# plt.show()

In [81]:
x=np.arange(1,0,-0.001)
y=(-3*x*np.log(x)+np.exp(-(40*(x-1/np.e))**4)/25)/2
+np.exp(-(40*(x-1/np.e))**4)/25
plt.plot(x,y,'r-',linewidth=2)
# plt.show()

In [85]:
t=np.linspace(0,7,100)
x=16*np.sin(t)**3
y=13*np.cos(t)-5*np.cos(2*t)-2*np.cos(3*t)-np.cos(4*t)
plt.plot(x,y,'r-',linewidth=2)
# plt.show()

In [89]:
x=np.random.rand(10000)
t=np.arange(len(x))
plt.hist(x,30,color='m',alpha=0.5)
# plt.show()

(array([ 372.,  315.,  318.,  344.,  350.,  325.,  326.,  347.,  362.,
         344.,  336.,  329.,  360.,  338.,  296.,  306.,  312.,  335.,
         313.,  322.,  354.,  350.,  326.,  303.,  328.,  363.,  311.,
         338.,  324.,  353.]),
 array([  3.71413479e-05,   3.33679677e-02,   6.66987941e-02,
          1.00029620e-01,   1.33360447e-01,   1.66691273e-01,
          2.00022099e-01,   2.33352926e-01,   2.66683752e-01,
          3.00014579e-01,   3.33345405e-01,   3.66676231e-01,
          4.00007058e-01,   4.33337884e-01,   4.66668710e-01,
          4.99999537e-01,   5.33330363e-01,   5.66661189e-01,
          5.99992016e-01,   6.33322842e-01,   6.66653668e-01,
          6.99984495e-01,   7.33315321e-01,   7.66646148e-01,
          7.99976974e-01,   8.33307800e-01,   8.66638627e-01,
          8.99969453e-01,   9.33300279e-01,   9.66631106e-01,
          9.99961932e-01]),
 <a list of 30 Patch objects>)

In [95]:
t=10000
a=np.zeros(1000)
for i in range(t):
    a+=np.random.uniform(-5,5,1000)
a/=t
plt.hist(a,bins=30,color='g',alpha=0.5,normed=True)
# plt.show()

(array([  1.18706184,   1.3566421 ,   2.03496315,   2.54370394,
          2.54370394,   5.25698814,   6.27446972,   6.95279077,
          7.2919513 ,   8.47901313,  10.85313681,  14.75348285,
         14.58390259,  13.05768023,  14.41432233,  10.0052355 ,
         10.68355655,   9.15733418,   8.30943287,   7.12237103,
          4.40908683,   2.54370394,   2.03496315,   1.69580263,
          1.01748158,   0.50874079,   0.        ,   0.16958026,
          0.16958026,   0.16958026]),
 array([-0.07738302, -0.07148611, -0.06558919, -0.05969228, -0.05379537,
        -0.04789845, -0.04200154, -0.03610463, -0.03020772, -0.0243108 ,
        -0.01841389, -0.01251698, -0.00662007, -0.00072315,  0.00517376,
         0.01107067,  0.01696759,  0.0228645 ,  0.02876141,  0.03465832,
         0.04055524,  0.04645215,  0.05234906,  0.05824597,  0.06414289,
         0.0700398 ,  0.07593671,  0.08183362,  0.08773054,  0.09362745,
         0.09952436]),
 <a list of 30 Patch objects>)

In [110]:
x = np.random.poisson(lam=5, size=10000)
print(x)
pillar = 15
a = plt.hist(x,
             bins=pillar,
             normed=True,
             range=[0, pillar],
             color='g',
             alpha=0.5)
# plt.show()

[4 2 6 ..., 6 6 8]


In [116]:
residual([1,2,3],4,5)

-22

In [127]:
x = np.linspace(-2, 2, 50)
A, B, C = 2, 3, -1
y = (A * x**2 + B * x + C) + np.random.rand(len(x)) * 0.75
t = leastsq(residual, [0, 0, 0], args=(x, y))
theta = t[0]
print('真实值：', A, B, C)
print('预测值：', theta)
y_hat = theta[0] * x**2 + theta[1] * x + theta[2]
plt.plot(x, y, 'r-', linewidth=2, label=u'Actual')
plt.plot(x, y_hat, 'g-', linewidth=2, label=u'Predict')
# plt.show()

真实值： 2 3 -1
预测值： [ 1.97619436  3.00713345 -0.56067426]


In [130]:
x = np.linspace(0, 5, 100)
A = 5
w = 1.5
y = A * np.sin(w * x) + np.random.rand(len(x)) - 0.5

t = leastsq(residual2, [3, 1], args=(x, y))
theta = t[0]
y_hat=theta[0]*np.sin(theta[1]*x)
print('真实值：', A, w)
print('预测值：', theta)
plt.plot(x, y, 'r-', linewidth=2, label='Actual')
plt.plot(x, y_hat, 'g-', linewidth=2, label='Predict')
# plt.show()

3 1
3.0 1.0
3.0 1.0
3.0000000447 1.0
3.0 1.0000000149
0.658798442869 1.42149534746
0.658798452686 1.42149534746
0.658798442869 1.42149536864
4.89327994695 1.98785155846
3.58746903325 1.51253086564
3.58746908671 1.51253086564
3.58746903325 1.51253088818
4.99465914206 1.49200961837
4.99465921649 1.49200961837
4.99465914206 1.49200964061
4.99815170433 1.49789670615
4.99815177881 1.49789670615
4.99815170433 1.49789672847
4.99883467538 1.49788988447
4.99883474987 1.49788988447
4.99883467538 1.49788990679
4.99883465625 1.4978898993
真实值： 5 1.5
预测值： [ 4.99883466  1.4978899 ]


In [132]:
a = opt.fmin(f, 1)
b = opt.fmin_cg(f, 1)
c = opt.fmin_bfgs(f, 1)
print(a, 1 / a, math.e)
print(b)
print(c)

Optimization terminated successfully.
         Current function value: 0.692201
         Iterations: 16
         Function evaluations: 32
Optimization terminated successfully.
         Current function value: 0.692201
         Iterations: 4
         Function evaluations: 30
         Gradient evaluations: 10
Optimization terminated successfully.
         Current function value: 0.692201
         Iterations: 5
         Function evaluations: 24
         Gradient evaluations: 8
[ 0.36787109] [ 2.71834351] 2.718281828459045
[ 0.36787948]
[ 0.36787942]


5.2 calc

In [161]:
def calc_e_small(x):
    n=10
    f=np.arange(1,n+1).cumprod()
    b=np.array([x]*n).cumprod()
    return np.sum(b/f)+1

In [158]:
np.arange(1,5).cumprod()

array([ 1,  2,  6, 24], dtype=int32)

In [159]:
def calc_e(x):
    reverse = False
    if x < 0:
        x = -x
        reverse = True
    ln2 = 0.69314718055994530941723212145818
    c=x/ln2
    a=int(c+0.5)
    b=x-a*ln2
    y=(2**a)*calc_e_small(b)
    if reverse:
        return 1/y
    return y

In [164]:
t1=np.linspace(-2,0,10,endpoint=False)
t2=np.linspace(0,2,20)
t=np.concatenate((t1,t2))
# print(t)
y=np.empty_like(t)
for i ,x in enumerate(t):
    print('x:',x)
    y[i]=calc_e(x)
    print ('e^', x, ' = ', y[i], '(近似值)\t', math.exp(x), '(真实值)')
plt.plot(t, y, 'r-', t, y, 'go', linewidth=2)
plt.title(u'Taylor展式的应用', fontsize=18)
plt.xlabel('X', fontsize=15)
plt.ylabel('exp(X)', fontsize=15)
# plt.show()

x: -2.0
e^ -2.0  =  0.135335283237 (近似值)	 0.1353352832366127 (真实值)
x: -1.8
e^ -1.8  =  0.165298888222 (近似值)	 0.16529888822158653 (真实值)
x: -1.6
e^ -1.6  =  0.201896517995 (近似值)	 0.20189651799465538 (真实值)
x: -1.4
e^ -1.4  =  0.246596963942 (近似值)	 0.2465969639416065 (真实值)
x: -1.2
e^ -1.2  =  0.301194211912 (近似值)	 0.30119421191220214 (真实值)
x: -1.0
e^ -1.0  =  0.367879441171 (近似值)	 0.36787944117144233 (真实值)
x: -0.8
e^ -0.8  =  0.449328964117 (近似值)	 0.4493289641172217 (真实值)
x: -0.6
e^ -0.6  =  0.548811636094 (近似值)	 0.5488116360940265 (真实值)
x: -0.4
e^ -0.4  =  0.670320046036 (近似值)	 0.6703200460356393 (真实值)
x: -0.2
e^ -0.2  =  0.818730753078 (近似值)	 0.8187307530779819 (真实值)
x: 0.0
e^ 0.0  =  1.0 (近似值)	 1.0 (真实值)
x: 0.105263157895
e^ 0.105263157895  =  1.11100294108 (近似值)	 1.1110029410844708 (真实值)
x: 0.210526315789
e^ 0.210526315789  =  1.2343275351 (近似值)	 1.2343275350983443 (真实值)
x: 0.315789473684
e^ 0.315789473684  =  1.37134152176 (近似值)	 1.3713415217558058 (真实值)
x: 0.421052631579
e^ 0.4210526

Text(0,0.5,'exp(X)')

In [170]:
class People:
    def __init__(self,n,a,s):
        self.name=n
        self.age=a
        self.__score=s
        
    def print_people(self):
        str=u'%s的年龄：%d，成绩为：%.2f' % (self.name, self.age, self.__score)
        print(str)
#         __print_people=print_people
        

In [171]:
class Student(People):
    def __init__(self,n,a,w):
        People.__init__(self,n,a,w)
        self.name='Student '+self.name
        
    def print_people(self):
        str=u'%s的年龄：%d' % (self.name, self.age)
        print(str)

In [172]:
def func(p):
    p.age=11

In [179]:
p=People("Tom",10,3.14159)
func(p)
p.print_people()
j=Student('Jerry',12,2.71828)
p.print_people()
j.print_people()
People.print_people(p)
People.print_people(j)

Tom的年龄：11，成绩为：3.14
Tom的年龄：11，成绩为：3.14
Student Jerry的年龄：12
Tom的年龄：11，成绩为：3.14
Student Jerry的年龄：12，成绩为：2.72


5.4 start

In [209]:
from scipy import stats

In [223]:
def cala_statistics(x):
    n = x.shape[0]
    m = 0
    m2 = 0
    m3 = 0
    m4 = 0
    for t in x:
        m += t
        m2 += t * t
        m3 += t**3
        m4 += t**4
    m/=n
    m2/=n
    m3/=n
    m4/=n
        
    mu = m
    sigma = np.sqrt(m2 - mu*mu)
    skew = (m3 - 3*mu*m2 + 2*mu**3) / sigma**3
#     skew = (m3 - 3*mu*m2 -mu**3) / sigma**3
    kurtosis = (m4 - 4*mu*m3 + 6*mu*mu*m2 - 4*mu**3*mu + mu**4) / sigma**4 - 3
    print ('手动计算均值、标准差、偏度、峰度：', mu, sigma, skew, kurtosis)
    mu=np.mean(x,axis=0)
    sigma=np.std(x,axis=0)
    skew=stats.skew(x)
    return mu,sigma,skew,kurtosis

In [224]:
d = np.random.randn(100)
print(d)
mu, sigma, skew, kurtosis = cala_statistics(d)
print('函数库计算均值、标准差、偏度、峰度：', mu, sigma, skew, kurtosis)

[-0.40001606 -1.19812964 -0.96974096 -0.81312675  0.62414477 -1.10205711
  1.32367919 -1.20124736 -0.69585482  1.42443906 -0.99426832 -0.08121011
 -1.53749882  0.53596799  1.26258589  1.18998094  0.74135424  0.16675088
  1.27754665 -0.80606469  0.39020356  0.80443432 -0.17089388  0.99058338
  0.75459265 -0.94388843 -0.92510403  0.46887002 -0.68073121  0.35622624
 -1.01702678 -1.19605222  0.91102961 -0.57975855 -0.34923891 -0.7200776
 -0.18055877 -0.21495382 -0.62127428  0.7778559   0.06904809  0.51660277
 -0.62552557  0.34979353 -1.88654284 -0.78280538 -1.13026678 -0.49717528
  0.83336544  1.33597296 -0.00696819  0.91573186 -0.19599065  0.3540589
  0.41555011 -0.29498906 -0.2731402  -0.32861092  2.96317021  1.92536544
  0.01717145 -1.80605484 -1.11707821  0.51609566 -0.91544221  3.18736847
 -0.64348285 -0.26165373  0.0338308   0.44049262  1.41365674 -1.27617026
  1.28764234 -0.31835414 -0.25486424  0.58279608  0.1527374  -0.29943823
 -1.44002711  1.35703295 -0.2453168  -1.6320577  -0.0