In [2]:
import torch
from torch.nn import init
from torch import nn

In [4]:
net =nn.Sequential(nn.Linear(4,3),nn.ReLU(),nn.Linear(3,1))
print(net)
x=torch.rand(2,4)
y=net(x).sum()
y

Sequential(
  (0): Linear(in_features=4, out_features=3, bias=True)
  (1): ReLU()
  (2): Linear(in_features=3, out_features=1, bias=True)
)


tensor(0.8400, grad_fn=<SumBackward0>)

In [8]:
print(type(net.named_parameters()))
for name,param in net.named_parameters():
    print(name,param)

<class 'generator'>
0.weight Parameter containing:
tensor([[ 0.1407,  0.0700,  0.2161, -0.3438],
        [ 0.2813,  0.0319,  0.1958, -0.3358],
        [-0.0449, -0.2517,  0.3188, -0.0741]], requires_grad=True)
0.bias Parameter containing:
tensor([0.1429, 0.0287, 0.1462], requires_grad=True)
2.weight Parameter containing:
tensor([[-0.4143,  0.5150, -0.2508]], requires_grad=True)
2.bias Parameter containing:
tensor([0.4730], requires_grad=True)


In [10]:
class MyModel(nn.Module):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)
        self.weight1=nn.Parameter(torch.rand(20,20))
        self.weight2=torch.rand(20,20)
        
    def forward(self,x):
        pass

In [11]:
n=MyModel()
for name,param in n.named_parameters():
    print(name)

weight1


In [12]:
weight_0=list(net[0].parameters())[0]
print(weight_0.data)
print(weight_0.data)
y.backward()
print(weight_0.grad)

tensor([[ 0.1407,  0.0700,  0.2161, -0.3438],
        [ 0.2813,  0.0319,  0.1958, -0.3358],
        [-0.0449, -0.2517,  0.3188, -0.0741]])
tensor([[ 0.1407,  0.0700,  0.2161, -0.3438],
        [ 0.2813,  0.0319,  0.1958, -0.3358],
        [-0.0449, -0.2517,  0.3188, -0.0741]])
tensor([[-0.2386, -0.6844, -0.4233, -0.3745],
        [ 0.2966,  0.8508,  0.5262,  0.4655],
        [-0.0333, -0.2113, -0.1850, -0.1452]])


In [13]:
for name,param in net.named_parameters():
    if 'weight' in name:
        init.normal_(param,mean=0,std=0.01)
        print(name,param.data)

0.weight tensor([[-0.0039, -0.0006,  0.0040, -0.0008],
        [ 0.0201, -0.0093, -0.0053,  0.0030],
        [-0.0035, -0.0071,  0.0202, -0.0178]])
2.weight tensor([[ 0.0086,  0.0048, -0.0084]])


In [14]:
for name,param in net.named_parameters():
    if 'bias' in name:
        init.constant_(param,val=0)
        print(name,param.data)

0.bias tensor([0., 0., 0.])
2.bias tensor([0.])


In [15]:
def normal_(tensor,mean=0,std=1):
    with torch.no_grad():
        return tensor.normal_(mean,std)

In [16]:
def init_weight_(tensor):
    with torch.no_grad():
        tensor.uniform_(-10,10)
        tensor *= (tensor.abs() >=5).float()
    
for name,param in net.named_parameters():
    if 'weight' in name:
        init_weight_(param)
        print(name,param.data)

0.weight tensor([[-8.0884, -0.0000, -9.1277, -0.0000],
        [ 0.0000,  7.6779,  0.0000,  5.5858],
        [ 5.5614,  0.0000, -0.0000, -0.0000]])
2.weight tensor([[-0.0000, 0.0000, 9.9447]])


In [17]:
for name,param in net.named_parameters():
    if 'bias' in name:
        param.data +=1
        print(name,param.data)

0.bias tensor([1., 1., 1.])
2.bias tensor([1.])
