In [1]:
import torch
import torch.nn as nn
from torch.nn import init

In [2]:
linear=nn.Linear(1,1,bias=False)
net=nn.Sequential(linear,linear)
print(net)

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=False)
  (1): Linear(in_features=1, out_features=1, bias=False)
)


In [3]:
for name,param in net.named_parameters():
    init.constant_(param,val=3)
    print(name,param.data)

0.weight tensor([[3.]])


In [9]:
print(id(net[0])==id(net[1]))
print(id(net[0].weight)==id(net[1].weight))

True
True


In [6]:
id(net[0])

254273800

In [7]:
id(net[1])

254273800

In [8]:
net[0].weight

Parameter containing:
tensor([[3.]], requires_grad=True)

In [11]:
x=torch.ones(1,1)
y=net(x).sum()
print(y)
y.backward()
print(net[0].weight.grad)

tensor(9., grad_fn=<SumBackward0>)
tensor([[6.]])


In [12]:
x

tensor([[1.]])

In [13]:
print(net)

Sequential(
  (0): Linear(in_features=1, out_features=1, bias=False)
  (1): Linear(in_features=1, out_features=1, bias=False)
)


In [14]:
for name,param in net.named_parameters():
    print(name)
    print(param)

0.weight
Parameter containing:
tensor([[3.]], requires_grad=True)
