In [1]:
import torch
import torch.nn as nn

In [43]:
def conv2d(x,k):
    h,w=k.shape
    y=torch.zeros((x.shape[0]-h+1,x.shape[1]-w+1))
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            y[i,j]=(x[i:i+h,j:j+w].float() * k.float()).sum()
    return y

In [44]:
class Conv2D(nn.Module):
    def __init__(self,kernel_size):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(kernel_size))
        self.bias=nn.Parameter(torch.randn(1))
    
    def forward(self,x):
        return conv2d(x,self.weight)+self.bias

In [45]:
x=torch.ones(6,8)
x[:,2:6]=0
x

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [59]:
k

tensor([[ 1, -1]])

In [46]:
y=conv2d(x,k)
y

tensor([[ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.],
        [ 0.,  1.,  0.,  0.,  0., -1.,  0.]])

In [56]:
conv2d1=Conv2D(kernel_size=(1,2))
step=50
lr=0.01
for i in range(step):
    y_hat=conv2d1(x)
    l=((y_hat-y)**2).sum()
    l.backward()
    
    conv2d1.weight.data -=lr * conv2d1.weight.grad
    conv2d1.bias.data -=lr * conv2d1.bias.grad
    
    conv2d1.weight.grad.fill_(0)
    conv2d1.bias.grad.fill_(0)
    
    if (i+1) % 5==0:
        print('step %d ,loss %.3f ' % (i+1,l.item()))
    

step 5 ,loss 20.296 
step 10 ,loss 5.538 
step 15 ,loss 1.529 
step 20 ,loss 0.425 
step 25 ,loss 0.118 
step 30 ,loss 0.033 
step 35 ,loss 0.009 
step 40 ,loss 0.003 
step 45 ,loss 0.001 
step 50 ,loss 0.000 


In [53]:
conv2d1.weight.data

tensor([[ 0.9255, -0.9331]])

In [54]:
conv2d1.bias.data

tensor([0.0042])

In [58]:
x.sum()

tensor(24.)

In [ ]:
nn.Conv2d()