In [1]:
import torch
import torch.nn as nn

In [68]:
def corr2d(x,k):
    h,w=k.shape
    y=torch.zeros((x.shape[0]-h+1,x.shape[1]-w+1),dtype=torch.float)
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            y[i,j]=(x[i:i+h,j:j+w].float()*k.float()).sum()
    return y

In [69]:
x=torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
k=torch.tensor([[0,1],[2,3]])
z=corr2d(x,k)
z[0][0].item()

19.0

In [70]:
type(z[0][0].item())

float

In [71]:
class Conv2D(nn.Module):
    def __init__(self,kernel_size):
        super().__init__()
        self.weight=nn.Parameter(torch.randn(kernel_size,dtype=torch.float))
        self.bias=nn.Parameter(torch.randn(1),dtype=torch.float)
    
    def forward(self,x):
        return corr2d(x,self.weight)+self.bias

In [72]:
k

tensor([[0, 1],
        [2, 3]])

In [73]:
x = torch.ones(6, 8)
x[:, 2:6] = 0
x

tensor([[1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.],
        [1., 1., 0., 0., 0., 0., 1., 1.]])

In [74]:
y=corr2d(x,k)
y

tensor([[6., 2., 0., 0., 0., 4., 6.],
        [6., 2., 0., 0., 0., 4., 6.],
        [6., 2., 0., 0., 0., 4., 6.],
        [6., 2., 0., 0., 0., 4., 6.],
        [6., 2., 0., 0., 0., 4., 6.]])