In [1]:
import torch
from torch import nn

In [4]:
def conv2d(x,k):
    h,w=k.shape
    y=torch.zeros((x.shape[0]-h+1,x.shape[1]-w+1))
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            y[i,j]=(x[i:i+h,j:j+w].float() * k.float()).sum()
    return y

In [2]:
def comp_conv2d(conv2d,x):
    x=x.view((1,1)+x.shape)
    y=conv2d(x)
    return y.view(y.shape[2:])

In [5]:
conv2d1=nn.Conv2d(in_channels=1,out_channels=1,kernel_size=3,padding=1)
x=torch.rand(8,8)
comp_conv2d(conv2d1,x).shape

torch.Size([8, 8])

In [9]:
for name,param in conv2d1.named_parameters():
    print(name)
    print(param)

weight
Parameter containing:
tensor([[[[-0.1195, -0.2076,  0.0883],
          [-0.1818,  0.0266,  0.2336],
          [ 0.0182,  0.1517,  0.0578]]]], requires_grad=True)
bias
Parameter containing:
tensor([0.2883], requires_grad=True)


In [10]:
x.view((1,1)+x.shape)

tensor([[[[0.0483, 0.0089, 0.1331, 0.6917, 0.6769, 0.6697, 0.8447, 0.3755],
          [0.8590, 0.8603, 0.4501, 0.2985, 0.1672, 0.3546, 0.5934, 0.8774],
          [0.4305, 0.4923, 0.3342, 0.0089, 0.1055, 0.9070, 0.3980, 0.2577],
          [0.6183, 0.0642, 0.7426, 0.5170, 0.1712, 0.3465, 0.7302, 0.6496],
          [0.3893, 0.5717, 0.5528, 0.9065, 0.4775, 0.2204, 0.4434, 0.9947],
          [0.0070, 0.1323, 0.2505, 0.0206, 0.0935, 0.7343, 0.4895, 0.1292],
          [0.5394, 0.0996, 0.6662, 0.9302, 0.4609, 0.6591, 0.8055, 0.1134],
          [0.0016, 0.4507, 0.5637, 0.8105, 0.9158, 0.0513, 0.5912, 0.7819]]]])

In [11]:
(1,1)+x.shape

(1, 1, 8, 8)

In [12]:
x.shape

torch.Size([8, 8])

In [14]:
conv2d1(x.view((1,1)+x.shape)).shape

torch.Size([1, 1, 8, 8])