In [1]:
import torch
import torch.nn as nn

In [8]:
def pool2d(x,pool_size,mode='max'):
    x=x.float()
    p_h,p_w=pool_size
    y=torch.zeros(x.shape[0]-p_h+1,x.shape[1]-p_w+1)
    for i in range(y.shape[0]):
        for j in range(y.shape[1]):
            if mode=='max':
                y[i,j]=x[i:i+p_h,j:j+p_w].max()
            elif mode=='avg':
                y[i,j]=x[i:i+p_h,j:j+p_w].mean()
    return y

In [11]:
x

tensor([[0, 1, 2],
        [3, 4, 5],
        [6, 7, 8]])

In [10]:
x=torch.tensor([[0,1,2],[3,4,5],[6,7,8]])
pool2d(x,(2,2))

tensor([[4., 5.],
        [7., 8.]])

In [13]:
pool2d(x,(2,2),'avg')

tensor([[2., 3.],
        [5., 6.]])

In [14]:
x=torch.arange(16,dtype=torch.float).view(1,1,4,4)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]]]])

In [15]:
pool2d1=nn.MaxPool2d(3)
pool2d1(x)

tensor([[[[10.]]]])

In [16]:
pool2d2=nn.MaxPool2d(3,padding=1,stride=2)
pool2d2(x)

tensor([[[[ 5.,  7.],
          [13., 15.]]]])

In [18]:
pool2d3=nn.MaxPool2d((2,4),padding=(1,2),stride=(2,3))
pool2d3(x)

tensor([[[[ 1.,  3.],
          [ 9., 11.],
          [13., 15.]]]])

In [19]:
x=torch.cat((x,x+1),dim=1)
x

tensor([[[[ 0.,  1.,  2.,  3.],
          [ 4.,  5.,  6.,  7.],
          [ 8.,  9., 10., 11.],
          [12., 13., 14., 15.]],

         [[ 1.,  2.,  3.,  4.],
          [ 5.,  6.,  7.,  8.],
          [ 9., 10., 11., 12.],
          [13., 14., 15., 16.]]]])

In [20]:
pool2d4=nn.MaxPool2d(3,padding=1,stride=2)
pool2d4(x)

tensor([[[[ 5.,  7.],
          [13., 15.]],

         [[ 6.,  8.],
          [14., 16.]]]])