In [1]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets as ds
import matplotlib.colors
from sklearn.cluster import KMeans

In [2]:
def expand(a,b):
    d=(b-a)*0.1
    return a-d,b+d

In [4]:
N = 400
centers = 4
data, y = ds.make_blobs(N, n_features=2, centers=centers, random_state=2)
data2, y2 = ds.make_blobs(N,
                          n_features=2,
                          centers=centers,
                          cluster_std=(1, 2.5, 0.5, 2),
                          random_state=2)
data3= np.vstack(
    (data[y == 0][:], 
     data[y == 1][:50], 
     data[y == 2][:20], 
     data[y == 3][:5]))
y3 = np.array([0] * 100 + [1] * 50 + [2] * 20 + [3] * 5)

In [20]:
cls=KMeans(n_clusters=4,init='k-means++')
y_hat=cls.fit_predict(data)
y2_hat=cls.fit_predict(data2)
y3_hat=cls.fit_predict(data3)

In [208]:
y

array([0, 3, 0, 3, 2, 3, 3, 2, 0, 0, 1, 3, 1, 2, 1, 0, 1, 0, 3, 1, 2, 1, 0,
       1, 2, 1, 0, 2, 0, 3, 0, 2, 2, 0, 1, 3, 0, 3, 0, 1, 1, 3, 0, 2, 1, 0,
       3, 1, 1, 3, 2, 0, 0, 3, 1, 0, 1, 3, 3, 1, 2, 1, 1, 2, 1, 2, 1, 2, 1,
       2, 2, 1, 3, 2, 3, 2, 2, 1, 0, 2, 3, 3, 3, 1, 1, 2, 0, 3, 3, 2, 1, 2,
       0, 0, 2, 1, 1, 2, 3, 1, 1, 2, 2, 0, 1, 3, 3, 2, 3, 1, 3, 3, 1, 2, 1,
       1, 1, 2, 0, 0, 2, 3, 2, 2, 0, 2, 2, 2, 2, 2, 0, 0, 2, 0, 1, 0, 1, 0,
       3, 1, 2, 3, 2, 0, 0, 3, 1, 0, 0, 0, 0, 2, 0, 1, 3, 2, 2, 3, 1, 2, 0,
       0, 0, 2, 2, 0, 3, 1, 0, 0, 3, 1, 1, 0, 0, 3, 2, 3, 1, 1, 2, 3, 3, 1,
       1, 0, 0, 1, 0, 1, 3, 2, 3, 0, 3, 2, 2, 3, 0, 1, 1, 2, 0, 3, 1, 3, 0,
       3, 1, 1, 3, 3, 0, 3, 2, 1, 2, 3, 0, 2, 0, 3, 3, 2, 0, 2, 3, 3, 1, 2,
       0, 1, 3, 2, 3, 3, 0, 0, 1, 0, 1, 0, 2, 3, 2, 0, 0, 0, 1, 1, 2, 2, 0,
       3, 3, 0, 2, 0, 0, 1, 2, 0, 2, 3, 2, 2, 0, 0, 2, 3, 3, 3, 3, 1, 3, 0,
       3, 2, 0, 0, 2, 3, 3, 1, 3, 3, 1, 3, 2, 1, 1, 2, 2, 3, 0, 2, 2, 0, 1,
       0, 2,

In [207]:
y_hat

array([1, 0, 1, 0, 2, 0, 0, 2, 1, 1, 3, 0, 3, 2, 3, 1, 3, 1, 0, 3, 2, 3, 1,
       3, 2, 3, 1, 2, 1, 0, 1, 2, 2, 1, 3, 0, 1, 0, 1, 3, 3, 0, 1, 2, 3, 1,
       0, 3, 3, 0, 2, 1, 1, 0, 3, 1, 3, 0, 0, 3, 2, 3, 3, 2, 3, 2, 3, 2, 3,
       2, 2, 3, 0, 2, 0, 2, 2, 3, 1, 2, 0, 0, 0, 3, 3, 2, 1, 0, 0, 2, 3, 2,
       1, 1, 2, 3, 3, 2, 0, 3, 3, 2, 2, 1, 3, 0, 0, 2, 0, 3, 0, 0, 3, 2, 3,
       3, 3, 2, 1, 1, 2, 0, 2, 2, 1, 2, 2, 2, 2, 2, 1, 1, 2, 1, 3, 1, 3, 1,
       0, 3, 2, 0, 2, 1, 1, 0, 2, 1, 1, 1, 1, 2, 1, 3, 0, 2, 2, 0, 3, 2, 1,
       1, 1, 2, 2, 1, 0, 3, 1, 1, 0, 3, 3, 1, 1, 0, 2, 0, 3, 3, 2, 0, 0, 3,
       3, 1, 1, 3, 1, 3, 0, 2, 0, 1, 0, 2, 2, 0, 1, 3, 3, 2, 1, 0, 3, 0, 1,
       0, 3, 3, 0, 0, 1, 0, 2, 3, 2, 0, 1, 2, 1, 0, 0, 2, 1, 2, 0, 0, 3, 2,
       1, 3, 0, 2, 0, 0, 1, 1, 3, 1, 3, 1, 2, 0, 2, 1, 1, 1, 3, 3, 2, 2, 1,
       0, 0, 1, 2, 1, 1, 3, 2, 1, 2, 0, 2, 2, 1, 1, 2, 0, 0, 0, 0, 3, 0, 1,
       0, 2, 1, 1, 2, 0, 0, 3, 0, 0, 3, 0, 2, 3, 3, 2, 2, 0, 1, 2, 2, 1, 3,
       1, 2,

In [213]:
np.sum(y3_hat==y3)/len(y3)

0.5714285714285714

In [22]:
m=np.array(((1,1),(1,3)))
data_r=data.dot(m)
y_r_hat=cls.fit_predict(data_r)

In [27]:
cm = matplotlib.colors.ListedColormap(list('rgbm'))
plt.figure(figsize=(9, 10), facecolor='w')
plt.subplot(421)
plt.title('orginal data')
plt.scatter(data[:, 0], data[:, 1], c=y, s=30, cmap=cm, edgecolors='none')
x1_min, x2_min = np.min(data, axis=0)
x1_max, x2_max = np.max(data, axis=0)
x1_min, x1_max = expand(x1_min, x1_max)
x2_min, x2_max = expand(x2_min, x2_max)
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(422)
plt.title(u'KMeans++聚类')
plt.scatter(data[:, 0], data[:, 1], c=y_hat, s=30, cmap=cm, edgecolors='none')
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(423)
plt.title(u'旋转后数据')
plt.scatter(data_r[:, 0], data_r[:, 1], c=y, s=30, cmap=cm, edgecolors='none')
x1_min, x2_min = np.min(data_r, axis=0)
x1_max, x2_max = np.max(data_r, axis=0)
x1_min, x1_max = expand(x1_min, x1_max)
x2_min, x2_max = expand(x2_min, x2_max)
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(424)
plt.title(u'旋转后KMeans++聚类')
plt.scatter(data_r[:, 0],
            data_r[:, 1],
            c=y_r_hat,
            s=30,
            cmap=cm,
            edgecolors='none')
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(425)
plt.title(u'方差不相等数据')
plt.scatter(data2[:, 0], data2[:, 1], c=y2, s=30, cmap=cm, edgecolors='none')
x1_min, x2_min = np.min(data2, axis=0)
x1_max, x2_max = np.max(data2, axis=0)
x1_min, x1_max = expand(x1_min, x1_max)
x2_min, x2_max = expand(x2_min, x2_max)
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(426)
plt.title(u'方差不相等KMeans++聚类')
plt.scatter(data2[:, 0],
            data2[:, 1],
            c=y2_hat,
            s=30,
            cmap=cm,
            edgecolors='none')
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(427)
plt.title(u'数量不相等数据')
plt.scatter(data3[:, 0], data3[:, 1], s=30, c=y3, cmap=cm, edgecolors='none')
x1_min, x2_min = np.min(data3, axis=0)
x1_max, x2_max = np.max(data3, axis=0)
x1_min, x1_max = expand(x1_min, x1_max)
x2_min, x2_max = expand(x2_min, x2_max)
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.subplot(428)
plt.title(u'数量不相等KMeans++聚类')
plt.scatter(data3[:, 0],
            data3[:, 1],
            c=y3_hat,
            s=30,
            cmap=cm,
            edgecolors='none')
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.grid(True)

plt.tight_layout(2)
plt.suptitle(u'数据分布对KMeans聚类的影响', fontsize=18)
# https://github.com/matplotlib/matplotlib/issues/829
plt.subplots_adjust(top=0.92)
# plt.show()

my kmean code

In [29]:
def points_dist(x1,x2,p=2):
    return np.sqrt((x1[0]-x2[0])**2+(x1[1]-x2[1])**2)

In [54]:
k=4
x1=np.random.randint(data[0].min(),data[0].max(),2)
x2=np.random.randint(data[0].min(),data[0].max(),2)
x1,x2=np.meshgrid(x1,x2)
print('x1:',x1.ravel())
print('x2:',x2.ravel())

# plt.scatter(x1,x2)
# plt.show()


x1: [-2 -5 -2 -5]
x2: [-9 -9 -3 -3]


In [55]:
x1.flatten()

array([-2, -5, -2, -5])

In [61]:
aa=[5]*len(data)
aa[1]=2
aa[2]=4
aa

[5,
 2,
 4,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,
 5,


In [58]:
x41=x1.ravel()
x42=x2.ravel()
y4=y

In [ ]:
points_dist((x41[0],x42[0]),(data[j][0],data[j][1]))

In [109]:
y4_hat=np.array([5,5,5]*len(data))
y4_hat=y4_hat.reshape((len(data),3))
y4_hat

array([[5, 5, 5],
       [5, 5, 5],
       [5, 5, 5],
       ..., 
       [5, 5, 5],
       [5, 5, 5],
       [5, 5, 5]])

In [137]:
y4_hat=np.array([5.0,5.0,5.0,5.0]*len(data))
y4_hat=y4_hat.reshape((len(data),4))
for j in range(len(data)):
    dist2=100
    for i in range(k):
        dist1=points_dist((x41[i],x42[i]),(data[j][0],data[j][1]))
        if dist1<dist2:
            dist2=dist1
            y4_hat[j]=[j,i,dist2,100]

In [138]:
y4_hat

array([[   0.        ,    0.        ,    1.41052824,  100.        ],
       [   1.        ,    3.        ,    4.21059091,  100.        ],
       [   2.        ,    0.        ,    1.39030159,  100.        ],
       ..., 
       [ 397.        ,    2.        ,    0.76975024,  100.        ],
       [ 398.        ,    2.        ,    3.12996002,  100.        ],
       [ 399.        ,    2.        ,    5.07639619,  100.        ]])

In [187]:
avg_dist=[100.0,100.0,100.0]*k
avg_dist=np.array(avg_dist).reshape(k,3)
for i in range(k):
    t_dist=np.average(y4_hat[np.array(y4_hat)[:,1]==i,2])
    avg_dist[i]=[i,t_dist,100.0]
avg_dist
    

array([[   0.        ,    1.48420675,  100.        ],
       [   1.        ,    1.27115412,  100.        ],
       [   2.        ,    2.53253168,  100.        ],
       [   3.        ,    5.35552827,  100.        ]])

In [145]:
for i in range(len(data)):
    for j in avg_dist:
        if j[0]==y4_hat[i,1]:
            y4_hat[i,3]=abs(y4_hat[i,2]-j[1])
            

In [198]:
for j in range(k):
    avg_dist[j,2]=np.where(y4_hat[:,3]==np.sort(y4_hat[y4_hat[:,1]==j,3])[0])[0][0]
avg_dist    

array([[   0.        ,    1.48420675,  393.        ],
       [   1.        ,    1.27115412,   26.        ],
       [   2.        ,    2.53253168,  117.        ],
       [   3.        ,    5.35552827,   11.        ]])

In [202]:
avg_dist[0,2]

393.0

In [203]:
data[int(avg_dist[0,2]),:2]

array([-0.58390398, -8.78405909])

In [204]:
for j in range(len(data)):
    for i in range(k):
        dist1=points_dist(data[int(avg_dist[i,2]),:2],(data[j][0],data[j][1]))
        if dist1<avg_dist[i,1]:
            dist2=dist1
            y4_hat[j]=[j,i,dist2,100]

In [205]:
y4_hat

array([[  0.00000000e+00,   0.00000000e+00,   1.41052824e+00,
          7.36785092e-02],
       [  1.00000000e+00,   3.00000000e+00,   1.14365328e+00,
          1.00000000e+02],
       [  2.00000000e+00,   1.00000000e+00,   4.00006096e-01,
          1.00000000e+02],
       ..., 
       [  3.97000000e+02,   2.00000000e+00,   1.78003077e+00,
          1.00000000e+02],
       [  3.98000000e+02,   2.00000000e+00,   3.12996002e+00,
          5.97428344e-01],
       [  3.99000000e+02,   2.00000000e+00,   5.07639619e+00,
          2.54386451e+00]])