In [4]:
from PIL import Image
import numpy as np
from sklearn.cluster import KMeans
import matplotlib
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d import Axes3D

In [9]:
def restore_image(cb,cluster,shape):
    row,col,dummy=shape
    image=np.empty((row,col,3))
    index=0
    for r in range(row):
        for c in range(col):
            image[r,c]=cb[cluster[index]]
    return image

In [12]:
def show_scatter(a):
    N=10
    print('original data')
    density,edges=np.histogramdd(a,bins=[N,N,N],range=[(0,1),(0,1),(0,1)])
    density/=density.max()
    x=y=z=np.arange(N)
    d=np.meshgrid(x,y,z)
    
    fig=plt.figure(1,facecolor='w')
    ax=fig.add_subplot(111,projection='3d')
    ax.scatter(d[1],d[0],d[2],c='r',s=100*density,marker='o',depthshade=True)
    ax.set_xlabel('red')
    ax.set_ylabel('green')
    ax.set_zlabel('blue')
    plt.title('3d frequency dist',fontsize=20)
    
    plt.figure(2,facecolor='w')
    den=density[density>0]
    den=np.sort(den)[::-1]
    t=np.arange(len(den))
    plt.plot(t,den,'r-',t,den,'go',lw=2)
    plt.title('color dist',fontsize=18)
    plt.grid(True)
    plt.show()
    

In [13]:
num_vq=50
im=Image.open(r"F:\study\ml\DoctorZou\16KNN_II\16.代码\16.Clustering\16.Lena.png")
image=np.array(im).astype(np.float)/255
image=image[:,:,:3]
image_v=image.reshape((-1,3))
model=KMeans(num_vq)
show_scatter(image_v)

N=image_v.shape[0]
idx=np.random.randint(0,N,size=1000)
image_sample=image_v[idx]
model.fit(image_sample)
c=model.predict(image_v)
print('knn result:',c)
print('knn center:',model.cluster_centers_)

plt.subplot(121)
plt.axis('off')
plt.title('original image ')
plt.imshow(image)

plt.subplot(122)
vq_image=restore_image(model.cluster_centers_,c,image.shape)
plt.axis('off')
plt.title('quantization image : %d ' % num_vq)
plt.imshow(vq_image)

plt.tight_layout(1.2)
# plt.show()

original data
knn result: [25 45 45 ..., 34 34 17]
knn center: [[ 0.81176471  0.37664884  0.36993464]
 [ 0.34117647  0.08280112  0.25030812]
 [ 0.86718954  0.70352941  0.63947712]
 [ 0.54070588  0.17066667  0.26807843]
 [ 0.83006536  0.56372549  0.51699346]
 [ 0.6459893   0.30231729  0.35579323]
 [ 0.86666667  0.4713352   0.46610644]
 [ 0.93906486  0.82835596  0.77013575]
 [ 0.74732026  0.47712418  0.46      ]
 [ 0.37201426  0.12228164  0.31229947]
 [ 0.48698752  0.23529412  0.41212121]
 [ 0.85754011  0.41989305  0.39622103]
 [ 0.65505882  0.24611765  0.30086275]
 [ 0.57611408  0.31871658  0.50409982]
 [ 0.9260311   0.60649087  0.47532116]
 [ 0.96392157  0.74352941  0.56235294]
 [ 0.74291939  0.59041394  0.63398693]
 [ 0.72563544  0.32229484  0.34829339]
 [ 0.44475997  0.13590264  0.26423259]
 [ 0.9122807   0.77234262  0.72776058]
 [ 0.80392157  0.60735294  0.57279412]
 [ 0.88581315  0.60484429  0.55732411]
 [ 0.38996808  0.09037848  0.23246694]
 [ 0.54024276  0.22819795  0.31596639]
 