In [1]:
from sklearn import datasets
import numpy as np
import random
import matplotlib.pyplot as plt
import time
import copy
from sklearn.metrics import euclidean_distances
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [2]:
x1,y1=datasets.make_circles(n_samples=2000,noise=0.02,factor=0.6,random_state=5)
x2,y2=datasets.make_blobs(n_features=2,n_samples=500,centers=[[1.2,1.2]]
                          ,cluster_std=0.1,random_state=5)
data=np.vstack((x1,x2))

In [3]:
data.shape

(2500, 2)

In [4]:
eps=0.2
minpts=10

In [5]:
dist=euclidean_distances(data)
ptype_list=[]
for row in dist:
    ptype=0
    density=np.sum(np.where(row<eps))
    if density >minpts:
        ptype=1
    elif density >1 :
        ptype=2
    else :
        ptype=0
    ptype_list.append(ptype)

In [6]:
cpt_index=[]
for k,v in enumerate(ptype_list):
    if v >0:
        cpt_index.append(k)

In [7]:
cpt_data=data[cpt_index,:]
cpt_dist=euclidean_distances(cpt_data)

In [8]:
dist

array([[ 0.        ,  1.25347713,  1.56798102, ...,  0.99331837,
         1.08568777,  0.77152249],
       [ 1.25347713,  0.        ,  0.58812959, ...,  1.70978515,
         1.79208908,  1.7437466 ],
       [ 1.56798102,  0.58812959,  0.        , ...,  2.22456536,
         2.31281155,  2.19809133],
       ..., 
       [ 0.99331837,  1.70978515,  2.22456536, ...,  0.        ,
         0.09544468,  0.35751183],
       [ 1.08568777,  1.79208908,  2.31281155, ...,  0.09544468,
         0.        ,  0.41569345],
       [ 0.77152249,  1.7437466 ,  2.19809133, ...,  0.35751183,
         0.41569345,  0.        ]])

In [9]:
cpt_dist

array([[ 0.        ,  1.25347713,  1.56798102, ...,  0.99331837,
         1.08568777,  0.77152249],
       [ 1.25347713,  0.        ,  0.58812959, ...,  1.70978515,
         1.79208908,  1.7437466 ],
       [ 1.56798102,  0.58812959,  0.        , ...,  2.22456536,
         2.31281155,  2.19809133],
       ..., 
       [ 0.99331837,  1.70978515,  2.22456536, ...,  0.        ,
         0.09544468,  0.35751183],
       [ 1.08568777,  1.79208908,  2.31281155, ...,  0.09544468,
         0.        ,  0.41569345],
       [ 0.77152249,  1.7437466 ,  2.19809133, ...,  0.35751183,
         0.41569345,  0.        ]])

In [10]:
cpt_dist[0]

array([ 0.        ,  1.25347713,  1.56798102, ...,  0.99331837,
        1.08568777,  0.77152249])

In [11]:
 np.where(cpt_dist[0] < eps)[0]

array([   0,   19,   84,   91,  183,  184,  258,  260,  280,  399,  404,
        479,  506,  542,  569,  593,  603,  635,  648,  654,  708,  715,
        768,  771,  788,  798,  849,  942,  951, 1091, 1117, 1127, 1148,
       1224, 1234, 1245, 1297, 1300, 1312, 1313, 1344, 1365, 1371, 1413,
       1481, 1484, 1592, 1596, 1627, 1638, 1651, 1681, 1682, 1753, 1762,
       1764, 1834, 1845, 1887, 1902, 1925, 1964, 1978, 1993], dtype=int64)

In [12]:
cpt_dist.shape

(2500, 2500)

In [13]:
a=np.zeros((2,2))
for k,v in enumerate(a):
    print(k,v)

0 [ 0.  0.]
1 [ 0.  0.]


In [14]:
cluster = dict()
for k, v in enumerate(cpt_dist):
    cluster[k] = np.where(v < eps)[0]

In [15]:
for k,v in cluster.items():
    print(k,len(v))

0 64
1 103
2 99
3 100
4 62
5 63
6 61
7 111
8 107
9 107
10 64
11 64
12 105
13 105
14 65
15 63
16 109
17 60
18 108
19 59
20 105
21 67
22 105
23 104
24 103
25 103
26 63
27 62
28 67
29 104
30 104
31 107
32 65
33 64
34 66
35 67
36 105
37 63
38 63
39 62
40 63
41 108
42 105
43 109
44 66
45 66
46 109
47 107
48 104
49 61
50 104
51 64
52 61
53 60
54 63
55 103
56 64
57 61
58 63
59 66
60 59
61 100
62 65
63 109
64 109
65 109
66 64
67 61
68 62
69 66
70 107
71 101
72 66
73 64
74 64
75 61
76 101
77 66
78 102
79 95
80 106
81 60
82 64
83 66
84 65
85 106
86 64
87 65
88 65
89 64
90 61
91 63
92 64
93 109
94 107
95 102
96 63
97 61
98 103
99 108
100 63
101 103
102 99
103 103
104 99
105 107
106 108
107 62
108 104
109 61
110 66
111 62
112 109
113 64
114 106
115 98
116 106
117 104
118 67
119 103
120 105
121 68
122 66
123 111
124 64
125 60
126 102
127 66
128 102
129 108
130 62
131 110
132 60
133 107
134 106
135 107
136 107
137 65
138 65
139 65
140 111
141 59
142 65
143 67
144 104
145 64
146 66
147 108
148 64
149

2160 334
2161 375
2162 245
2163 253
2164 380
2165 344
2166 323
2167 394
2168 250
2169 102
2170 411
2171 316
2172 119
2173 231
2174 398
2175 407
2176 220
2177 276
2178 400
2179 257
2180 260
2181 308
2182 398
2183 364
2184 394
2185 359
2186 367
2187 260
2188 293
2189 130
2190 139
2191 419
2192 349
2193 344
2194 339
2195 354
2196 286
2197 426
2198 422
2199 400
2200 223
2201 339
2202 146
2203 411
2204 295
2205 430
2206 369
2207 145
2208 356
2209 404
2210 348
2211 370
2212 329
2213 425
2214 355
2215 392
2216 383
2217 412
2218 297
2219 355
2220 382
2221 282
2222 318
2223 358
2224 165
2225 227
2226 204
2227 351
2228 356
2229 416
2230 262
2231 265
2232 410
2233 372
2234 281
2235 217
2236 400
2237 299
2238 345
2239 430
2240 395
2241 268
2242 390
2243 388
2244 363
2245 426
2246 321
2247 370
2248 202
2249 331
2250 61
2251 421
2252 419
2253 398
2254 25
2255 400
2256 253
2257 431
2258 375
2259 297
2260 105
2261 424
2262 413
2263 400
2264 419
2265 140
2266 259
2267 381
2268 276
2269 415
2270 413
227

In [16]:
for i in range(len(cluster)):
    for j in range(len(cluster)):
        if len(set(cluster[i]).intersection(set(cluster[j])))>0 and i != j:
            cluster[i]=list(set(cluster[i]).union(set(cluster[j])))
            cluster[j]=[]

In [50]:
for k,v in cluster.items():
    if len(v)>0:
        print(k,len(v))

2 1000
4 1000
2000 500
