In [56]:
import numpy as np
import matplotlib.pyplot as plt
import sklearn.datasets as ds
import matplotlib.colors
from sklearn.cluster import KMeans

In [57]:
N = 400
K_num = 4
data, y = ds.make_blobs(N, n_features=2, centers=K_num, random_state=2)
data2, y2 = ds.make_blobs(N,
                          n_features=2,
                          centers=K_num,
                          cluster_std=(1, 2.5, 0.5, 2),
                          random_state=2)

data3 = np.vstack(
    (data[y == 0][:], data[y == 1][:50], data[y == 2][:20], data[y == 3][:5]))
y3 = np.array([0] * 100 + [1] * 50 + [2] * 20 + [3] * 5)

In [58]:
x1_mm=[data[:,0].min(),data[:,0].max()]
x2_mm=[data[:,1].min(),data[:,1].max()]
x1,x2=np.meshgrid(x1_mm,x2_mm)
data_i=np.stack((x1.ravel(),x2.ravel()),axis=1)
data_i

array([[ -8.09999402, -11.82507855],
       [  2.92640652, -11.82507855],
       [ -8.09999402,   4.6280828 ],
       [  2.92640652,   4.6280828 ]])

In [59]:
np.power(8,1/3)

2.0

In [60]:
def point_dest(x1, x2, p=2):
    return np.power((np.power((x1[0] - x2[0]), p) + np.power(
        (x1[1] - x2[1]), p)), 1 / p)

In [61]:
y_hat=np.zeros((len(data),4))
for i in range(400):
    dest2=100
    ck=10
    for k in range(K_num):
        dest1=point_dest(data[i],data_i[k])
        if dest1<dest2:
            dest2=dest1
            ck=k
    y_hat[i]=[i,ck,dest2,100]
    
data_i2=np.zeros((K_num,2))
for k in range(K_num):
    data_i2[k]=np.average(data[y_hat[y_hat[:,1]==k,0].astype(int),:],axis=0)
data_i2    
           

array([[-3.03186066, -6.81047136],
       [-1.1276994 , -7.76141868],
       [-5.80262472,  2.01636903],
       [ 0.27208826, -1.72104205]])

In [62]:
y_hat[y_hat[:,1]==0,0]

array([   2.,   22.,   26.,   38.,   65.,   89.,  128.,  148.,  164.,
        176.,  247.,  251.,  292.,  295.,  328.,  344.,  347.,  365.,
        366.,  375.,  386.])

In [63]:
y_hat[y_hat[:,1]==0,0].astype(int)

array([  2,  22,  26,  38,  65,  89, 128, 148, 164, 176, 247, 251, 292,
       295, 328, 344, 347, 365, 366, 375, 386])

In [64]:
np.average(data[y_hat[y_hat[:,1]==0,0].astype(int),:],axis=0)

array([-3.03186066, -6.81047136])

In [97]:
y_hat=np.zeros((len(data),4))
changed=True
count_old=[0]*4
j=0
z=0

count_new=count_old
for i in range(len(data)):
    dest2=100
    ck=10
    for k in range(K_num):
        if z==0:
            dest1=point_dest(data[i],data_i[k])
        else :
            dest1=point_dest(data[i],data_i2[k])
        if dest1<dest2:
            dest2=dest1
            ck=k
    y_hat[i]=[i,ck,dest2,100]

print(i,np.sum(y_hat[:,1]==y)/len(y))
y_hat

data_i2=np.zeros((K_num,2))
for k in range(K_num):
    data_i2[k]=np.average(data[y_hat[y_hat[:,1]==k,0].astype(int),:],axis=0)
    count_old[k]=len(data[y_hat[y_hat[:,1]==k].astype(int)])

if count_old == count_new:
    j+=1
    print(j)
    print('----')
    if j==5:
        changed=False
# z+=1

399 0.0375
1
----


In [96]:
def points_dist(x1,x2,p=2):
    return np.sqrt((x1[0]-x2[0])**2+(x1[1]-x2[1])**2)
################old

#     avg_dist2=avg_dist
#     y5_hat=y4_hat

y4_hat=np.array([5.0,5.0,5.0,5.0]*len(data))
y4_hat=y4_hat.reshape((len(data),4))
for j in range(len(data)): #len(data)
    dist2=100
    ck=5
    for i in range(K_num):
#         print(int(avg_dist[i,2]),j)
        dist1=points_dist(data_i[i],data[j])
        if dist1<dist2:
#             print(j,i,dist1)
            dist2=dist1
#             ck=i
            y4_hat[j]=[j,i,dist2,100]
y4_hat       
        
# for i in range(k):
#     t_dist=np.average(y4_hat[np.array(y4_hat)[:,1]==i,2])
# #     print(t_dist)
#     avg_dist[i]=[i,t_dist,100.0]
# #     break
# for i in range(len(data)):
#     for j in avg_dist:
#         if j[0]==y4_hat[i,1]:
# #             print(y4_hat[i,2],j[1])
#             y4_hat[i,3]=abs(y4_hat[i,2]-j[1])
# # avg_dist
# for j in range(k):
#     avg_dist[j,2]=np.where(y4_hat[:,3]==np.sort(y4_hat[y4_hat[:,1]==j,3])[0])[0][0]
# # avg_dist 


# print(np.sum(y4_hat[:,1]==y)/len(y))






array([[   0.        ,    1.        ,    5.10503659,  100.        ],
       [   1.        ,    2.        ,    4.11810212,  100.        ],
       [   2.        ,    0.        ,    5.3437538 ,  100.        ],
       ..., 
       [ 397.        ,    3.        ,    9.16957851,  100.        ],
       [ 398.        ,    3.        ,    6.30746738,  100.        ],
       [ 399.        ,    3.        ,    4.6383524 ,  100.        ]])

In [93]:
for i in range(K_num):
    print(i,points_dist(data_i[i],data[398]))
    print(i,point_dest(data[398],data_i[i]))
    



0 13.6988168159
0 13.6988168159
1 10.8557113811
1 10.8557113811
2 10.4687753469
2 10.4687753469
3 6.30746737571
3 6.30746737571


Use mean value to compute new center

In [118]:
y_hat=np.zeros((len(data),4))
changed=True
count_old=[0]*4
j=0
z=0
while changed:
    count_new=count_old
    for i in range(len(data)):
        dest2=100
        ck=10
        for k in range(K_num):
            if z==0:
                dest1=point_dest(data[i],data_i[k])
            else :
                dest1=point_dest(data[i],data_i2[k])
            if dest1<dest2:
                dest2=dest1
                ck=k
        y_hat[i]=[i,ck,dest2,100]
    
    print(i,np.sum(y_hat[:,1]==y)/len(y))
    
    data_i2=np.zeros((K_num,2))
    for k in range(K_num):
        data_i2[k]=np.average(data[y_hat[y_hat[:,1]==k,0].astype(int),:],axis=0)
        count_old[k]=len(data[y_hat[y_hat[:,1]==k].astype(int)])
    print(data_i2)
    print(count_old)
    print(count_new)
    
    if count_old == count_new:
        j+=1
        print(j)
        print('----')
        if j==50:
            changed=False
    z+=1
        
  

399 0.0375
[[-3.03186066 -6.81047136]
 [-1.1276994  -7.76141868]
 [-5.80262472  2.01636903]
 [ 0.27208826 -1.72104205]]
[21, 134, 105, 140]
[21, 134, 105, 140]
1
----
399 0.02
[[-2.43893949 -5.22763626]
 [-1.10672782 -9.32782189]
 [-5.91942653  2.21778527]
 [ 0.12782221 -1.99529085]]
[42, 96, 101, 161]
[42, 96, 101, 161]
2
----
399 0.0025
[[-2.01054961 -4.16589188]
 [-1.27182098 -9.43447643]
 [-5.93749857  2.25998454]
 [ 0.45526479 -1.73463756]]
[64, 99, 100, 137]
[64, 99, 100, 137]
3
----
399 0.0
[[-1.85927114 -3.75687419]
 [-1.27494466 -9.40909347]
 [-5.93749857  2.25998454]
 [ 0.88300134 -1.48894033]]
[88, 100, 100, 112]
[88, 100, 100, 112]
4
----
399 0.0
[[-1.74710635 -3.71764862]
 [-1.27494466 -9.40909347]
 [-5.93749857  2.25998454]
 [ 0.96433708 -1.37323454]]
[95, 100, 100, 105]
[95, 100, 100, 105]
5
----
399 0.0
[[-1.6660748  -3.67905746]
 [-1.27494466 -9.40909347]
 [-5.93749857  2.25998454]
 [ 1.0188777  -1.294605  ]]
[100, 100, 100, 100]
[100, 100, 100, 100]
6
----
399 0.0
[[-

Use median value to compute new center

In [139]:
np.median(data[y_hat[y_hat[:,1]==k,0].astype(int),:],axis=0)

array([ 1.05210626, -1.3559413 ])

In [142]:
np.mean(data[y_hat[y_hat[:,1]==k,0].astype(int),:],axis=0)

array([ 1.0188777, -1.294605 ])

In [140]:
y_hat3=np.zeros((len(data),4))
changed=True
count_old=[0]*4
j=0
z=0
while changed:
    count_new=count_old
    for i in range(len(data)):
        dest2=100
        ck=10
        for k in range(K_num):
            if z==0:
                dest1=point_dest(data[i],data_i[k])
            else :
                dest1=point_dest(data[i],data_i2[k])
            if dest1<dest2:
                dest2=dest1
                ck=k
        y_hat3[i]=[i,ck,dest2,100]
    
    print(i,np.sum(y_hat3[:,1]==y)/len(y))
    
    data_i2=np.zeros((K_num,2))
    for k in range(K_num):
        data_i2[k]=np.median(data[y_hat3[y_hat3[:,1]==k,0].astype(int),:],axis=0)
        count_old[k]=len(data[y_hat3[y_hat3[:,1]==k].astype(int)])
    print(data_i2)
    print(count_old)
    print(count_new)
    
    if count_old == count_new:
        j+=1
        print(j)
        print('----')
        if j==50:
            changed=False
    z+=1

399 0.0375
[[-2.9219904  -5.90874304]
 [-1.28475086 -8.7355845 ]
 [-5.90898023  2.21185794]
 [ 0.47678228 -1.71769259]]
[21, 134, 105, 140]
[21, 134, 105, 140]
1
----
399 0.005
[[-2.17225192 -4.36486452]
 [-1.30945233 -9.42424556]
 [-5.94980334  2.26894544]
 [ 0.43108403 -1.81425431]]
[54, 98, 100, 148]
[54, 98, 100, 148]
2
----
399 0.0
[[-1.78996867 -3.80533218]
 [-1.35709773 -9.40437575]
 [-5.94980334  2.26894544]
 [ 0.82980311 -1.45186852]]
[84, 100, 100, 116]
[84, 100, 100, 116]
3
----
399 0.0
[[-1.74464462 -3.71702913]
 [-1.35709773 -9.40437575]
 [-5.94980334  2.26894544]
 [ 1.00842907 -1.38613034]]
[96, 100, 100, 104]
[96, 100, 100, 104]
4
----
399 0.0
[[-1.69072341 -3.70470337]
 [-1.35709773 -9.40437575]
 [-5.94980334  2.26894544]
 [ 1.05210626 -1.3559413 ]]
[100, 100, 100, 100]
[100, 100, 100, 100]
5
----
399 0.0
[[-1.69072341 -3.70470337]
 [-1.35709773 -9.40437575]
 [-5.94980334  2.26894544]
 [ 1.05210626 -1.3559413 ]]
[100, 100, 100, 100]
[100, 100, 100, 100]
6
----
399 0.0
[

In [128]:
cls=KMeans(n_clusters=4,init='k-means++')
y_hat2=cls.fit_predict(data)
print(i,np.sum(y_hat2==y)/len(y))

399 0.2525


In [129]:
np.sum(y_hat2==y_hat[:,1])

199

In [130]:
from sklearn import metrics

In [131]:
h=metrics.homogeneity_score(y,y_hat[:,1])
c=metrics.completeness_score(y,y_hat[:,1])
print (u'同一性(Homogeneity)：', h)
print (u'完整性(Completeness)：', c)
v2=2*c*h/(c+h)
v=metrics.v_measure_score(y,y_hat[:,1])
print('V-measure:',v2,v)

同一性(Homogeneity)： 0.979801716026
完整性(Completeness)： 0.979801716026
V-measure: 0.979801716026 0.979801716026


In [132]:
h=metrics.homogeneity_score(y,y_hat2)
c=metrics.completeness_score(y,y_hat2)
print (u'同一性(Homogeneity)：', h)
print (u'完整性(Completeness)：', c)
v2=2*c*h/(c+h)
v=metrics.v_measure_score(y,y_hat2)
print('V-measure:',v2,v)

同一性(Homogeneity)： 0.989882824024
完整性(Completeness)： 0.989900675882
V-measure: 0.989891749873 0.989891749873


In [141]:
h=metrics.homogeneity_score(y,y_hat3[:,1])
c=metrics.completeness_score(y,y_hat3[:,1])
print (u'同一性(Homogeneity)：', h)
print (u'完整性(Completeness)：', c)
v2=2*c*h/(c+h)
v=metrics.v_measure_score(y,y_hat3[:,1])
print('V-measure:',v2,v)

同一性(Homogeneity)： 0.979801716026
完整性(Completeness)： 0.979801716026
V-measure: 0.979801716026 0.979801716026


In [144]:
l=[1,2,3,4,50,100]
np.median(l)

3.5