In [1]:
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import  train_test_split
import matplotlib.pyplot as plt

In [2]:
def create_data():
    iris = load_iris()
    df = pd.DataFrame(iris.data, columns=iris.feature_names)
    df['label'] = iris.target
    df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
    data = np.array(df.iloc[:100, [0, 1, -1]])
    for i in range(len(data)):
        if data[i,-1] == 0:
            data[i,-1] = -1
    # print(data)
    return data[:,:2], data[:,-1]

In [3]:
X, y = create_data()
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25)

In [4]:
len(X_test)

25

In [5]:
X_test[0:5]

array([[6.5, 2.8],
       [6.4, 2.9],
       [4.6, 3.6],
       [4.8, 3.4],
       [4.9, 3.1]])

In [6]:
X_train[0:5]

array([[5.5, 2.4],
       [5.6, 2.7],
       [5.5, 2.3],
       [5.7, 2.9],
       [5.5, 2.6]])

In [7]:
y_test[1:5]

array([ 1., -1., -1., -1.])

In [8]:
y_train[0:5]

array([1., 1., 1., 1., 1.])

In [9]:
s=0
for i in range(len(X_test)):
    s+=X_test[i][0]*X_test[i][1]
print(s)

466.01


In [10]:
s1=0
for i in range(len(X_train)):
    s+=X_train[i][0]*X_train[i][1]
    (s+1)**2
print(s)

1686.7500000000007


In [11]:
430.90999999999997/1686.7500000000005

0.25546761523640127

In [12]:
from sklearn.svm import SVC

In [ ]:
SVC()

In [120]:
429*.9

386.1