In [ ]:
import numpy as np
import matplotlib as mpl
# mpl.use('Agg')
import matplotlib.pyplot as plt
%matplotlib auto

In [2]:
stock_max, stock_min, stock_close, stock_amount = np.loadtxt(
    r'F:\study\ml\DoctorZou\06PythonPackage\6.Package\6.SH600000.txt',
    delimiter='\t',
    skiprows=2,
    usecols=(2, 3, 4, 5),unpack=True)

In [3]:
stock_max[1:5]

array([ 10.29,  10.12,   9.97,   9.83])

In [4]:
N=100
stock_close=stock_close[:N]
stock_close

array([ 10.06,  10.15,   9.91,   9.63,   9.76,   9.76,   9.83,   9.25,
         9.34,   9.38,   9.5 ,   9.56,   9.23,   9.63,   9.89,   9.63,
         9.76,   9.27,   9.18,   9.13,   8.89,   8.91,   9.29,   9.15,
         9.01,   8.89,   9.01,   9.17,   9.14,   9.24,   9.17,   9.05,
         9.15,   9.79,  10.12,   9.97,   9.76,  10.06,  10.34,  10.36,
        10.42,  10.66,  10.54,  10.56,  10.31,  10.69,  11.12,  11.  ,
        11.04,  11.08,  11.12,  11.  ,  10.88,  11.1 ,  10.79,  11.15,
        11.06,  10.99,  10.57,   9.69,   9.68,   9.86,   9.47,   9.59,
         9.63,   9.42,   9.47,   9.7 ,   9.47,   9.54,   8.79,   8.5 ,
         8.75,   8.62,   8.88,   9.18,   9.  ,   8.56,   8.97,   8.92,
         8.71,   8.9 ,   9.2 ,   8.85,   8.83,   8.95,   8.84,   8.49,
         8.42,   8.41,   8.29,   8.27,   7.96,   7.82,   8.47,   8.15,
         8.24,   8.26,   8.3 ,   8.75])

In [5]:
n = 5
weight = np.ones(n)
weight /= weight.sum()
stock_sma = np.convolve(stock_close, weight, mode='valid')

In [6]:
weight=np.linspace(1,0,n)
weight=np.exp(weight)
weight/=weight.sum()
weight
stock_ema=np.convolve(stock_close,weight,mode='valid')
stock_ema

array([  9.84814617,   9.80200147,   9.77977143,   9.60396336,
         9.51981626,   9.45513635,   9.44196623,   9.44409305,
         9.39495938,   9.47270879,   9.6103129 ,   9.62621464,
         9.67357241,   9.58785542,   9.45766787,   9.31768267,
         9.15735073,   9.02713757,   9.08705899,   9.09831681,
         9.06812246,   9.02872191,   9.03346292,   9.05300608,
         9.07136084,   9.12909293,   9.16301193,   9.14156669,
         9.14165567,   9.34280375,   9.59288301,   9.74735922,
         9.81321954,   9.94863592,  10.08405789,  10.16641354,
        10.26247692,  10.43034923,  10.49723883,  10.53066257,
        10.47741104,  10.54841771,  10.71570975,  10.81945301,
        10.91087277,  11.01667714,  11.07772587,  11.04987424,
        11.00163945,  11.0287261 ,  10.95016146,  10.99703027,
        11.01628849,  11.02024401,  10.87357431,  10.51406352,
        10.19899982,  10.01742597,   9.76132513,   9.63638181,
         9.62964079,   9.56017449,   9.50558707,   9.56

In [7]:
t=np.arange(n-1,N)
poly=np.polyfit(t,stock_ema,10)
print(poly)
stock_ema_hat=np.polyval(poly,t)
stock_ema_hat

[ -1.54828672e-16   7.72911232e-14  -1.50730384e-11   1.39225179e-09
  -4.94312198e-08  -1.41407546e-06   1.89122124e-04  -6.62482665e-03
   1.05773566e-01  -7.91122537e-01   1.17765096e+01]


array([  9.92719422,   9.75024573,   9.63882554,   9.5748041 ,
         9.54315305,   9.53166735,   9.53068758,   9.53282544,
         9.53269545,   9.52665515,   9.51255591,   9.48950612,
         9.45764823,   9.41795064,   9.37201553,   9.32190303,
         9.26997229,   9.21873953,   9.17075314,   9.12848551,
         9.09424143,   9.07008233,   9.05776598,   9.05870076,
         9.07391368,   9.10403135,   9.14927279,   9.20945316,
         9.2839972 ,   9.37196145,   9.4720639 ,   9.58272019,
         9.70208496,   9.82809749,   9.95853027,  10.09103967,
        10.22321747,  10.35264243,  10.47693084,  10.59378525,
        10.70104051,  10.7967064 ,  10.87900624,  10.94641077,
        10.99766685,  11.03182068,  11.04823488,  11.04659964,
        11.0269373 ,  10.98960073,  10.93526523,  10.86491423,
        10.77981894,  10.68151233,  10.57175769,  10.45251239,
        10.32588731,  10.19410259,  10.05944045,   9.92419577,
         9.79062537,   9.66089685,   9.53703786,   9.42

In [16]:
np.polyval(poly,[100])

array([ 8.8625896])

In [14]:
stock_close

array([ 10.06,  10.15,   9.91,   9.63,   9.76,   9.76,   9.83,   9.25,
         9.34,   9.38,   9.5 ,   9.56,   9.23,   9.63,   9.89,   9.63,
         9.76,   9.27,   9.18,   9.13,   8.89,   8.91,   9.29,   9.15,
         9.01,   8.89,   9.01,   9.17,   9.14,   9.24,   9.17,   9.05,
         9.15,   9.79,  10.12,   9.97,   9.76,  10.06,  10.34,  10.36,
        10.42,  10.66,  10.54,  10.56,  10.31,  10.69,  11.12,  11.  ,
        11.04,  11.08,  11.12,  11.  ,  10.88,  11.1 ,  10.79,  11.15,
        11.06,  10.99,  10.57,   9.69,   9.68,   9.86,   9.47,   9.59,
         9.63,   9.42,   9.47,   9.7 ,   9.47,   9.54,   8.79,   8.5 ,
         8.75,   8.62,   8.88,   9.18,   9.  ,   8.56,   8.97,   8.92,
         8.71,   8.9 ,   9.2 ,   8.85,   8.83,   8.95,   8.84,   8.49,
         8.42,   8.41,   8.29,   8.27,   7.96,   7.82,   8.47,   8.15,
         8.24,   8.26,   8.3 ,   8.75])

In [17]:
plt.plot(np.arange(N),stock_close,'ro-',lw=2,label=u'original price')
t=np.arange(n-1,N)
plt.plot(t,stock_sma,'b-',lw=2,label='simple average price')
plt.plot(t,stock_ema,'g-',lw=2,label='exponential average price')
plt.ioff()
# plt.show()
# plt.imshow()
plt.show()


In [22]:
plt.plot(np.arange(N), stock_close, 'ro-', linewidth=1, label=u'原始收盘价')
# plt.plot(t, stock_ema, 'g-', linewidth=2, label=u'指数移动平均线')
plt.plot(t, stock_ema_hat, 'm-', linewidth=3, label=u'指数移动平均线估计')
plt.show()