In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from collections import Counter
import math

In [117]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['label'] = iris.target
df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
data = np.array(df.iloc[:100, :])
X,y=data[:,:-1], data[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3,random_state=7)

In [6]:
X_test[0], y_test[0]

(array([4.6, 3.4, 1.4, 0.3]), 0.0)

In [24]:
a={label:[] for label in list(set(y_test))}
a[0.0].append(3)
a[0.0].append(4)
for i in a.items():
    print(i)

(0.0, [3, 4])
(1.0, [])


In [28]:
{label:value for label,value in a.items()}


{0.0: [3, 4], 1.0: []}

In [118]:
model=None

def mean(x):
    return sum(x) / float(len(x))

def stdev(x):
    avg=mean(x)
    return np.sqrt((sum((x1-mean(x))**2 for x1 in x))/len(x))

def gaussian_probability(x,mean,stdev):
    exponent=math.exp(-(math.pow(x-mean,2)/(2*math.pow(stdev,2))))
    return (1 / (math.sqrt(2*np.pi)*stdev)) * exponent

def summary(train_data):
    summaries=[(mean(i),stdev(i)) for i in zip(*train_data)]
    return summaries

def fit(x,y):
    global model
    labels=list(set(y))
    data={label:[] for label in labels}
    for f,label in zip(x,y):
        data[label].append(f)
#     model=data
    model={label:summary(value) for label,value in data.items()}
    return 'gaussianNB train done'

def calculate_probabilityes(input_data):
    probabilities={}
    global model
    for label,value in model.items():
        probabilities[label]=1
        for i in range(len(value)):
            mean,stdev=value[i]
            print(input_data[i])
            probabilities[label] *=gaussian_probability(input_data[i],mean,stdev)  
            #此处的mean,stdev 并不是函数,而是变量,函数需要传递参数
    print(probabilities)        
    return probabilities

def predict(x_test):
    label=sorted(calculate_probabilityes(x_test).items(),key=lambda x:x[-1])[-1][0]
    return label

def score(x_test,y_test):
    right=0
    for x,y in zip(x_test,y_test):
        label=predict(x)
        if label ==y:
            right+=1
    return right/float(len(x_test))

In [119]:
fit(X_train,y_train)

'gaussianNB train done'

In [107]:
predict([4.4,  3.2,  1.3,  0.2])

4.4
3.2
1.3
0.2
4.4
3.2
1.3
0.2
{0.0: 1.1412978897950963, 1.0: 1.0876612115906482e-20}


0.0

In [120]:
model

{0.0: [(5.008823529411764, 0.33726202682852463),
  (3.4205882352941184, 0.38100440924166706),
  (1.4705882352941178, 0.15629800300689908),
  (0.24411764705882355, 0.10898239596264063)],
 1.0: [(5.86388888888889, 0.4859999872986838),
  (2.688888888888889, 0.2960647243216495),
  (4.219444444444445, 0.4886599842906246),
  (1.302777777777778, 0.2074797327600285)]}

In [112]:
model

{0.0: [array([4.7, 3.2, 1.3, 0.2]),
  array([5.4, 3.4, 1.7, 0.2]),
  array([4.8, 3. , 1.4, 0.3]),
  array([4.8, 3.4, 1.9, 0.2]),
  array([5. , 3.6, 1.4, 0.2]),
  array([5.1, 3.3, 1.7, 0.5]),
  array([5.1, 3.7, 1.5, 0.4]),
  array([5.4, 3.9, 1.7, 0.4]),
  array([5.4, 3.9, 1.3, 0.4]),
  array([4.9, 3. , 1.4, 0.2]),
  array([4.7, 3.2, 1.6, 0.2]),
  array([4.9, 3.1, 1.5, 0.1]),
  array([5.2, 4.1, 1.5, 0.1]),
  array([5. , 3.5, 1.3, 0.3]),
  array([5.1, 3.8, 1.9, 0.4]),
  array([5.2, 3.5, 1.5, 0.2]),
  array([5.2, 3.4, 1.4, 0.2]),
  array([4.6, 3.1, 1.5, 0.2]),
  array([5.7, 3.8, 1.7, 0.3]),
  array([5.4, 3.7, 1.5, 0.2]),
  array([4.5, 2.3, 1.3, 0.3]),
  array([5. , 3.3, 1.4, 0.2]),
  array([5.5, 3.5, 1.3, 0.2]),
  array([5. , 3. , 1.6, 0.2]),
  array([4.3, 3. , 1.1, 0.1]),
  array([5.1, 3.8, 1.6, 0.2]),
  array([5.1, 3.8, 1.5, 0.3]),
  array([4.6, 3.6, 1. , 0.2]),
  array([5. , 3.4, 1.5, 0.2]),
  array([4.4, 3. , 1.3, 0.2]),
  array([5.3, 3.7, 1.5, 0.2]),
  array([4.6, 3.2, 1.4, 0.2]),
  a

In [104]:
gaussian_probability(2,3,1.414)

0.21971223238070992