In [20]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
# %matplotlib inline

from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split

from collections import Counter
import math

In [21]:
iris = load_iris()
df = pd.DataFrame(iris.data, columns=iris.feature_names)
df['label'] = iris.target
df.columns = ['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
data = np.array(df.iloc[:100, :])
X,y=data[:,:-1], data[:,-1]
X_train, X_test, y_train, y_test = train_test_split(X, y,
                                                    test_size=0.3,random_state=7)

In [22]:
X_test[0], y_test[0]

(array([4.9, 3.1, 1.5, 0.1]), 0.0)

In [23]:
X_train.sum()

851.5999999999999

In [24]:
def mean(x):
    return sum(x)/float(len(x))

def stdev(x):
    return np.sqrt(sum((x1-mean(x))**2 for x1 in x)/len(x))

def gaussian_probability(x,mean,stdev):
    exponent=np.exp(-(((x-mean)**2)/(2*stdev**2)))
    return 1/(np.sqrt(2*np.pi)*stdev)*exponent

In [34]:
a=[1,2,3,4,5]
gaussian_probability(3,3,1.414)

0.2821373977379298

In [26]:
train_model={}
for label in list(set(y_train)):
    train_model[label]=[]
for x_data,y_data in zip(X_train,y_train):
    train_model[y_data].append(x_data)

In [27]:
train_model

{0.0: [array([5.2, 3.5, 1.5, 0.2]),
  array([5.5, 4.2, 1.4, 0.2]),
  array([5. , 3.5, 1.6, 0.6]),
  array([5.5, 3.5, 1.3, 0.2]),
  array([5.1, 3.7, 1.5, 0.4]),
  array([5.2, 4.1, 1.5, 0.1]),
  array([4.5, 2.3, 1.3, 0.3]),
  array([5.4, 3.7, 1.5, 0.2]),
  array([5.2, 3.4, 1.4, 0.2]),
  array([4.7, 3.2, 1.6, 0.2]),
  array([5.4, 3.4, 1.5, 0.4]),
  array([5.4, 3.9, 1.3, 0.4]),
  array([4.9, 3. , 1.4, 0.2]),
  array([4.6, 3.1, 1.5, 0.2]),
  array([5. , 3.2, 1.2, 0.2]),
  array([4.9, 3.1, 1.5, 0.1]),
  array([5.1, 3.8, 1.6, 0.2]),
  array([5. , 3.6, 1.4, 0.2]),
  array([4.4, 3. , 1.3, 0.2]),
  array([4.9, 3.1, 1.5, 0.1]),
  array([4.8, 3.4, 1.9, 0.2]),
  array([5.1, 3.8, 1.5, 0.3]),
  array([4.6, 3.4, 1.4, 0.3]),
  array([5.1, 3.5, 1.4, 0.2]),
  array([5.1, 3.8, 1.9, 0.4]),
  array([5. , 3.4, 1.5, 0.2]),
  array([5.3, 3.7, 1.5, 0.2]),
  array([5.1, 3.4, 1.5, 0.2]),
  array([4.4, 2.9, 1.4, 0.2]),
  array([4.4, 3.2, 1.3, 0.2]),
  array([5.8, 4. , 1.2, 0.2]),
  array([5.1, 3.3, 1.7, 0.5]),
  a

In [28]:
train_model2={}
for label,data in train_model.items():
    train_model2[label]=[]
    for i in zip(*data):
        train_model2[label].append((mean(i),stdev(i)))
    
    

In [29]:
train_model2

{0.0: [(5.008823529411764, 0.33726202682852463),
  (3.4205882352941184, 0.38100440924166706),
  (1.4705882352941178, 0.15629800300689908),
  (0.24411764705882355, 0.10898239596264063)],
 1.0: [(5.86388888888889, 0.4859999872986838),
  (2.688888888888889, 0.2960647243216495),
  (4.219444444444445, 0.4886599842906246),
  (1.302777777777778, 0.2074797327600285)]}

In [30]:
train_model2

{0.0: [(5.008823529411764, 0.33726202682852463),
  (3.4205882352941184, 0.38100440924166706),
  (1.4705882352941178, 0.15629800300689908),
  (0.24411764705882355, 0.10898239596264063)],
 1.0: [(5.86388888888889, 0.4859999872986838),
  (2.688888888888889, 0.2960647243216495),
  (4.219444444444445, 0.4886599842906246),
  (1.302777777777778, 0.2074797327600285)]}

In [ ]:
predict([4.4,  3.2,  1.3,  0.2])

In [ ]:
test=[4.4,  3.2,  1.3,  0.2]

In [35]:
def predict(test):
    global train_model2
    probability={}
    for label,result in train_model2.items():
        probability[label]=1
        for i in range(len(test)):
            probability[label] *= gaussian_probability(test[i],
                                                       result[i][0],result[i][1])
    return sorted(probability.items(),key=lambda x:x[1])[-1][0]


In [38]:
probability=predict([4.4,  3.2,  1.3,  0.2])

In [39]:
probability

0.0

In [37]:
sorted(probability.items(),key=lambda x:x[1])[-1][0]

NameError: name 'probability' is not defined

In [ ]:
def score(x_test,y_test):
    right=0
    for x,y in zip(x_test,y_test):
        if predict(x_test[i]) ==y_test[i]:
            right+=1
    return right / float(len(y_test))
        

In [ ]:
score(X_test,y_test)

In [ ]:
from sklearn.naive_bayes import GaussianNB

In [ ]:
clf=GaussianNB()
clf.fit(X_train,y_train)

In [ ]:
clf.score(X_test,y_test)

In [ ]:
clf.predict([[4.4,3.2,1.3,0.2]])