### code by numpy

In [1]:
import numpy as np

In [2]:
a=(1,2,3)
b=(2,3,5)
for i in [a,b]:
    print(i[0])

1
2


In [2]:
def uwb_loc4(a,b,c,d,pr):
    A=np.zeros((3,3))
    B=np.zeros((3,1))
    l=[a,b,c,d]
    for i in range(3):
        for j in range(3):
            A[i,j]=(l[i+1][j]-l[i][j])*2
    for i in range(3):
        B[i,:]=(pr[i]**2-pr[i+1]**2+sum([j**2 for j in l[i+1]])-sum([j**2 for j in l[i]]))    
    print(A)
    print(B)
    print('---------')
    denominator=np.linalg.inv(np.matmul(A.transpose(),A))
    nominator=np.matmul(A.transpose(),B)
    print('denominator',denominator.shape)
    print('---------')
    print('nominator',nominator.shape)
    print('---------')
    print(np.matmul(denominator,nominator))
    

In [3]:
uwb_loc4((0,0,0),(5,0,0),(0,5,0),(0,0,5),(2,3,np.sqrt(29),np.sqrt(29)))

[[ 10.   0.   0.]
 [-10.  10.   0.]
 [  0. -10.  10.]]
[[ 20.]
 [-20.]
 [  0.]]
---------
denominator (3, 3)
---------
nominator (3, 1)
---------
[[2.]
 [0.]
 [0.]]


In [4]:
xyz=(3.59, 2.64, 1.12)
for i in [(5,0,3,25),(0,0,4.5),(0,6.5,3.25),(15,6.5,4.5)]:
    d=0
    for j in range(3):
        d+=(xyz[j]-i[j])**2
    print(np.sqrt(d))

3.534416500640523
5.593040318109641
5.685472715614772
12.510479607113389


In [5]:
A=np.array([[ 10. ,  0. ,  0.],
 [-10.,  10. ,  0.],
 [  0., -10. , 10.]])

In [6]:
B=np.array([[ 20.],
 [-20.],
 [  0.]])

In [7]:
np.matmul(A.transpose(),A)

array([[ 200., -100.,    0.],
       [-100.,  200., -100.],
       [   0., -100.,  100.]])

In [8]:
np.linalg.inv(np.matmul(A.transpose(),A))

array([[0.01, 0.01, 0.01],
       [0.01, 0.02, 0.02],
       [0.01, 0.02, 0.03]])

In [9]:
np.matmul(A.transpose(),A)

array([[ 200., -100.,    0.],
       [-100.,  200., -100.],
       [   0., -100.,  100.]])

In [10]:
uwb_loc4((5,0,3,25),(0,0,4.5),(0,6.5,3.25),(15,6.5,4.5),(3.55,5.61,5.69,12.51))

[[-10.    0.    3. ]
 [  0.   13.   -2.5]
 [ 30.    0.    2.5]]
[[-657.6196]
 [  31.6585]
 [ 110.5635]]
---------
denominator (3, 3)
---------
nominator (3, 1)
---------
[[  17.18034348]
 [ -28.70679264]
 [-161.93872174]]


In [11]:
x1=np.array([[ 0.00461248, -0.00261742, -0.01361059],
 [-0.00261742 , 0.0348542 ,  0.0581649 ],
 [-0.01361059 , 0.0581649  , 0.30245747]])
x2=np.array([[2473.27525 ],
 [ 102.890125],
 [-443.899075]])


In [12]:
np.matmul(x1,x2)

array([[  17.18035427],
       [ -28.70679242],
       [-161.93873271]])

In [13]:
np.matmul(A.transpose(),A)

array([[ 200., -100.,    0.],
       [-100.,  200., -100.],
       [   0., -100.,  100.]])

In [14]:
np.matmul(A.transpose(),B)

array([[ 400.],
       [-200.],
       [   0.]])

In [18]:
A

array([[ 10.,   0.,   0.],
       [-10.,  10.,   0.],
       [  0., -10.,  10.]])

In [26]:
l=[]
m=1
n=0
for i in range(3):
    if i !=m:
        for j in range(3):
            if j !=n:
                print(A[i][j])
                l.append(A[i][j])
-1**(m+n) * l[0]*l[3]-l[1]*l[2]

                
        
        

0.0
0.0
-10.0
10.0


0.0

In [57]:
def bs_m(m,n,A):
    l=[]
    for i in range(3):
        if i !=m:
            for j in range(3):
                if j !=n:
                    print(A[i][j])
                    l.append(A[i][j])
#   m+1,n+1
    return -1**(m+1+n+1) * (l[0]*l[3]-l[1]*l[2])

In [31]:
bs_m(2,2,A)

10.0
0.0
-10.0
10.0


-100.0

In [33]:
A_bs=np.zeros_like(A)
for i in range(3):
    for j in range(3):
        A_bs[i][j]=bs_m(i,j,A)
A_bs

10.0
0.0
-10.0
10.0
-10.0
0.0
0.0
10.0
-10.0
10.0
0.0
-10.0
0.0
0.0
-10.0
10.0
10.0
0.0
0.0
10.0
10.0
0.0
0.0
-10.0
0.0
0.0
10.0
0.0
10.0
0.0
-10.0
0.0
10.0
0.0
-10.0
10.0


array([[-100.,  100., -100.],
       [  -0., -100.,  100.],
       [  -0.,   -0., -100.]])

In [34]:
A[0][0]*A[1][1]*A[2][2]+A[0][1]*A[1][2]*A[2][0]+A[0][2]*A[1][0]*A[2][1]-(A[0][2]*A[1][1]*A[2][0]+A[1][2]*A[2][1]*A[0][0]+A[0][1]*A[1][0]*A[2][2])

1000.0

In [36]:
A_bs=np.zeros_like(A)
for i in range(3):
    for j in range(3):
        A_bs[i][j]=bs_m(i,j,np.matmul(A.transpose(),A))
A_bs

200.0
-100.0
-100.0
100.0
-100.0
-100.0
0.0
100.0
-100.0
200.0
0.0
-100.0
-100.0
0.0
-100.0
100.0
200.0
0.0
0.0
100.0
200.0
-100.0
0.0
-100.0
-100.0
0.0
200.0
-100.0
200.0
0.0
-100.0
-100.0
200.0
-100.0
-100.0
200.0


array([[-10000.,  10000., -10000.],
       [ 10000., -20000.,  20000.],
       [-10000.,  20000., -30000.]])

In [38]:
A_bs.transpose()/1000

array([[-10.,  10., -10.],
       [ 10., -20.,  20.],
       [-10.,  20., -30.]])

In [44]:
np.matmul(A_bs.transpose()/1000000.0 ,np.matmul(A.transpose(),B))

array([[-6.],
       [ 8.],
       [-8.]])

In [40]:
np.linalg.inv(np.matmul(A.transpose(),A))

array([[0.01, 0.01, 0.01],
       [0.01, 0.02, 0.02],
       [0.01, 0.02, 0.03]])

In [41]:
np.linalg.det(np.matmul(A.transpose(),A))

999999.9999999995

In [42]:
C=np.matmul(A.transpose(),A)

In [43]:
C[0][0]*C[1][1]*C[2][2]+C[0][1]*C[1][2]*C[2][0]+C[0][2]*C[1][0]*C[2][1]-(C[0][2]*C[1][1]*C[2][0]+C[1][2]*C[2][1]*C[0][0]+C[0][1]*C[1][0]*C[2][2])

1000000.0

In [45]:
A_bs.transpose()/1000000.0

array([[-0.01,  0.01, -0.01],
       [ 0.01, -0.02,  0.02],
       [-0.01,  0.02, -0.03]])

In [46]:
np.linalg.inv(np.matmul(A.transpose(),A))

array([[0.01, 0.01, 0.01],
       [0.01, 0.02, 0.02],
       [0.01, 0.02, 0.03]])

In [65]:
A_bs=np.zeros_like(A)
for i in range(3):
    for j in range(3):
        A_bs[i][j]=bs_m(i,j,np.matmul(A.transpose(),A))
A_bs.transpose()

200.0
-100.0
-100.0
100.0
-100.0
-100.0
0.0
100.0
-100.0
200.0
0.0
-100.0
-100.0
0.0
-100.0
100.0
200.0
0.0
0.0
100.0
200.0
-100.0
0.0
-100.0
-100.0
0.0
200.0
-100.0
200.0
0.0
-100.0
-100.0
200.0
-100.0
-100.0
200.0


array([[10000., 10000., 10000.],
       [10000., 20000., 20000.],
       [10000., 20000., 30000.]])

In [69]:
A_bs/1000000

array([[0.01, 0.01, 0.01],
       [0.01, 0.02, 0.02],
       [0.01, 0.02, 0.03]])

In [50]:
np.linalg.inv(np.matmul(A.transpose(),A))

array([[0.01, 0.01, 0.01],
       [0.01, 0.02, 0.02],
       [0.01, 0.02, 0.03]])

In [49]:
C

array([[ 200., -100.,    0.],
       [-100.,  200., -100.],
       [   0., -100.,  100.]])

In [64]:
bs_m(0,0,C)

200.0
-100.0
-100.0
100.0


10000.0