In [1]:
import numpy as np

In [8]:
b=np.array([[-1,2,-3],[4,-6,6]])

In [5]:
a=0
for i in [17,40,45]:
    a+=np.sqrt(i)
a

17.15586487845379

In [10]:
10.062275+0.86638438

10.92865938

In [9]:
b=np.array([[-1,2,-3],[4,-6,6]])
np.linalg.svd(b)

(array([[-0.3630926 ,  0.93175306],
        [ 0.93175306,  0.3630926 ]]),
 array([10.062275  ,  0.86638438]),
 array([[ 0.40647913, -0.62776097,  0.66384552],
        [ 0.60090806, -0.36363711, -0.71181286],
        [-0.6882472 , -0.6882472 , -0.22941573]]))

In [6]:
np.sqrt(17+40+45)

10.099504938362077