In [2]:
import torch 
import torchvision
from torch import nn,optim
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [3]:
data_csv=pd.read_csv('./data.csv',usecols=[1])

In [4]:
data_csv.shape

(145, 1)

In [5]:
data_csv=data_csv.dropna()
dataset=data_csv.apply(lambda x : x/(x.max()-x.min()))
dataset=dataset.values
dataset=dataset.astype('float32')

In [6]:
dataX,dataY=[],[]
for i in range(len(dataset)-2):
    dataX.append(dataset[i:i+2])
    dataY.append(dataset[i+2])

In [7]:
dataX[12:18]

[array([[0.22200772],
        [0.24324325]], dtype=float32), array([[0.24324325],
        [0.27220076]], dtype=float32), array([[0.27220076],
        [0.26061776]], dtype=float32), array([[0.26061776],
        [0.24131274]], dtype=float32), array([[0.24131274],
        [0.28764477]], dtype=float32), array([[0.28764477],
        [0.32818532]], dtype=float32)]

In [8]:
dataX[15]

array([[0.26061776],
       [0.24131274]], dtype=float32)

In [9]:
dataY[12:18]

[array([0.27220076], dtype=float32),
 array([0.26061776], dtype=float32),
 array([0.24131274], dtype=float32),
 array([0.28764477], dtype=float32),
 array([0.32818532], dtype=float32),
 array([0.32818532], dtype=float32)]

In [10]:
dataX[:10]

[array([[0.21621622],
        [0.22779922]], dtype=float32), array([[0.22779922],
        [0.25482625]], dtype=float32), array([[0.25482625],
        [0.24903475]], dtype=float32), array([[0.24903475],
        [0.23359074]], dtype=float32), array([[0.23359074],
        [0.26061776]], dtype=float32), array([[0.26061776],
        [0.2857143 ]], dtype=float32), array([[0.2857143],
        [0.2857143]], dtype=float32), array([[0.2857143 ],
        [0.26254827]], dtype=float32), array([[0.26254827],
        [0.22972973]], dtype=float32), array([[0.22972973],
        [0.2007722 ]], dtype=float32)]

In [11]:
dataY[:10]

[array([0.25482625], dtype=float32),
 array([0.24903475], dtype=float32),
 array([0.23359074], dtype=float32),
 array([0.26061776], dtype=float32),
 array([0.2857143], dtype=float32),
 array([0.2857143], dtype=float32),
 array([0.26254827], dtype=float32),
 array([0.22972973], dtype=float32),
 array([0.2007722], dtype=float32),
 array([0.22779922], dtype=float32)]

In [12]:
dataX,dataY=[],[]
for i in range(len(dataset)-2):
    dataX.append(dataset[i:i+2])
    dataY.append(dataset[i+2])

In [13]:
train_size=int(len(dataX)*0.7)
test_size=len(dataX)-train_size
train_X=dataX[:train_size]
train_Y=dataY[:train_size]
test_X=dataX[train_size:]
test_Y=dataY[train_size:]

In [14]:
train_x=torch.Tensor(train_X).reshape(-1,1,2)
train_y=torch.Tensor(train_Y).reshape(-1,1,1)
test_x=torch.Tensor(test_X).reshape(-1,1,2)
test_y=torch.Tensor(test_Y).reshape(-1,1,1)

In [15]:
np.random.shuffle(list(range(train_x.shape[0])))

In [16]:
net=nn.Linear(2,1)
loss=nn.MSELoss()
optimizer=optim.Adam(net.parameters(),lr=1e-2)
for e in range(1000):
    r_idxes=list(range(train_x.shape[0]))
    np.random.shuffle(r_idxes)
    for i in r_idxes:
        x=train_x[i]
        y=train_y[i]
        l=loss(net(x),y)
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
        if (e+1) % 100 ==0:
            print('epoch %d,loss : %.5f' % (e+1,l.item()))

epoch 100,loss : 0.00519
epoch 100,loss : 0.00508
epoch 100,loss : 0.00065
epoch 100,loss : 0.00502
epoch 100,loss : 0.00830
epoch 100,loss : 0.01125
epoch 100,loss : 0.00154
epoch 100,loss : 0.00125
epoch 100,loss : 0.00057
epoch 100,loss : 0.01866
epoch 100,loss : 0.00033
epoch 100,loss : 0.00006
epoch 100,loss : 0.00054
epoch 100,loss : 0.00020
epoch 100,loss : 0.00172
epoch 100,loss : 0.01071
epoch 100,loss : 0.00077
epoch 100,loss : 0.00000
epoch 100,loss : 0.00093
epoch 100,loss : 0.00153
epoch 100,loss : 0.00231
epoch 100,loss : 0.00024
epoch 100,loss : 0.00054
epoch 100,loss : 0.00472
epoch 100,loss : 0.00354
epoch 100,loss : 0.00002
epoch 100,loss : 0.00098
epoch 100,loss : 0.00101
epoch 100,loss : 0.00222
epoch 100,loss : 0.00405
epoch 100,loss : 0.00004
epoch 100,loss : 0.00348
epoch 100,loss : 0.00012
epoch 100,loss : 0.00002
epoch 100,loss : 0.00190
epoch 100,loss : 0.00038
epoch 100,loss : 0.00022
epoch 100,loss : 0.00080
epoch 100,loss : 0.00027
epoch 100,loss : 0.00193


epoch 500,loss : 0.00652
epoch 500,loss : 0.00139
epoch 500,loss : 0.00047
epoch 500,loss : 0.00492
epoch 500,loss : 0.00924
epoch 500,loss : 0.00127
epoch 500,loss : 0.00097
epoch 500,loss : 0.01208
epoch 500,loss : 0.00010
epoch 500,loss : 0.00968
epoch 500,loss : 0.00002
epoch 500,loss : 0.00264
epoch 500,loss : 0.00115
epoch 500,loss : 0.00005
epoch 500,loss : 0.00051
epoch 500,loss : 0.00074
epoch 500,loss : 0.00192
epoch 500,loss : 0.00049
epoch 500,loss : 0.00254
epoch 500,loss : 0.00049
epoch 500,loss : 0.00237
epoch 500,loss : 0.00043
epoch 500,loss : 0.00274
epoch 500,loss : 0.00045
epoch 500,loss : 0.00105
epoch 500,loss : 0.00107
epoch 500,loss : 0.00027
epoch 500,loss : 0.00045
epoch 500,loss : 0.00104
epoch 500,loss : 0.00081
epoch 500,loss : 0.01811
epoch 500,loss : 0.00695
epoch 500,loss : 0.00150
epoch 500,loss : 0.00221
epoch 500,loss : 0.00020
epoch 500,loss : 0.00002
epoch 500,loss : 0.00134
epoch 500,loss : 0.00284
epoch 500,loss : 0.00246
epoch 500,loss : 0.00000


epoch 900,loss : 0.00043
epoch 900,loss : 0.00017
epoch 900,loss : 0.00336
epoch 900,loss : 0.00083
epoch 900,loss : 0.00003
epoch 900,loss : 0.00035
epoch 900,loss : 0.00100
epoch 900,loss : 0.00014
epoch 900,loss : 0.00864
epoch 900,loss : 0.00001
epoch 900,loss : 0.00679
epoch 900,loss : 0.00019
epoch 900,loss : 0.00051
epoch 900,loss : 0.00994
epoch 900,loss : 0.00000
epoch 900,loss : 0.00060
epoch 900,loss : 0.00000
epoch 900,loss : 0.00250
epoch 900,loss : 0.00840
epoch 900,loss : 0.00281
epoch 900,loss : 0.01086
epoch 900,loss : 0.00300
epoch 900,loss : 0.00620
epoch 900,loss : 0.00436
epoch 900,loss : 0.00163
epoch 900,loss : 0.00036
epoch 900,loss : 0.00219
epoch 900,loss : 0.00071
epoch 900,loss : 0.00031
epoch 900,loss : 0.00000
epoch 900,loss : 0.00014
epoch 900,loss : 0.00093
epoch 900,loss : 0.00004
epoch 900,loss : 0.00373
epoch 900,loss : 0.00005
epoch 900,loss : 0.00201
epoch 900,loss : 0.01293
epoch 900,loss : 0.00010
epoch 900,loss : 0.00574
epoch 900,loss : 0.00005


In [18]:
train_x.shape

torch.Size([99, 1, 2])

In [23]:
trace_model=torch.jit.trace(net,train_x[0])
torch.jit.save(trace_model,r'F:\study\ml\rknn\models\test_net1.pt')

In [24]:
torch.save((train_x,train_y),r'F:\study\ml\rknn\models\data.csv')

In [25]:
train_x.shape

torch.Size([99, 1, 2])

In [26]:
train_y.shape

torch.Size([99, 1, 1])

In [36]:
torch.save(torch.cat((train_x,train_y),dim=2).reshape(-1,3),r'F:\study\ml\rknn\models\data.csv')

In [31]:
torch.stack([train_x,train_y])

RuntimeError: invalid argument 0: Sizes of tensors must match except in dimension 0. Got 2 and 1 in dimension 3 at c:\a\w\1\s\windows\pytorch\aten\src\th\generic/THTensorMoreMath.cpp:1307

In [37]:
import csv

In [40]:
fp=open(r'F:\study\ml\rknn\models\data.csv', 'w') 
writer = csv.writer(fp)
writer.writerow(['x1', 'x2','y'])
for i in torch.cat((train_x,train_y),dim=2).reshape(-1,3):
    writer.writerow([i[0],i[1],i[2]])

In [45]:
with open(r'F:\study\ml\rknn\models\data1.csv', 'w',newline='')  as f:
    writer=csv.writer(f)
    writer.writerow(['x1', 'x2','y'])
    for i in torch.cat((train_x,train_y),dim=2).reshape(-1,3):
        writer.writerow([i[0].item(),i[1].item(),i[2].item()])