In [6]:
import torch
import numpy as np
from torch import nn,optim

In [31]:
m=1000
n=2
true_w=[2,-3,4]
true_b=4.2
features=torch.Tensor(np.random.normal(0,1,(m,n)))
labels=true_w[0]*features[:,0]+true_w[1]*features[:,1]+true_b
labels+=torch.Tensor(np.random.normal(0,0.01,size=labels.size()))

In [32]:
import torch.utils.data as Data

In [33]:
batch_size=10
dataset=Data.TensorDataset(features,labels)
data_iter=Data.DataLoader(dataset,batch_size,shuffle=True)

In [ ]:
for X,y in data_iter:
    print(X,y)
    break

In [35]:
class LinearNet(nn.Module):
    def __init__(self,n_features):
        super().__init__()
        self.linear=nn.Linear(n_features,1)
    def forward(self,x):
        y=self.linear(x)
        return y

In [36]:
net=LinearNet(n)
print(net)

LinearNet(
  (linear): Linear(in_features=2, out_features=1, bias=True)
)


In [37]:
net[0]

TypeError: 'LinearNet' object does not support indexing

In [38]:
net=nn.Sequential(nn.Linear(n,1))

In [43]:
net[0]

Linear(in_features=2, out_features=1, bias=True)

In [39]:
from torch.nn import init

In [40]:
init.normal_(net[0].weight,mean=0,std=0.01)
init.constant_(net[0].bias,val=0)

Parameter containing:
tensor([0.], requires_grad=True)

In [41]:
loss=nn.MSELoss()
optimizer=optim.SGD(net.parameters(),lr=0.03)
print(optimizer)

SGD (
Parameter Group 0
    dampening: 0
    lr: 0.03
    momentum: 0
    nesterov: False
    weight_decay: 0
)


In [47]:
num_epochs=3
for e in range(1,num_epochs+1):
    for X,y in data_iter:
        l=loss(net(X),y.view(-1,1))
        optimizer.zero_grad()
        l.backward()
        optimizer.step()
    eloss=loss(net(features),labels).item()/m
    print('epoch %d,loss :%f' % (e,eloss))

epoch 1,loss :0.024064
epoch 2,loss :0.024069
epoch 3,loss :0.024060


In [45]:
dense=net[0]
print(true_w,dense.weight)
print(true_b,dense.bias)


[2, -3, 4] Parameter containing:
tensor([[ 2.0000, -2.9999]], requires_grad=True)
4.2 Parameter containing:
tensor([4.2000], requires_grad=True)


In [46]:
for p in net.parameters():
    print(p)

Parameter containing:
tensor([[ 2.0000, -2.9999]], requires_grad=True)
Parameter containing:
tensor([4.2000], requires_grad=True)
