In [79]:
import torch
import torchvision
import numpy as np
import torch.utils.data as Data
from torchvision import transforms

In [80]:
batch_size=256
mnist_train=torchvision.datasets.FashionMNIST(
    root='F:\study\ml\DataSet\FashionMNIST',train=True,
    download=True,transform=transforms.ToTensor())
mnist_test=torchvision.datasets.FashionMNIST(
    root='F:\study\ml\DataSet\FashionMNIST',train=False,
    download=True,transform=transforms.ToTensor())

In [81]:
train_iter=Data.DataLoader(mnist_train,batch_size,shuffle=True)
test_iter=Data.DataLoader(mnist_test,batch_size,shuffle=False)

In [82]:
def softmax(x):
    x_exp=x.exp()
    x_exp_sum=x_exp.sum(dim=1,keepdim=True)
    return x_exp/x_exp_sum
    

In [83]:
a=torch.Tensor([[1,2,3],[4,5,6]])
softmax(a)

tensor([[0.0900, 0.2447, 0.6652],
        [0.0900, 0.2447, 0.6652]])

In [84]:
def snet(x,w,b):
    return softmax(torch.mm(x.view(-1,784),w)+b)

In [85]:
def cross_entropy(y_hat,y):
    return-torch.log(y_hat.gather(1,y.view(-1,1)))

In [86]:
b=torch.Tensor([[0.1,0.2,0.7],[0.3,0.4,0.3]])
c=torch.tensor([1,2],dtype=torch.long)
print(softmax(b))
print(-torch.log(softmax(b)))
print(-torch.log(b))
cross_entropy(b,c)


tensor([[0.2546, 0.2814, 0.4640],
        [0.3220, 0.3559, 0.3220]])
tensor([[1.3679, 1.2679, 0.7679],
        [1.1331, 1.0331, 1.1331]])
tensor([[2.3026, 1.6094, 0.3567],
        [1.2040, 0.9163, 1.2040]])


tensor([[1.6094],
        [1.2040]])

In [87]:
def sgd(params,lr,batch_size):
    for p in params:
        p.data -= lr*p.grad/batch_size

In [88]:
def evaluate_acc(data_iter):
    acc,n=0,0
    for x,y in data_iter:
        acc+=(snet(x,w,b).argmax(dim=1)==y).sum().item()
        n+=len(y)
    return acc/n

In [89]:
a=torch.Tensor([1,2,3])
b=torch.Tensor([1,2,4])
print((a==b).sum())
print((a==b).sum()/3)
print((a==b).float().sum()/3)

tensor(2)
tensor(0)
tensor(0.6667)


In [94]:
w=torch.Tensor(np.random.normal(0,0.01,(784,10)))
b=torch.zeros((1,10),dtype=torch.float32)
w.requires_grad_(requires_grad=True)
b.requires_grad_(requires_grad=True)

tensor([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]], requires_grad=True)

In [96]:
lr=0.03
params=[w,b]
loss=cross_entropy
for i in range(5):
    train_l,train_acc,test_acc,n=0,0,0,0
    for x,y in train_iter:
        y_hat=snet(x,w,b)
        l=loss(y_hat,y).sum()
#         l=loss(y_hat,y)
        print(l)
        
        if params[0].grad is not None:
            for p in params:
                p.grad.data.zero_()
        l.backward()
        sgd(params,lr,batch_size)
        train_l+=l
        train_acc+=(snet(x,w,b).argmax(dim=1)==y).sum().item()
        n+=len(y)
    test_acc=evaluate_acc(test_iter)
    print('eposh %d,loss %.3f,train acc %.3f,test acc %.3f' % (
    i+1,train_l/n,train_acc/n,test_acc))

tensor(598.2317, grad_fn=<SumBackward0>)
tensor(572.8186, grad_fn=<SumBackward0>)
tensor(560.9443, grad_fn=<SumBackward0>)
tensor(542.8265, grad_fn=<SumBackward0>)
tensor(533.8809, grad_fn=<SumBackward0>)
tensor(522.6052, grad_fn=<SumBackward0>)
tensor(511.0300, grad_fn=<SumBackward0>)
tensor(501.8399, grad_fn=<SumBackward0>)
tensor(484.6569, grad_fn=<SumBackward0>)
tensor(481.0330, grad_fn=<SumBackward0>)
tensor(469.5710, grad_fn=<SumBackward0>)
tensor(461.1483, grad_fn=<SumBackward0>)
tensor(445.2183, grad_fn=<SumBackward0>)
tensor(441.7003, grad_fn=<SumBackward0>)
tensor(430.4334, grad_fn=<SumBackward0>)
tensor(427.1391, grad_fn=<SumBackward0>)
tensor(409.1255, grad_fn=<SumBackward0>)
tensor(418.5605, grad_fn=<SumBackward0>)
tensor(408.7454, grad_fn=<SumBackward0>)
tensor(394.6254, grad_fn=<SumBackward0>)
tensor(387.5623, grad_fn=<SumBackward0>)
tensor(390.2661, grad_fn=<SumBackward0>)
tensor(378.2486, grad_fn=<SumBackward0>)
tensor(369.3729, grad_fn=<SumBackward0>)
tensor(373.2664,

tensor(196.3186, grad_fn=<SumBackward0>)
tensor(206.7935, grad_fn=<SumBackward0>)
tensor(210.0393, grad_fn=<SumBackward0>)
tensor(218.8971, grad_fn=<SumBackward0>)
tensor(194.8703, grad_fn=<SumBackward0>)
tensor(211.8431, grad_fn=<SumBackward0>)
tensor(200.4200, grad_fn=<SumBackward0>)
tensor(188.0332, grad_fn=<SumBackward0>)
tensor(200.4467, grad_fn=<SumBackward0>)
tensor(196.2610, grad_fn=<SumBackward0>)
tensor(210.6694, grad_fn=<SumBackward0>)
tensor(193.6450, grad_fn=<SumBackward0>)
tensor(215.8178, grad_fn=<SumBackward0>)
tensor(191.7140, grad_fn=<SumBackward0>)
tensor(183.3051, grad_fn=<SumBackward0>)
tensor(204.2219, grad_fn=<SumBackward0>)
tensor(195.2245, grad_fn=<SumBackward0>)
tensor(216.6426, grad_fn=<SumBackward0>)
tensor(203.3490, grad_fn=<SumBackward0>)
tensor(206.7222, grad_fn=<SumBackward0>)
tensor(196.7813, grad_fn=<SumBackward0>)
tensor(213.2253, grad_fn=<SumBackward0>)
tensor(200.0565, grad_fn=<SumBackward0>)
tensor(188.0252, grad_fn=<SumBackward0>)
tensor(196.4635,

tensor(176.1050, grad_fn=<SumBackward0>)
tensor(180.7922, grad_fn=<SumBackward0>)
tensor(174.2873, grad_fn=<SumBackward0>)
tensor(159.6383, grad_fn=<SumBackward0>)
tensor(158.1744, grad_fn=<SumBackward0>)
tensor(172.9765, grad_fn=<SumBackward0>)
tensor(166.1586, grad_fn=<SumBackward0>)
tensor(173.2529, grad_fn=<SumBackward0>)
tensor(169.7746, grad_fn=<SumBackward0>)
tensor(166.8617, grad_fn=<SumBackward0>)
tensor(175.7401, grad_fn=<SumBackward0>)
tensor(164.3856, grad_fn=<SumBackward0>)
tensor(190.5222, grad_fn=<SumBackward0>)
tensor(175.5964, grad_fn=<SumBackward0>)
tensor(200.3712, grad_fn=<SumBackward0>)
tensor(163.7990, grad_fn=<SumBackward0>)
tensor(171.1007, grad_fn=<SumBackward0>)
tensor(148.1798, grad_fn=<SumBackward0>)
tensor(156.4046, grad_fn=<SumBackward0>)
tensor(180.0894, grad_fn=<SumBackward0>)
tensor(164.1069, grad_fn=<SumBackward0>)
tensor(193.0854, grad_fn=<SumBackward0>)
tensor(154.9213, grad_fn=<SumBackward0>)
tensor(165.8654, grad_fn=<SumBackward0>)
tensor(173.0404,

tensor(161.5345, grad_fn=<SumBackward0>)
tensor(158.0530, grad_fn=<SumBackward0>)
tensor(168.7957, grad_fn=<SumBackward0>)
tensor(144.8743, grad_fn=<SumBackward0>)
tensor(166.0776, grad_fn=<SumBackward0>)
tensor(160.6336, grad_fn=<SumBackward0>)
tensor(160.9912, grad_fn=<SumBackward0>)
tensor(168.9560, grad_fn=<SumBackward0>)
tensor(170.2424, grad_fn=<SumBackward0>)
tensor(178.8454, grad_fn=<SumBackward0>)
tensor(153.7982, grad_fn=<SumBackward0>)
tensor(174.8477, grad_fn=<SumBackward0>)
tensor(165.7687, grad_fn=<SumBackward0>)
tensor(156.7197, grad_fn=<SumBackward0>)
tensor(167.8412, grad_fn=<SumBackward0>)
tensor(143.6218, grad_fn=<SumBackward0>)
tensor(157.1085, grad_fn=<SumBackward0>)
tensor(182.8589, grad_fn=<SumBackward0>)
tensor(155.1260, grad_fn=<SumBackward0>)
tensor(155.4325, grad_fn=<SumBackward0>)
tensor(168.7298, grad_fn=<SumBackward0>)
tensor(161.8587, grad_fn=<SumBackward0>)
tensor(150.8108, grad_fn=<SumBackward0>)
tensor(157.9588, grad_fn=<SumBackward0>)
tensor(155.6381,

tensor(154.7259, grad_fn=<SumBackward0>)
tensor(163.6895, grad_fn=<SumBackward0>)
tensor(150.3272, grad_fn=<SumBackward0>)
tensor(164.6273, grad_fn=<SumBackward0>)
tensor(146.4695, grad_fn=<SumBackward0>)
tensor(168.3012, grad_fn=<SumBackward0>)
tensor(151.3784, grad_fn=<SumBackward0>)
tensor(150.1961, grad_fn=<SumBackward0>)
tensor(169.5608, grad_fn=<SumBackward0>)
tensor(157.1655, grad_fn=<SumBackward0>)
tensor(134.6093, grad_fn=<SumBackward0>)
tensor(145.0035, grad_fn=<SumBackward0>)
tensor(150.6467, grad_fn=<SumBackward0>)
tensor(161.0357, grad_fn=<SumBackward0>)
tensor(152.8644, grad_fn=<SumBackward0>)
tensor(169.6237, grad_fn=<SumBackward0>)
tensor(150.7647, grad_fn=<SumBackward0>)
tensor(136.3128, grad_fn=<SumBackward0>)
tensor(158.0871, grad_fn=<SumBackward0>)
tensor(183.4711, grad_fn=<SumBackward0>)
tensor(137.9569, grad_fn=<SumBackward0>)
tensor(141.8982, grad_fn=<SumBackward0>)
tensor(149.7134, grad_fn=<SumBackward0>)
tensor(138.6295, grad_fn=<SumBackward0>)
tensor(160.1552,

tensor(125.6219, grad_fn=<SumBackward0>)
tensor(152.4509, grad_fn=<SumBackward0>)
tensor(144.2693, grad_fn=<SumBackward0>)
tensor(167.1313, grad_fn=<SumBackward0>)
tensor(144.2758, grad_fn=<SumBackward0>)
tensor(163.8305, grad_fn=<SumBackward0>)
tensor(150.6153, grad_fn=<SumBackward0>)
tensor(154.3255, grad_fn=<SumBackward0>)
tensor(146.5517, grad_fn=<SumBackward0>)
tensor(155.4682, grad_fn=<SumBackward0>)
tensor(155.9777, grad_fn=<SumBackward0>)
tensor(155.9561, grad_fn=<SumBackward0>)
tensor(149.6628, grad_fn=<SumBackward0>)
tensor(156.7791, grad_fn=<SumBackward0>)
tensor(124.6231, grad_fn=<SumBackward0>)
tensor(142.7351, grad_fn=<SumBackward0>)
tensor(137.0774, grad_fn=<SumBackward0>)
tensor(125.4454, grad_fn=<SumBackward0>)
tensor(140.5864, grad_fn=<SumBackward0>)
tensor(156.1161, grad_fn=<SumBackward0>)
tensor(144.7397, grad_fn=<SumBackward0>)
tensor(139.7999, grad_fn=<SumBackward0>)
tensor(157.3138, grad_fn=<SumBackward0>)
tensor(132.7900, grad_fn=<SumBackward0>)
tensor(136.3326,