In [1]:
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import train_test_split
import matplotlib as mpl
import matplotlib.colors
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [3]:
data=np.loadtxt(r'F:\study\ml\DoctorZou\18EMII\18.HeightWeight.csv',
               dtype=np.float,delimiter=',',skiprows=1)

In [5]:
y,x=np.split(data,[1,],axis=1)
x,x_test,y,y_test=train_test_split(x,y,test_size=0.4,random_state=0)
gmm=GaussianMixture(n_components=2,covariance_type='full',random_state=0)
x_min=np.min(x,axis=0)
x_max=np.max(x,axis=0)
gmm.fit(x)

GaussianMixture(covariance_type='full', init_params='kmeans', max_iter=100,
        means_init=None, n_components=2, n_init=1, precisions_init=None,
        random_state=0, reg_covar=1e-06, tol=0.001, verbose=0,
        verbose_interval=10, warm_start=False, weights_init=None)

In [7]:
print('mean :\n ',gmm.means_)
print('covariances :\n ',gmm.covariances_)

mean :
  [[ 160.13983374   55.93370575]
 [ 173.50243688   65.03359308]]
covariances :
  [[[  18.82128194   12.30370549]
  [  12.30370549   31.23596113]]

 [[  23.22794989   28.48688647]
  [  28.48688647  105.81824734]]]


In [8]:
y_hat=gmm.predict(x)
y_test_hat=gmm.predict(x_test)

In [9]:
change=(gmm.means_[0][0]>gmm.means_[1][0])
if change:
    z=y_hat==0
    y_hat[z]=1
    y_hat[~z]=0
    z=y_test_hat==0
    y_test_hat[z]=1
    y_test_hat[z]=0

In [13]:
acc=np.mean(y_hat.ravel()==y.ravel())
acc_test=np.mean(y_test_hat.ravel()==y_test.ravel())
acc_str='train set acc: %.2f%%' % (acc * 100)
acc_test_str='test set acc: %.2f%%' % (acc_test * 100)

In [23]:
print(acc_str)
print(acc_test_str)

train set acc: 77.94%
test set acc: 82.61%


In [14]:
cm_light=mpl.colors.ListedColormap(['#FF8080','#77E0A0'])
cm_dark=mpl.colors.ListedColormap(['r','g'])
x1_min,x1_max=x[:,0].min(),x[:,0].max()
x2_min,x2_max=x[:,1].min(),x[:,1].max()
x1,x2=np.mgrid[x1_min:x1_max:500j,x2_min:x2_max:500j]
grid_test=np.stack((x1.flat,x2.flat),axis=1)
grid_hat=gmm.predict(grid_test)
grid_hat=grid_hat.reshape(x1.shape)

In [15]:
if change:
    z=grid_hat==0
    grid_hat[z]=1
    grid_hat[~z]=0

In [22]:
plt.figure(figsize=(8,6))
plt.pcolormesh(x1,x2,grid_hat,cmap=cm_light)
plt.scatter(x[:,0],x[:,1],s=50,c=y[:,0],marker='o',cmap=cm_dark,edgecolors='k')
plt.scatter(x_test[:,0],x_test[:,1],s=50,marker='^',c=y_test[:,0],cmap=cm_dark)
p=gmm.predict_proba(grid_test)
p=p[:,0].reshape(x1.shape)
CS=plt.contour(x1,x2,p,levels=(0.2,0.5,0.8),color=list('rgb'),linewidths=2)
plt.clabel(CS,fontsize=15,fmt='%.1f',inline=True)
ax1_min, ax1_max, ax2_min, ax2_max = plt.axis()
xx = 0.9*ax1_min + 0.1*ax1_max
yy = 0.1*ax2_min + 0.9*ax2_max
plt.text(xx, yy, acc_str, fontsize=18)
yy = 0.15*ax2_min + 0.85*ax2_max
plt.text(xx, yy, acc_test_str, fontsize=18)
plt.xlim((x1_min, x1_max))
plt.ylim((x2_min, x2_max))
plt.xlabel(u'身高(cm)', fontsize='large')
plt.ylabel(u'体重(kg)', fontsize='large')
plt.title(u'EM算法估算GMM的参数', fontsize=20)
plt.grid()
plt.show()

D:\ProgramData\Anaconda3\lib\site-packages\matplotlib\contour.py:967: UserWarning: The following kwargs were not used by contour: 'color'
  s)


In [17]:
y.shape

(68, 1)

In [20]:
y[:,0]

array([ 0.,  1.,  1.,  0.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,
        0.,  0.,  1.,  1.,  0.,  0.,  0.,  0.,  0.,  0.,  0.,  1.,  1.,
        1.,  1.,  0.,  1.,  0.,  1.,  0.,  0.,  0.,  1.,  1.,  1.,  1.,
        1.,  0.,  1.,  1.,  1.,  0.,  0.,  1.,  1.,  0.,  1.,  0.,  1.,
        1.,  0.,  1.,  1.,  1.,  1.,  0.,  0.,  1.,  0.,  1.,  1.,  1.,
        1.,  0.,  0.])