In [1]:
import numpy as np
from sklearn.mixture import GaussianMixture
from sklearn.model_selection import train_test_split
import matplotlib as mpl
import matplotlib.colors
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [3]:
def expand(a,b):
    d=(b-a)*0.05
    return a-d,b+d

In [8]:
data = np.loadtxt(r'F:\study\ml\DoctorZou\18EMII\18.HeightWeight.csv',
               delimiter=',',
               dtype=np.float,
               skiprows=1)

In [9]:
y,x=np.split(data,[1,],axis=1)
x,x_test,y,y_test=train_test_split(x,y,test_size=0.4,random_state=0)

In [11]:
gmm=GaussianMixture(n_components=2,covariance_type='full',random_state=0)

In [13]:
x_min=np.min(x,axis=0)
x_max=np.max(x,axis=0)

In [14]:
gmm.fit(x)
print('mean : ',gmm.means_)
print('covariance : ',gmm.covariances_)

mean :  [[ 160.13983374   55.93370575]
 [ 173.50243688   65.03359308]]
covariance :  [[[  18.82128194   12.30370549]
  [  12.30370549   31.23596113]]

 [[  23.22794989   28.48688647]
  [  28.48688647  105.81824734]]]


In [16]:
y_hat=gmm.predict(x)
y_test_hat=gmm.predict(x_test)

In [17]:
change=(gmm.means_[0][0] > gmm.means_[1][0])
if change:
    z=y_hat==0
    y_hat[z]=1
    y_hat[~z]=0
    z=y_test_hat==0
    y_test_hat[z]=1
    y_test_hat[~z]=0

In [24]:
np.array([[1,2,3],[2,3,4]])==np.array([[1,2,4],[2,3,5]])

array([[ True,  True, False],
       [ True,  True, False]], dtype=bool)

In [28]:
acc=np.mean(y.ravel()==y_hat.ravel())
acc_test=np.mean(y_test.ravel()==y_test_hat.ravel())
acc_str='train set acc : %.2f%%' % acc
acc_test_str='test set acc : %.2f%%' % acc_test
print(acc_str,'\n',acc_test_str)

train set acc : 0.78% 
 test set acc : 0.83%


In [42]:
['abc']

['abc']

In [39]:
list('abc')

['a', 'b', 'c']

In [43]:
cm_light=mpl.colors.ListedColormap(['#FF8080', '#77E0A0'])
cm_dark=mpl.colors.ListedColormap(list('rg'))
x1_min,x1_max=x[:,0].min(),x[:,0].max()
x2_max,x2_min=x[:,1].min(),x[:,1].max()
x1_min,x1_max=expand(x1_min,x1_max)
x2_min,x2_max=expand(x2_min,x2_max)
x1,x2=np.mgrid[x1_min:x1_max:500j,x2_min:x2_max:500j]
grid_test=np.stack((x1.flat,x2.flat),axis=1)
grid_hat=gmm.predict(grid_test)
grid_hat=grid_hat.reshape(x1.shape)

In [45]:
y.shape

(68, 1)

In [61]:
plt.figure(figsize=(8,6),facecolor='w')
plt.pcolormesh(x1,x2,grid_hat,cmap=cm_light)
plt.scatter(x[:,0],x[:,1],s=50,c=y.ravel(),marker='o',cmap=cm_dark,edgecolors='k')
plt.scatter(x_test[:,0],x_test[:,1],s=60,c=y_test.ravel(),cmap=cm_dark,edgecolors='k')

p=gmm.predict_proba(grid_test)
p=p[:,0].reshape(x1.shape)
CS=plt.contour(x1,x2,p,levels=(0.2,0.5,0.8),colors=list('rgb'),linewidths=2)
plt.clabel(CS,fontsize=15,fmt='%.1f',inline=True)
ax1_min,ax1_max,ax2_min,ax2_max=plt.axis()
xx=0.9*ax1_min+0.1*ax1_max
yy=0.1*ax2_min+0.9*ax2_max
# print(ax1_min,ax1_max,ax2_min,ax2_max)
plt.text(xx,yy,acc_str,fontsize=18)
yy=0.15*ax2_min+0.85*ax2_max
plt.text(xx,yy,acc_test_str,fontsize=18)
plt.xlim((x1_min,x1_max))
plt.ylim((x2_min,x2_max))
plt.xlabel('height(cm)',fontsize=20)
plt.ylabel('weight(kg)',fontsize=20)
# plt.show()

Text(0,0.5,'weight(kg)')

In [48]:
gmm.predict_proba(grid_test)

array([[  4.00913470e-06,   9.99995991e-01],
       [  4.62203715e-06,   9.99995378e-01],
       [  5.32668411e-06,   9.99994673e-01],
       ..., 
       [  2.19927891e-10,   1.00000000e+00],
       [  2.01316864e-10,   1.00000000e+00],
       [  1.84213208e-10,   1.00000000e+00]])