In [1]:
import numpy as np
from scipy.stats import multivariate_normal
from sklearn.mixture import GaussianMixture
from mpl_toolkits.mplot3d import Axes3D
import matplotlib as mpl
import matplotlib.pyplot as plt
from sklearn.metrics.pairwise import pairwise_distances_argmin

In [6]:
np.random.seed(0)
mu1_fact=(0,0,0)
cov_fact=np.identity(3)
data1=np.random.multivariate_normal(mu1_fact,cov_fact,400)
mu2_fact=(3,3,3)
data2=np.random.multivariate_normal(mu2_fact,cov_fact,100)
data=np.vstack((data1,data2))
y=np.array([0]*400+[1]*100)

In [18]:
iter_num=100
n,d=data.shape
pi=0.5
mu1=np.min(data,axis=0)
mu2=np.max(data,axis=0)
sigma1=np.identity(d)
sigma2=np.identity(d)

In [21]:
for i in range(iter_num):
    norm1=multivariate_normal(mu1,sigma1)
    norm2=multivariate_normal(mu2,sigma2)
    tau1=pi*norm1.pdf(data)
    tau2=(1-pi)*norm2.pdf(data)
    gamma=tau1/(tau1+tau2)
    
    mu1=np.dot(gamma,data)/np.sum(gamma)
    mu2=np.dot(1-gamma,data)/np.sum(1-gamma)
    sigma1=np.dot(gamma*(data-mu1).T,data-mu1)/np.sum(gamma)
    sigma2=np.dot((1-gamma)*(data-mu2).T,data-mu2)/np.sum(1-gamma)
    p1=np.sum(gamma)/n
    
print('cate prob / example :',pi)
print('mean : \n',mu1,mu2)
print('cov : \n',sigma1,'\n',sigma2)

    
    

cate prob / example : 0.797580413292
mean : 
 [-0.00054615 -0.00499444 -0.07475788] [ 2.93143307  2.98501664  2.98944777]
cov : 
 [[ 0.92841225 -0.03948323  0.01723521]
 [-0.03948323  1.05425524 -0.04818367]
 [ 0.01723521 -0.04818367  0.86781276]] 
 [[ 1.05503164 -0.06960455 -0.01908567]
 [-0.06960455  0.99677278  0.01410168]
 [-0.01908567  0.01410168  0.91006651]]
