In [ ]:
import numpy as np

In [8]:
Q = [1, 2, 3]
V = ['红', '白']
A = [[0.5, 0.2, 0.3], [0.3, 0.5, 0.2], [0.2, 0.3, 0.5]]
B = [[0.5, 0.5], [0.4, 0.6], [0.7, 0.3]]
O = ['红', '白', '红', '红', '白', '红', '白', '白']
PI = [[0.2, 0.3, 0.5]]

In [ ]:
                betas[i][t-1]=np.dot(np.multiply([a for a in A[i]], 
                                            [b[indexOfO] for b in B]),
                                     [beta for beta in betas[:,t]])

In [136]:
class HiddenMarkov:
    def forward(self,Q,V,A,B,O,PI):
        '''
        Q:状态集合
        V:观测集合
        A:状态转移概率矩阵
        B:观测概率矩阵
        O:观测序列
        PI:初始参数
        '''
        N=len(Q)  #状态集合,就是箱子
        M=len(O)  # 观测序列
        alphas=np.zeros((N,M))
        T=M ### T=观测序列的长度
        
        for t in range(T):
            for i in range(N):
                indexOfO=V.index(O[t])
                if t==0:
                    alphas[i][t]=PI[t][i]*B[i][indexOfO]
                else:
                    alphas[i][t]=np.dot([alpha[t-1] for alpha in alphas],\
                                       [a[i] for a in A]) * B[i][indexOfO]
        print(alphas)
        P=np.sum([alpha[M-1] for alpha in alphas])
        print(P)
        
        
    def backward(self,Q,V,A,B,O,PI):
        '''
        Q:状态集合
        V:观测集合
        A:状态转移概率矩阵
        B:观测概率矩阵
        O:观测序列
        PI:初始参数
        '''
        M=len(Q)
        N=len(O)
        T=N
        betas=np.ones((M,N))
        
        for i in range(M):
            print('betas[%d][%d] = %d' % (i,N-1,betas[i][N-1]))
        
        for t in range(T-1,0,-1):
            indexOfO=V.index(O[t])
            for i in range(M):
#                 print('---------A-----------')
#                 print([np.float64(a) for a in A[i]])
#                 print('---------B-----------')
#                 print( [np.float64(b[indexOfO]) for b in B])
#                 print('---------beta-----------')
#                 print([beta for beta in betas[:,t]])
                print('-----------{}--{}------------'.format(t,i))
                print('-------part11----------')
                print([a for a in A[i]])
                print('-------part12----------')
                print([b[indexOfO] for b in B])
                print('---------part2------------')
                print([beta for beta in betas[:,t]])
                print('-------------------------')
                      
                betas[i][t-1]=np.dot(np.multiply([a for a in A[i]], 
                                            [b[indexOfO] for b in B]),
                                     [beta for beta in betas[:,t]])
        
        P=0
        indexOfO2=V.index(O[0])
        for i in range(M):
            P+=PI[0][i]*B[i][indexOfO2]*betas[i][0]
        print(betas)
        return P
        

In [137]:
HMM = HiddenMarkov()

In [140]:
HMM.forward(Q,V,A,B,O,PI)

[[0.1        0.078      0.04302    0.0218541  0.01146343 0.00576595
  0.0028617  0.00141148]
 [0.12       0.111      0.036684   0.0174942  0.01394714 0.00467612
  0.00338859 0.00169797]
 [0.35       0.0687     0.055965   0.03375771 0.00808018 0.00718798
  0.0018777  0.00074252]]
0.0038519735794910995


In [139]:
HMM.backward(Q,V,A,B,O,PI)

betas[0][7] = 1
betas[1][7] = 1
betas[2][7] = 1
-----------7--0------------
-------part11----------
[0.5, 0.2, 0.3]
-------part12----------
[0.5, 0.6, 0.3]
---------part2------------
[1.0, 1.0, 1.0]
-------------------------
-----------7--1------------
-------part11----------
[0.3, 0.5, 0.2]
-------part12----------
[0.5, 0.6, 0.3]
---------part2------------
[1.0, 1.0, 1.0]
-------------------------
-----------7--2------------
-------part11----------
[0.2, 0.3, 0.5]
-------part12----------
[0.5, 0.6, 0.3]
---------part2------------
[1.0, 1.0, 1.0]
-------------------------
-----------6--0------------
-------part11----------
[0.5, 0.2, 0.3]
-------part12----------
[0.5, 0.6, 0.3]
---------part2------------
[0.45999999999999996, 0.51, 0.43000000000000005]
-------------------------
-----------6--1------------
-------part11----------
[0.3, 0.5, 0.2]
-------part12----------
[0.5, 0.6, 0.3]
---------part2------------
[0.45999999999999996, 0.51, 0.43000000000000005]
-------------------------
-

0.0038519735794910986

In [24]:
A

[[0.5, 0.2, 0.3], [0.3, 0.5, 0.2], [0.2, 0.3, 0.5]]

In [90]:
a=[1,2,3]
b=[2,2,2]
np.multiply(a,b)

array([2, 4, 6])

In [147]:
Q = [1, 2, 3]
V = ['红', '白']
A = [[0.5, 0.2, 0.3], [0.3, 0.5, 0.2], [0.2, 0.3, 0.5]]
B = [[0.5, 0.5], [0.4, 0.6], [0.7, 0.3]]
# O = ['红', '白', '红', '红', '白', '红', '白', '白']
O = ['红', '白', '红', '白']    #习题10.1的例子
PI = [[0.2, 0.4, 0.4]]

In [142]:
A

[[0.5, 0.2, 0.3], [0.3, 0.5, 0.2], [0.2, 0.3, 0.5]]

In [143]:
B

[[0.5, 0.5], [0.4, 0.6], [0.7, 0.3]]

In [144]:
0.1*0.2,0.16*0.5,0.28*0.3

(0.020000000000000004, 0.08, 0.084)

In [145]:
0.084*0.6

0.0504

In [161]:
class HiddenMarkov2:
    def viterbi(self,Q,V,A,B,O,PI):
        '''
        Q:状态集合
        V:观测集合
        A:状态转移概率矩阵
        B:观测概率矩阵
        O:观测序列
        PI:初始参数
        '''        
        M=len(Q)
        N=len(O)
        deltas=np.zeros((M,N))
        psis=np.zeros((M,N))
        I=np.zeros((1,N))
        for t in range(N):
            realT=t+1
            for i in range(M):
                indexOfO=V.index(O[t])
                realI=i+1
                if t==0:
                    deltas[i][t]=PI[0][i] * B[i][indexOfO]
                    psis[i][t] =0
                    print('delta[%d][0] = pi[%d] * B[%d][%d]=%.2f * %.2f=%.2f' \
                          % (i,i,i,indexOfO,PI[0][i],B[i][indexOfO],PI[0][i] * B[i][indexOfO]))
                    print('psis[%d][0]=0' % (realI))
                else:
                    deltas[i][t]=np.max(np.multiply([delta[t-1] for delta in deltas],\
                                                   [a[i] for a in A]))* B[i][indexOfO]
                    psis[i][t]=np.argmax(np.multiply([delta[t-1] for delta in deltas],\
                                                    [a[i] for a in A]))
                    
            print(deltas)
            print(psis)
            I[0][N-1]=np.argmax([delta[N-1] for delta in deltas])
            print('i%d=argmax[deltaT(i)]=%d' % (N, I[0][N-1]))
            for t in range(N-2,-1,-1):
                I[0][t]=psis[int(I[0][t+1])][t+1]
                print('i%d=psis%d(i%d)=%d' % (t+1, t+2, t+2, I[0][t]+1))
            print(I)


In [162]:
HMM2=HiddenMarkov2()
HMM2.viterbi(Q,V,A,B,O,PI)

delta[0][0] = pi[0] * B[0][0]=0.20 * 0.50=0.10
psis[1][0]=0
delta[1][0] = pi[1] * B[1][0]=0.40 * 0.40=0.16
psis[2][0]=0
delta[2][0] = pi[2] * B[2][0]=0.40 * 0.70=0.28
psis[3][0]=0
[[0.1  0.   0.   0.  ]
 [0.16 0.   0.   0.  ]
 [0.28 0.   0.   0.  ]]
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
i4=argmax[deltaT(i)]=0
i3=psis4(i4)=1
i2=psis3(i3)=1
i1=psis2(i2)=1
[[0. 0. 0. 0.]]
[[0.1    0.028  0.     0.    ]
 [0.16   0.0504 0.     0.    ]
 [0.28   0.042  0.     0.    ]]
[[0. 2. 0. 0.]
 [0. 2. 0. 0.]
 [0. 2. 0. 0.]]
i4=argmax[deltaT(i)]=0
i3=psis4(i4)=1
i2=psis3(i3)=1
i1=psis2(i2)=3
[[2. 0. 0. 0.]]
[[0.1     0.028   0.00756 0.     ]
 [0.16    0.0504  0.01008 0.     ]
 [0.28    0.042   0.0147  0.     ]]
[[0. 2. 1. 0.]
 [0. 2. 1. 0.]
 [0. 2. 2. 0.]]
i4=argmax[deltaT(i)]=0
i3=psis4(i4)=1
i2=psis3(i3)=2
i1=psis2(i2)=3
[[2. 1. 0. 0.]]
[[0.1      0.028    0.00756  0.00189 ]
 [0.16     0.0504   0.01008  0.003024]
 [0.28     0.042    0.0147   0.002205]]
[[0. 2. 1. 0.]
 [0. 2. 1. 1.]
 [0. 2. 2. 2

In [179]:
class HiddenMarkov3:
    def viterbi(self,Q,V,A,B,O,PI):
        '''
        Q:状态集合
        V:观测集合
        A:状态转移概率矩阵
        B:观测概率矩阵
        O:观测序列
        PI:初始参数
        ''' 
        M=len(Q)
        N=len(O)
        T=N
        deltas=np.ones((M,N))
        psis=np.ones((M,N))
        I=np.ones((1,N))
        
        for t in range(T):
            indexOfO=V.index(O[t])
            for i in range(M):
                if t==0:
                    deltas[i][t]=PI[t][i] * B[i][indexOfO]
#                     print([deltas[t] for delta in deltas])
                    psis[i][t]=np.argmax([PI[t][j] * B[j][indexOfO] for j in range(M)])
                else:
                    deltas[i][t]=np.max(np.multiply([delta[t-1] for delta in deltas],
                                            [a[i] for a in A])) * B[i][indexOfO]
                    psis[i][t]=np.argmax(np.multiply([delta[t-1] for delta in deltas],
                                            [a[i] for a in A]))
        print(deltas)
        print(psis)
        
        I=np.zeros((1,N))
        for i in range(N-1,-1,-1):
            I[0][i]=psis[np.argmax([delta[i] for delta in deltas])][i]
        print(I)
                    
                    
                    
                
    

In [180]:
HMM3=HiddenMarkov3()
HMM3.viterbi(Q,V,A,B,O,PI)

[[0.1      0.028    0.00756  0.00189 ]
 [0.16     0.0504   0.01008  0.003024]
 [0.28     0.042    0.0147   0.002205]]
[[2. 2. 1. 0.]
 [2. 2. 1. 1.]
 [2. 2. 2. 2.]]
[[2. 2. 2. 1.]]
