In [2]:
import pandas as pd
import numpy as np
from sklearn.datasets import load_iris
import matplotlib.pyplot as plt

In [3]:
iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['label']=iris.target

In [4]:
df.head()

sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   label  
0      0  
1      0  
2      0  
3      0  
4      0

In [5]:
df.columns=['sepal length', 'sepal width', 'petal length', 'petal width', 'label']
df.head()

sepal length  sepal width  petal length  petal width  label
0           5.1          3.5           1.4          0.2      0
1           4.9          3.0           1.4          0.2      0
2           4.7          3.2           1.3          0.2      0
3           4.6          3.1           1.5          0.2      0
4           5.0          3.6           1.4          0.2      0

In [6]:
df.label.value_counts()

2    50
1    50
0    50
Name: label, dtype: int64

In [43]:
plt.scatter(df.loc[:50,'sepal length'],df.loc[:50,'sepal width'])
plt.scatter(df.loc[50:100,'sepal length'],df.loc[50:100,'sepal width'])
plt.xlabel('sepal length')
plt.xlabel('sepal width')
plt.legend()
# plt.show()

In [78]:
data=np.array(df.iloc[:100,[0,1,-1]])
X,y=data[:,:-1],data[:,-1]
y=np.array([1 if i==1 else -1 for i in y ])

Perceptron

In [124]:
class Model:
    def __init__(self):
        self.w = np.ones(len(data[0])-1, dtype=np.float32)
        self.b = 0
        self.l_rate = 0.1
        
    def sign(self, x, w, b):
        y = np.dot(x, w) + b
        return y
    
    def fit(self,X_train,y_train):
        is_wrong=False
        while not is_wrong:
            wrong_count=0
            for d in range(len(X_train)):
                X=X_train[d]
                y=y_train[d]
                if y * self.sign(X,self.w,self.b) <=0:
                    self.w=self.w+self.l_rate*np.dot(y,X)
                    self.b=self.b+self.l_rate*y
                    wrong_count+=1
            if wrong_count==0:
                is_wrong=True
        print('wrong count : '+str(wrong_count))        
        return 'Perceptron Model'
        
        def score(self):
            pass

In [126]:
perceptron=Model()
perceptron.fit(X,y)

wrong count : 0


'Perceptron Model'

In [91]:
x_points=np.linspace(4,7,10)
y_points=-(perceptron.w[0]*x_points+perceptron.b)/perceptron.w[1]
plt.plot(x_points,y_points)
plt.plot(data[:50,0],data[:50,1],'bo',label='0')
plt.plot(data[50:100,0],data[50:100,1],'bo',color='orange',label='1')
plt.xlabel('sepal length')
plt.ylabel('sepal width')
plt.legend()
# plt.show()

In [117]:
perceptron.b

-12.099999999999973

In [118]:
perceptron.w

array([  7.8, -10. ])

In [94]:
y

array([-1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,
       -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1, -1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,
        1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1,  1])

In [93]:
X

array([[5.1, 3.5],
       [4.9, 3. ],
       [4.7, 3.2],
       [4.6, 3.1],
       [5. , 3.6],
       [5.4, 3.9],
       [4.6, 3.4],
       [5. , 3.4],
       [4.4, 2.9],
       [4.9, 3.1],
       [5.4, 3.7],
       [4.8, 3.4],
       [4.8, 3. ],
       [4.3, 3. ],
       [5.8, 4. ],
       [5.7, 4.4],
       [5.4, 3.9],
       [5.1, 3.5],
       [5.7, 3.8],
       [5.1, 3.8],
       [5.4, 3.4],
       [5.1, 3.7],
       [4.6, 3.6],
       [5.1, 3.3],
       [4.8, 3.4],
       [5. , 3. ],
       [5. , 3.4],
       [5.2, 3.5],
       [5.2, 3.4],
       [4.7, 3.2],
       [4.8, 3.1],
       [5.4, 3.4],
       [5.2, 4.1],
       [5.5, 4.2],
       [4.9, 3.1],
       [5. , 3.2],
       [5.5, 3.5],
       [4.9, 3.1],
       [4.4, 3. ],
       [5.1, 3.4],
       [5. , 3.5],
       [4.5, 2.3],
       [4.4, 3.2],
       [5. , 3.5],
       [5.1, 3.8],
       [4.8, 3. ],
       [5.1, 3.8],
       [4.6, 3.2],
       [5.3, 3.7],
       [5. , 3.3],
       [7. , 3.2],
       [6.4, 3.2],
       [6.9,

In [95]:
np.ones(2)

array([1., 1.])

In [139]:
def sign2(x,w,b):
    y=np.dot(w,x)+b
    return y

def fit2(x_train,y_train):
    w=np.ones(len(x_train[0]))
    b=0
    l=0.001
    is_wrong=False
    wc_sum=0
    while not is_wrong:
        wrong_count=0
        for i in range(len(y_train)):
            x=x_train[i]
            y=y_train[i]
#              loss condition y(wx+b)<0
            if y*sign2(x,w,b) <=0:
#                 update w,b,w1=w0+lxy,b=ly
                w=w+l*np.dot(x,y)
                b=b+l*y
                wrong_count+=1
                wc_sum+=1
        if wrong_count ==0:
            is_wrong=True
    print('wrong count : '+str(wc_sum))
    return w,b
                

In [140]:
fit2(X,y)

wrong count : 797


(array([ 0.0672, -0.0412]), -0.22700000000000017)

sklearn-perceptron

In [142]:
from sklearn.linear_model import Perceptron

In [158]:
clf=Perceptron(alpha =0.01,max_iter=2000,shuffle=False,n_jobs=-1)
clf.fit(X,y)

Perceptron(alpha=0.01, class_weight=None, eta0=1.0, fit_intercept=True,
      max_iter=2000, n_iter=None, n_jobs=-1, penalty=None, random_state=0,
      shuffle=False, tol=None, verbose=0, warm_start=False)

In [159]:
print(clf.coef_)

[[  79.8 -101.4]]


In [162]:
print(clf.coef_[0][0])

79.80000000000159


In [160]:
print(clf.intercept_)

[-126.]


In [164]:
1/np.sqrt(2)

0.7071067811865475

In [165]:
np.sqrt(18)

4.242640687119285

6.25

In [171]:
#2,4.5,4,7
np.sqrt(10.25)


3.2015621187164243