In [1]:
import numpy as np
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [19]:
np.random.seed(0)
M=20
N=5
x=np.random.randint(2,size=(M,N))
x=np.array(list(set([tuple(i) for i in x])))
y=np.arange(len(x))
# gnb=GaussianNB(priors=None)
gnb=MultinomialNB(alpha=1.0)
gnb.fit(x,y)
y_hat=gnb.predict(x)
print('acc : ',np.mean(y==y_hat))
print('model score : ',gnb.score(x,y))
err=y!=y_hat
for i,e in enumerate(err):
    if e:
        print('y :',y[i],' y_hat :',y_hat[i])
        print(x[i])

acc :  0.882352941176
model score :  0.882352941176
y : 1  y_hat : 0
[0 0 0 0 0]
y : 15  y_hat : 1
[1 1 1 1 1]


In [22]:
for i in range(len(x)):
    print (x[i],'------',y[i])

[1 1 0 1 0] ------ 0
[0 0 0 0 0] ------ 1
[0 0 1 1 0] ------ 2
[1 1 1 1 0] ------ 3
[1 1 0 0 0] ------ 4
[1 1 0 0 1] ------ 5
[1 1 1 0 1] ------ 6
[0 1 1 0 1] ------ 7
[0 1 0 1 1] ------ 8
[1 0 1 0 1] ------ 9
[0 1 0 0 1] ------ 10
[1 0 1 1 0] ------ 11
[0 1 1 0 0] ------ 12
[0 0 0 0 1] ------ 13
[1 0 0 1 0] ------ 14
[1 1 1 1 1] ------ 15
[0 1 1 1 1] ------ 16
