In [1]:
import numpy as np
from sklearn.naive_bayes import GaussianNB,MultinomialNB

In [2]:
np.random.seed(0)
M=20
N=5
x=np.random.randint(2,size=(M,N))
x=np.array(list(set([tuple(i) for i in x])))
y=np.arange(len(x))
print('sample num: %d, feature num : %d' % x.shape)
print('data:\n',x)
print('--------------')
print(y)
# mnb=MultinomialNB(alpha=1)
mnb=GaussianNB(priors=None)
mnb.fit(x,y)
y_hat=mnb.predict(x)
print('predict category : \n',y_hat)
print('acc : ',(100*np.mean(y_hat==y) ))
print('model score :',mnb.score(x,y))
err=y!=y_hat
for i ,e in enumerate(err):
    if e:
        print('y : ',y[i],' x:',x[i])
        print('y_hat : ',y_hat[i])

sample num: 17, feature num : 5
data:
 [[1 1 0 1 0]
 [0 0 0 0 0]
 [0 0 1 1 0]
 [1 1 1 1 0]
 [1 1 0 0 0]
 [1 1 0 0 1]
 [1 1 1 0 1]
 [0 1 1 0 1]
 [0 1 0 1 1]
 [1 0 1 0 1]
 [0 1 0 0 1]
 [1 0 1 1 0]
 [0 1 1 0 0]
 [0 0 0 0 1]
 [1 0 0 1 0]
 [1 1 1 1 1]
 [0 1 1 1 1]]
--------------
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
predict category : 
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
acc :  100.0
model score : 1.0


In [3]:
mnb=GaussianNB(priors=None)
mnb.fit(x,y)
y_hat=mnb.predict(x)
print('Category predict : ', y_hat)
print('acc : %.2f%%' % (100 * np.mean(y_hat==y)))
print('system score : ',mnb.score(x,y))
err=y_hat !=y
for i,e in enumerate(err):
    if e:
        print(y[i],':\t',x[i],'like same with ',x[y_hat[i]] )

Category predict :  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16]
acc : 100.00%
system score :  1.0


In [7]:
x1=np.random.randint(2,size=(2,4))
x1


array([[1, 0, 1, 0],
       [1, 1, 1, 1]])

In [21]:
x2=np.array(set([tuple(i) for i in x1]))
x2

array({(1, 0, 1, 0), (1, 1, 1, 1)}, dtype=object)

In [31]:
x1

array([[1, 0, 1, 0],
       [1, 1, 1, 1]])