In [1]:
import torch
import matplotlib.pyplot as plt
from matplotlib_inline import backend_inline
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [12]:
def show_heatmaps(matrices,xlabel,ylabel,title=None,figsize=(2.5,2.5),cmap='Reds'):
    backend_inline.set_matplotlib_formats('svg')
    num_rows,num_cols=matrices.shape[0],matrices.shape[1]
    fig,axes=plt.subplots(num_rows,num_cols,figsize=figsize,sharex=True,sharey=True,squeeze=False)
    for i,(row_axes,row_matrices) in enumerate(zip(axes,matrices)):
        for j,(ax,matrix) in enumerate(zip(row_axes,row_matrices)):
            pcm=ax.imshow(matrix.detach().numpy(),cmap=cmap)
            if i==num_rows-1:
                ax.set_xlabel(xlabel)
            if j==0:
                ax.set_ylabel(ylabel)
            if title:
                ax.set_title(titles[j])
    fig.colorbar(pcm,ax=axes,shrink=0.6)
    

In [33]:
attention_weights=torch.eye(10).reshape((1,1,10,10))
show_heatmaps(attention_weights,xlabel='keys',ylabel='Queries')

In [29]:
for i,j in enumerate(zip('a',attention_weights)):
    print(i)
    print(j[1].shape)
#     print(j[1])
    for k,(l1,l2) in enumerate(zip('b',j[1])):
        print(l2.shape)
        print(l2)

0
torch.Size([1, 10, 10])
torch.Size([10, 10])
tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])


In [31]:
attention_weights[0,0,:,:]

tensor([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

In [34]:
plt.imshow(attention_weights[0,0,:,:])

In [5]:
X = torch.tensor([[1, 2, 3], [4, 5, 6]])
b=torch.tensor([1,2])

In [7]:
a=torch.arange(3)[None,:]
a

tensor([[0, 1, 2]])

In [6]:
b[:,None]

tensor([[1],
        [2]])

In [8]:
a<b[:,None]

tensor([[ True, False, False],
        [ True,  True, False]])

In [ ]:
torch.repeat_interleave()

In [9]:
X = torch.ones(2, 3, 4)

In [12]:
torch.arange(3)[None,:]<b[:,None]

tensor([[ True, False, False],
        [ True,  True, False]])

In [14]:
X

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

In [19]:
c=torch.arange(3,dtype=torch.float32)[None,:]<b[:,None]
c

tensor([[ True, False, False],
        [ True,  True, False]])

In [21]:
X[~c]=0

In [22]:
X

tensor([[[1., 1., 1., 1.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [0., 0., 0., 0.]]])