In [2]:
import torch
from torch import nn,optim
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [3]:
n_train=50
x_train,_ = torch.sort(torch.rand(n_train)*5)

In [4]:
def f(x):
    return 2* torch.sin(x)+x**0.8

In [5]:
x_train

tensor([0.0634, 0.2446, 0.6663, 0.8288, 1.2090, 1.4653, 1.5994, 1.8266, 1.8687,
        2.6337, 2.7219, 2.7705, 2.8668, 2.8972, 3.1988, 3.2612, 3.2843, 3.3439,
        3.3625, 3.5198, 3.5212, 3.6458, 3.6537, 3.7207, 3.7833, 3.8185, 3.8656,
        3.9041, 4.0746, 4.2219, 4.2429, 4.2506, 4.3132, 4.3352, 4.4341, 4.4542,
        4.4767, 4.4941, 4.5064, 4.5323, 4.5327, 4.5337, 4.5660, 4.6190, 4.6384,
        4.6714, 4.7404, 4.9081, 4.9470, 4.9973])

In [6]:
f(x_train)

tensor([0.2369, 0.8086, 1.9587, 2.3347, 3.0345, 3.3464, 3.4552, 3.5542, 3.5610,
        3.1426, 3.0428, 2.9850, 2.8651, 2.8259, 2.4207, 2.3359, 2.3047, 2.2248,
        2.2001, 1.9981, 1.9964, 1.8485, 1.8396, 1.7663, 1.7022, 1.6681, 1.6249,
        1.5916, 1.4697, 1.4010, 1.3942, 1.3919, 1.3771, 1.3736, 1.3688, 1.3701,
        1.3725, 1.3749, 1.3770, 1.3824, 1.3825, 1.3827, 1.3914, 1.4100, 1.4181,
        1.4338, 1.4734, 1.6087, 1.6479, 1.7030])

In [7]:
y_train=f(x_train)+torch.normal(0.0,0.5,(n_train,))
x_test=torch.arange(0,5,0.1)
y_truth=f(x_test)
n_test=len(x_test)
n_test

50

In [8]:

plt.plot(x_test)
plt.plot(y_truth)
plt.xlabel('X')
plt.ylabel('Y')
plt.legend(['Truth','pred'])
plt.xlim([0,5])
plt.ylim([-1,5])
plt.show()


In [ ]:
X_repeat=x_test.repeat_interleave(n_train).reshape((-1,n_train))
attention_weights=nn.functional.softmax(-(X_repeat-x_train)**2/2,dim=1)
y_hat=torchr.matmul(attention_weights,y_train)


#### 10.2.4

In [9]:
X=torch.ones((2,1,4))
Y=torch.ones((2,4,6))
torch.bmm(X,Y).shape

torch.Size([2, 1, 6])

In [10]:
weights=torch.ones((2,10))*0.1
values=torch.arange(20.0).reshape((2,10))
torch.bmm(weights.unsqueeze(1),values.unsqueeze(-1))

tensor([[[ 4.5000]],

        [[14.5000]]])

In [ ]:
class NWKernelRegression(nn.Module):
    def __init__(self,**kwargs):
        super().__init__(**kwargs)
        self.w=nn.Parameter(torch.rand((1,),requires_grad=True))
    
    def forward(self,queries,keys,values):
        queries=queries.repeat_interleave(keys.shape[1]).reshape((-1,keys.shape[1]))
        self.attention_weights=nn.functional.softmax(-((queries-keys)*self.w)**2/2,dim=1)
        