In [1]:
import numpy as np
import torch
import math
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [2]:
def train_2d(trainer):
    x1,x2,s1,s2=-5,-2,0,0
    results=[(x1,x2)]
    for i in range(20):
        x1,x2,s1,s2=trainer(x1,x2,s1,s2)
        results.append((x1,x2))
        print('epoch : %d,x1 %f,x2 %f' % (i+1,x1,x2))
    return results

In [18]:
def show_trace_2d(f,results):
    plt.plot(*zip(*results),'-o',color='#ff7f0e')
    x1,x2=np.meshgrid(np.arange(-5.5,1.0,0.1),np.arange(-3.0,1.0,0.1))
    plt.contour(x1,x2,f(x1,x2),colors='#1f77b4')
    plt.xlabel('x1')
    plt.xlabel('x2')

In [19]:
def f_2d(x1,x2):
    return x1**2+2*x2**2

def gd_2d(x1,x2,s1,s2):
    return (x1-eta*2*x1,x2-eta*4*x2,0,0)

In [20]:
eta=0.1
show_trace_2d(f_2d,train_2d(gd_2d))

epoch : 1,x1 -4.000000,x2 -1.200000
epoch : 2,x1 -3.200000,x2 -0.720000
epoch : 3,x1 -2.560000,x2 -0.432000
epoch : 4,x1 -2.048000,x2 -0.259200
epoch : 5,x1 -1.638400,x2 -0.155520
epoch : 6,x1 -1.310720,x2 -0.093312
epoch : 7,x1 -1.048576,x2 -0.055987
epoch : 8,x1 -0.838861,x2 -0.033592
epoch : 9,x1 -0.671089,x2 -0.020155
epoch : 10,x1 -0.536871,x2 -0.012093
epoch : 11,x1 -0.429497,x2 -0.007256
epoch : 12,x1 -0.343597,x2 -0.004354
epoch : 13,x1 -0.274878,x2 -0.002612
epoch : 14,x1 -0.219902,x2 -0.001567
epoch : 15,x1 -0.175922,x2 -0.000940
epoch : 16,x1 -0.140737,x2 -0.000564
epoch : 17,x1 -0.112590,x2 -0.000339
epoch : 18,x1 -0.090072,x2 -0.000203
epoch : 19,x1 -0.072058,x2 -0.000122
epoch : 20,x1 -0.057646,x2 -0.000073


In [6]:
def test_print(inputs):
    print(inputs)
    print('-------- * ----------')
    print(*inputs)

In [7]:
test_print(train_2d(gd_2d))

epoch : 1,x1 -4.000000,x2 -1.200000
epoch : 2,x1 -3.200000,x2 -0.720000
epoch : 3,x1 -2.560000,x2 -0.432000
epoch : 4,x1 -2.048000,x2 -0.259200
epoch : 5,x1 -1.638400,x2 -0.155520
epoch : 6,x1 -1.310720,x2 -0.093312
epoch : 7,x1 -1.048576,x2 -0.055987
epoch : 8,x1 -0.838861,x2 -0.033592
epoch : 9,x1 -0.671089,x2 -0.020155
epoch : 10,x1 -0.536871,x2 -0.012093
epoch : 11,x1 -0.429497,x2 -0.007256
epoch : 12,x1 -0.343597,x2 -0.004354
epoch : 13,x1 -0.274878,x2 -0.002612
epoch : 14,x1 -0.219902,x2 -0.001567
epoch : 15,x1 -0.175922,x2 -0.000940
epoch : 16,x1 -0.140737,x2 -0.000564
epoch : 17,x1 -0.112590,x2 -0.000339
epoch : 18,x1 -0.090072,x2 -0.000203
epoch : 19,x1 -0.072058,x2 -0.000122
epoch : 20,x1 -0.057646,x2 -0.000073
[(-5, -2), (-4.0, -1.2), (-3.2, -0.72), (-2.56, -0.432), (-2.048, -0.2592), (-1.6384, -0.15552), (-1.31072, -0.09331199999999999), (-1.0485760000000002, -0.055987199999999994), (-0.8388608000000002, -0.033592319999999995), (-0.6710886400000001, -0.020155391999999994), 

In [8]:
results=[(-5, -2), (-4.0, -1.2), (-3.2, -0.72), (-2.56, -0.432)]

In [9]:
print(results)
print('-------- * ----------')
print(*results)
print('-------- *zip ----------')
print([*zip(*results)])

[(-5, -2), (-4.0, -1.2), (-3.2, -0.72), (-2.56, -0.432)]
-------- * ----------
(-5, -2) (-4.0, -1.2) (-3.2, -0.72) (-2.56, -0.432)
-------- *zip ----------
[(-5, -4.0, -3.2, -2.56), (-2, -1.2, -0.72, -0.432)]


In [10]:
a=[-5, -4.0, -3.2, -2.56]
b=[-2, -1.2, -0.72, -0.432]
c=zip(a,b)
print(*c)
print(*zip(*c))

(-5, -2) (-4.0, -1.2) (-3.2, -0.72) (-2.56, -0.432)



In [11]:
x1,x2=np.meshgrid(np.arange(-5.5,1.0,0.1),np.arange(-3.0,1.0,0.1))
x1,x2


(array([[-5.5, -5.4, -5.3, ...,  0.7,  0.8,  0.9],
        [-5.5, -5.4, -5.3, ...,  0.7,  0.8,  0.9],
        [-5.5, -5.4, -5.3, ...,  0.7,  0.8,  0.9],
        ...,
        [-5.5, -5.4, -5.3, ...,  0.7,  0.8,  0.9],
        [-5.5, -5.4, -5.3, ...,  0.7,  0.8,  0.9],
        [-5.5, -5.4, -5.3, ...,  0.7,  0.8,  0.9]]),
 array([[-3. , -3. , -3. , ..., -3. , -3. , -3. ],
        [-2.9, -2.9, -2.9, ..., -2.9, -2.9, -2.9],
        [-2.8, -2.8, -2.8, ..., -2.8, -2.8, -2.8],
        ...,
        [ 0.7,  0.7,  0.7, ...,  0.7,  0.7,  0.7],
        [ 0.8,  0.8,  0.8, ...,  0.8,  0.8,  0.8],
        [ 0.9,  0.9,  0.9, ...,  0.9,  0.9,  0.9]]))

In [12]:
len(x1)

40

In [13]:
f_2d(x1,x2)

array([[48.25, 47.16, 46.09, ..., 18.49, 18.64, 18.81],
       [47.07, 45.98, 44.91, ..., 17.31, 17.46, 17.63],
       [45.93, 44.84, 43.77, ..., 16.17, 16.32, 16.49],
       ...,
       [31.23, 30.14, 29.07, ...,  1.47,  1.62,  1.79],
       [31.53, 30.44, 29.37, ...,  1.77,  1.92,  2.09],
       [31.87, 30.78, 29.71, ...,  2.11,  2.26,  2.43]])

In [14]:
def fun(*args,**kwargs):
    print('args= ',args)
    print('kwargs= ',kwargs)

In [15]:
fun(1,2,3,4,A='a',B='b',c='c')

args=  (1, 2, 3, 4)
kwargs=  {'A': 'a', 'B': 'b', 'c': 'c'}


In [16]:
def sgd_2d(x1,x2,s1,s2):
    return (x1-eta*(2*x1+np.random.normal(0.1)),
           x2-eta*(4*x2+np.random.normal(0.1)),0,0)

In [17]:
show_trace_2d(f_2d,train_2d(sgd_2d))

epoch : 1,x1 -4.061090,x2 -1.325123
epoch : 2,x1 -3.204519,x2 -0.789584
epoch : 3,x1 -2.462671,x2 -0.670753
epoch : 4,x1 -1.834497,x2 -0.409027
epoch : 5,x1 -1.312353,x2 -0.178052
epoch : 6,x1 -1.142994,x2 -0.241050
epoch : 7,x1 -1.027432,x2 -0.090968
epoch : 8,x1 -0.685818,x2 -0.126295
epoch : 9,x1 -0.407612,x2 -0.033164
epoch : 10,x1 -0.408344,x2 0.055981
epoch : 11,x1 -0.374854,x2 -0.024941
epoch : 12,x1 -0.244974,x2 -0.132471
epoch : 13,x1 -0.083309,x2 -0.048699
epoch : 14,x1 -0.163586,x2 -0.075396
epoch : 15,x1 -0.155411,x2 0.063195
epoch : 16,x1 -0.119262,x2 0.016620
epoch : 17,x1 -0.060562,x2 0.014229
epoch : 18,x1 -0.032128,x2 -0.096416
epoch : 19,x1 -0.151469,x2 -0.116690
epoch : 20,x1 -0.126374,x2 -0.164805
