In [1]:
import torch
import torchvision
import matplotlib.pyplot as plt
from torch import nn,optim
import PIL
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [2]:
content_path=r'F:\study\ml\LM\image\13\rainier.jpg'
style_path=r'F:\study\ml\LM\image\13\autumn-oak.jpg'

In [3]:
# content_img=plt.imread(content_path)
# style_img=plt.imread(style_path)

In [4]:
content_img=PIL.Image.open(content_path)
style_img=PIL.Image.open(style_path)

### 以下为PIL测试

In [42]:
import PIL
import numpy as np

In [43]:
content_img_pil=PIL.Image.fromarray(content_img)

In [1]:
content_img_pil=PIL.Image.open(content_path)
np.array(content_img_pil)

NameError: name 'PIL' is not defined

In [46]:
np.array(content_img_pil).shape

(1365, 2048, 3)

In [5]:
plt.imshow(np.array(content_img_pil))
plt.show()

NameError: name 'np' is not defined

In [48]:
content_img.shape

(1365, 2048, 3)

In [34]:
a=torchvision.transforms.ToTensor()(np.array(content_img_pil))

In [35]:
a.shape

torch.Size([3, 1365, 2048])

In [39]:
b=torchvision.transforms.ToTensor()(content_img)
b.shape

D:\ProgramData\Anaconda3\lib\site-packages\torchvision\transforms\functional.py:133: UserWarning: The given NumPy array is not writable, and PyTorch does not support non-writable tensors. This means writing to this tensor will result in undefined behavior. You may want to copy the array to protect its data or make it writable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  C:\actions-runner\_work\pytorch\pytorch\builder\windows\pytorch\torch\csrc\utils\tensor_numpy.cpp:178.)
  img = torch.from_numpy(pic.transpose((2, 0, 1))).contiguous()


torch.Size([3, 1365, 2048])

In [36]:
a

tensor([[[0.9255, 0.9255, 0.9255,  ..., 0.5020, 0.5059, 0.5059],
         [0.9255, 0.9255, 0.9255,  ..., 0.5059, 0.5059, 0.5098],
         [0.9255, 0.9255, 0.9255,  ..., 0.5059, 0.5098, 0.5098],
         ...,
         [0.0549, 0.0549, 0.0549,  ..., 0.1059, 0.1137, 0.1294],
         [0.0549, 0.0549, 0.0549,  ..., 0.0745, 0.0941, 0.1098],
         [0.0549, 0.0549, 0.0549,  ..., 0.0549, 0.0863, 0.1137]],

        [[0.9020, 0.9020, 0.9020,  ..., 0.7333, 0.7373, 0.7373],
         [0.9020, 0.9020, 0.9020,  ..., 0.7373, 0.7373, 0.7412],
         [0.9020, 0.9020, 0.9020,  ..., 0.7373, 0.7412, 0.7412],
         ...,
         [0.0471, 0.0471, 0.0471,  ..., 0.0902, 0.0902, 0.1059],
         [0.0471, 0.0471, 0.0471,  ..., 0.0549, 0.0667, 0.0824],
         [0.0471, 0.0471, 0.0471,  ..., 0.0314, 0.0549, 0.0863]],

        [[0.9176, 0.9176, 0.9176,  ..., 0.8510, 0.8549, 0.8549],
         [0.9176, 0.9176, 0.9176,  ..., 0.8549, 0.8549, 0.8588],
         [0.9176, 0.9176, 0.9176,  ..., 0.8549, 0.8588, 0.

In [49]:
plt.imshow(content_img_pil)
plt.show()

In [19]:
content_img

array([[[236, 230, 234],
        [236, 230, 234],
        [236, 230, 234],
        ...,
        [128, 187, 217],
        [129, 188, 218],
        [129, 188, 218]],

       [[236, 230, 234],
        [236, 230, 234],
        [236, 230, 234],
        ...,
        [129, 188, 218],
        [129, 188, 218],
        [130, 189, 219]],

       [[236, 230, 234],
        [236, 230, 234],
        [236, 230, 234],
        ...,
        [129, 188, 218],
        [130, 189, 219],
        [130, 189, 219]],

       ...,

       [[ 14,  12,  13],
        [ 14,  12,  13],
        [ 14,  12,  13],
        ...,
        [ 27,  23,   0],
        [ 29,  23,   0],
        [ 33,  27,   1]],

       [[ 14,  12,  13],
        [ 14,  12,  13],
        [ 14,  12,  13],
        ...,
        [ 19,  14,   0],
        [ 24,  17,   0],
        [ 28,  21,   2]],

       [[ 14,  12,  13],
        [ 14,  12,  13],
        [ 14,  12,  13],
        ...,
        [ 14,   8,   0],
        [ 22,  14,   1],
        [ 29,  22,   6]]

In [ ]:
b=torchvision.transforms.ToTensor()(content_img)

In [37]:
b

tensor([[[0.9255, 0.9255, 0.9255,  ..., 0.5020, 0.5059, 0.5059],
         [0.9255, 0.9255, 0.9255,  ..., 0.5059, 0.5059, 0.5098],
         [0.9255, 0.9255, 0.9255,  ..., 0.5059, 0.5098, 0.5098],
         ...,
         [0.0549, 0.0549, 0.0549,  ..., 0.1059, 0.1137, 0.1294],
         [0.0549, 0.0549, 0.0549,  ..., 0.0745, 0.0941, 0.1098],
         [0.0549, 0.0549, 0.0549,  ..., 0.0549, 0.0863, 0.1137]],

        [[0.9020, 0.9020, 0.9020,  ..., 0.7333, 0.7373, 0.7373],
         [0.9020, 0.9020, 0.9020,  ..., 0.7373, 0.7373, 0.7412],
         [0.9020, 0.9020, 0.9020,  ..., 0.7373, 0.7412, 0.7412],
         ...,
         [0.0471, 0.0471, 0.0471,  ..., 0.0902, 0.0902, 0.1059],
         [0.0471, 0.0471, 0.0471,  ..., 0.0549, 0.0667, 0.0824],
         [0.0471, 0.0471, 0.0471,  ..., 0.0314, 0.0549, 0.0863]],

        [[0.9176, 0.9176, 0.9176,  ..., 0.8510, 0.8549, 0.8549],
         [0.9176, 0.9176, 0.9176,  ..., 0.8549, 0.8549, 0.8588],
         [0.9176, 0.9176, 0.9176,  ..., 0.8549, 0.8588, 0.

In [38]:
a==b

tensor([[[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]],

        [[True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         ...,
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True],
         [True, True, True,  ..., True, True, True]]]

### 以上为PIL测试

In [6]:
plt.subplots(12)
plt.subplot(121)
plt.imshow(content_img)
plt.subplot(122)
plt.imshow(style_img)
plt.show()


In [7]:
rgb_mean = torch.tensor([0.485, 0.456, 0.406])
rgb_std = torch.tensor([0.229, 0.224, 0.225])

In [8]:
def preprocess(img,image_shape):
    transforms=torchvision.transforms.Compose([
        torchvision.transforms.Resize(image_shape),
        torchvision.transforms.ToTensor(),
        torchvision.transforms.Normalize(mean=rgb_mean,std=rgb_std)])
    print("img : ",img)
#     print("img shape: ",img.shape)
    print("transforms(img)shape : ",transforms(img).shape)
    return transforms(img).unsqueeze(0)

In [9]:
preprocess(content_img,(300,450))

img :  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2048x1365 at 0x18172D84880>
transforms(img)shape :  torch.Size([3, 300, 450])


tensor([[[[ 1.9235,  1.9235,  1.9407,  ...,  0.0741,  0.0741,  0.1083],
          [ 1.9235,  1.9235,  1.9407,  ...,  0.1426,  0.1426,  0.1768],
          [ 1.9235,  1.9235,  1.9407,  ...,  0.2282,  0.2111,  0.2111],
          ...,
          [-1.8782, -1.8439, -1.8268,  ..., -1.6384, -0.8164, -0.8335],
          [-1.8782, -1.8439, -1.8268,  ..., -1.6384, -1.2445, -1.1247],
          [-1.8782, -1.8782, -1.8610,  ..., -1.8439, -1.7069, -1.5528]],

         [[ 1.9909,  1.9909,  1.9734,  ...,  1.2206,  1.2206,  1.2556],
          [ 1.9909,  1.9909,  1.9734,  ...,  1.2731,  1.2731,  1.3081],
          [ 1.9909,  1.9909,  1.9559,  ...,  1.3431,  1.3256,  1.3256],
          ...,
          [-1.8256, -1.7906, -1.7731,  ..., -1.6506, -1.0203, -1.1253],
          [-1.8256, -1.7906, -1.7731,  ..., -1.5630, -1.3704, -1.2654],
          [-1.8256, -1.8256, -1.8081,  ..., -1.7731, -1.6856, -1.5630]],

         [[ 2.2740,  2.2740,  2.2740,  ...,  1.9603,  1.9603,  1.9951],
          [ 2.2740,  2.2740,  

In [10]:
def postprocess(img):
    img=img[0].to(rgb_std.device)
    img=torch.clamp(img.permute(1,2,0)*rgb_std+rgb_mean,0,1)
    return torchvision.transforms.ToPILImage()(img.permute(2,0,1))

In [11]:
pretrained_net=torchvision.models.vgg19(pretrained=True)

In [12]:
style_layers,content_layers=[0,5,10,19,28],[25]

In [13]:
net=nn.Sequential(*[pretrained_net.features[i] for i in 
                   range(max(content_layers+style_layers)+1)])

In [14]:
def extract_features(X,content_layers,style_layers):
    contents=[]
    styles=[]
    for i in range(len(net)):
        X=net[i](X)
        if i in style_layers:
            styles.append(X)
        if i in content_layers:
            contents.append(X)
    return contents,styles

In [15]:
def get_contents(image_shape,device):
    content_X=preprocess(content_img,image_shape).to(device)
    contents_Y,_=extract_features(content_X,content_layers,style_layers)
    return content_X,contents_Y
    

In [16]:
def get_styles(image_shape,device):
    style_X=preprocess(style_img,image_shape).to(device)
    _,styles_Y=extract_features(style_X,content_layers,style_layers)
    return style_X,styles_Y

#### content loss

In [17]:
def content_loss(Y_hat,Y):
    return torch.square(Y_hat-Y.detach()).mean()

#### style loss

In [18]:
def gram(X):
    num_channels,n=X.shape[1],X.numel()//X.shape[1]
    X=X.reshape((num_channels,n))
    return torch.matmul(X,X.T)/(num_channels*n)

In [19]:
def style_loss(Y_hat,gram_Y):
    return torch.square(gram(Y_hat)-gram_Y.detach()).mean()

In [98]:
def tv_loss(Y_hat):
    return 0.5 * (torch.abs(Y_hat[:,:,1:,:]-Y_hat[:,:,:-1,:]).mean()+
                 torch.abs(Y_hat[:,:,:,1:]-Y_hat[:,:,:,:-1]).mean())

In [2]:
content_weight,style_weight,tv_weight=1,1e3,10

In [3]:
def compute_loss(X,contents_Y_hat,styles_Y_hat,contents_Y,styles_Y_gram):
    contents_l=[content_loss(Y_hat,Y) * content_weight for Y_hat,Y in
               zip(contents_Y_hat,contents_Y)]
    styles_l=[style_loss(Y_hat,Y) * style_weight for Y_hat,Y in 
             zip(styles_Y_hat,styles_Y_gram)]
    tv_l=tv_loss(X) * tv_weight
    l=sum(10*styles_l+contents_l+[tv_l])
    return contents_l,styles_l,tv_l,l

In [75]:
class SynthesizedImage(nn.Module):
    def __init__(self,img_shape,**kwargs):
        super(SynthesizedImage,self).__init__(**kwargs)
        self.weight=nn.Parameter(torch.rand(*img_shape))
    
    def forward(self):
        return self.weight

In [87]:
def get_inits(X,device,lr,styles_Y):
    gen_img=SynthesizedImage(X.shape).to(device)
    gen_img.weight.data.copy_(X.data)
    trainer=torch.optim.Adam(gen_img.parameters(),lr=lr)
    styles_Y_gram=[gram(Y) for Y in styles_Y]
    return gen_img(),styles_Y_gram,trainer

In [78]:
device,image_shape='cpu',(300,450)
content_X,contents_Y=get_contents(image_shape,device)
_,styles_Y=get_styles(image_shape,device)

img :  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2048x1365 at 0x22F8148B5B0>
transforms(img)shape :  torch.Size([3, 300, 450])
img :  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1717x1200 at 0x22F81B793A0>
transforms(img)shape :  torch.Size([3, 300, 450])


In [80]:
content_X.shape

torch.Size([1, 3, 300, 450])

In [83]:
contents_Y[0].shape

torch.Size([1, 512, 37, 56])

In [84]:
len(styles_Y)

5

In [85]:
for i in range(len(styles_Y)):
    print("styles Y : i shape ",i,styles_Y[i].shape)

styles Y : i shape  0 torch.Size([1, 64, 300, 450])
styles Y : i shape  1 torch.Size([1, 128, 150, 225])
styles Y : i shape  2 torch.Size([1, 256, 75, 112])
styles Y : i shape  3 torch.Size([1, 512, 37, 56])
styles Y : i shape  4 torch.Size([1, 512, 18, 28])


In [92]:
X,styles_Y_gram,trainer=get_inits(content_X,'cpu',0.3,styles_Y)

In [94]:
for i in range(len(styles_Y_gram)):
    print("styles_Y_gram : i shape ",i,styles_Y_gram[i].shape)

styles_Y_gram : i shape  0 torch.Size([64, 64])
styles_Y_gram : i shape  1 torch.Size([128, 128])
styles_Y_gram : i shape  2 torch.Size([256, 256])
styles_Y_gram : i shape  3 torch.Size([512, 512])
styles_Y_gram : i shape  4 torch.Size([512, 512])


In [103]:
def train(X,contents_Y,styles_Y,device,lr,num_epochs,lr_decay_epoch):
    X,styles_Y_gram,trainer=get_inits(X,device,lr,styles_Y)
    scheduler=torch.optim.lr_scheduler.StepLR(trainer,lr_decay_epoch,0.8)
    for epoch in range(num_epochs):
        trainer.zero_grad()
        contents_Y_hat,styles_Y_hat=extract_features(X,content_layers,style_layers)
        contents_l,styles_l,tv_l,l=compute_loss(X,contents_Y_hat,styles_Y_hat,contents_Y,styles_Y_gram)
        l.backward()
        trainer.step()
        scheduler.step()
        if(epoch+1) %10 ==0:
            print("contens loss: %.2f",float(sum(contents_l)))
            print("styles loss: %.2f",float(sum(styles_l)))
            print("tv loss: %.2f",float(tv_l))
    return X

In [104]:
device,image_shape='cpu',(300,450)
net=net.to(device)
content_X,contents_Y=get_contents(image_shape,device)
_,styles_Y=get_styles(image_shape,device)
output=train(content_X,contents_Y,styles_Y,device,0.3,500,50)

img :  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2048x1365 at 0x22F8148B5B0>
transforms(img)shape :  torch.Size([3, 300, 450])
img :  <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1717x1200 at 0x22F81B793A0>
transforms(img)shape :  torch.Size([3, 300, 450])
contens loss: %.2f 1.886697769165039
styles loss: %.2f 1.7113851308822632
tv loss: %.2f 7.836203098297119
contens loss: %.2f 1.6912285089492798
styles loss: %.2f 0.7593602538108826
tv loss: %.2f 7.591408729553223
contens loss: %.2f 1.5549570322036743
styles loss: %.2f 0.2870299220085144
tv loss: %.2f 6.251469612121582
contens loss: %.2f 1.450787901878357
styles loss: %.2f 0.21341782808303833
tv loss: %.2f 5.155290603637695
contens loss: %.2f 1.3914440870285034
styles loss: %.2f 0.12216442078351974
tv loss: %.2f 4.535834312438965
contens loss: %.2f 1.3003970384597778
styles loss: %.2f 0.07521913200616837
tv loss: %.2f 3.760624408721924
contens loss: %.2f 1.1860100030899048
styles loss: %.2f 0.057811036705970764


In [102]:
a=torch.Tensor([0.01])
sum(a)

tensor(0.0100)