In [2]:
import torch
import torchvision
from torch import nn,optim
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [3]:
img_path=r'F:\study\ml\LM\image\13\cat1.jpg'
img=plt.imread(img_path)
# plt.imshow(img)
# plt.show()

In [9]:
import PIL

In [4]:
type(img)

numpy.ndarray

In [4]:
# plt.figure(figsize=(2*1.4,4*1.5))
plt.subplots(2,4)
for i in range(8):
    plt.subplot(2,4,i+1)
    plt.imshow(img)
plt.show()

In [7]:
trans=torchvision.transforms.ToPILImage()
type(trans(img))

PIL.Image.Image

In [12]:
isinstance(trans(img),PIL.Image.Image)

True

In [13]:
type(torchvision.transforms.ToPILImage(img))

torchvision.transforms.transforms.ToPILImage

In [5]:
def show_images(imgs, num_rows, num_cols, titles=None, scale=1.5):
    """绘制图像列表
    Defined in :numref:`sec_fashion_mnist`"""
    figsize = (num_cols * scale, num_rows * scale)
    _, axes = plt.subplots(num_rows, num_cols, figsize=figsize)
    axes = axes.flatten()
    for i, (ax, img) in enumerate(zip(axes, imgs)):
        if torch.is_tensor(img):
            # 图片张量
            ax.imshow(img.numpy())
        else:
            # PIL图片
            ax.imshow(img)
        ax.axes.get_xaxis().set_visible(False)
        ax.axes.get_yaxis().set_visible(False)
        if titles:
            ax.set_title(titles[i])
    return axes

In [6]:
def show_images1(imgs,num_rows,num_cols,titles=None,scale=1.5):
    figsize=(num_cols*scale,num_rows*scale)
    plt.subplots(num_rows,num_cols,figsize=figsize)
    for i in range(num_cols*num_rows):
        plt.subplot(num_rows,num_cols,i+1)
        plt.imshow(imgs)
    plt.show()
    

In [7]:
from PIL import Image

In [8]:
torchvision.transforms.RandomHorizontalFlip(img)

RandomHorizontalFlip(p=[[[ 15  12   0]
  [ 16  15   0]
  [ 18  17   0]
  ...
  [  0  18  28]
  [  1  19  29]
  [  1  19  29]]

 [[ 16  10   0]
  [ 19  13   0]
  [ 20  17   0]
  ...
  [  1  20  27]
  [  1  20  27]
  [  2  21  28]]

 [[ 24  14   2]
  [ 24  16   3]
  [ 24  18   4]
  ...
  [  0  17  24]
  [  0  18  25]
  [  0  18  25]]

 ...

 [[ 69  88 105]
  [ 74  93 110]
  [ 78  97 114]
  ...
  [ 23  42  59]
  [ 23  42  59]
  [ 23  42  59]]

 [[ 66  87 104]
  [ 71  90 107]
  [ 83 102 119]
  ...
  [ 25  44  61]
  [ 25  44  61]
  [ 25  44  61]]

 [[ 64  85 104]
  [ 67  88 107]
  [ 87 105 125]
  ...
  [ 24  41  59]
  [ 24  41  59]
  [ 24  41  59]]])

In [9]:
from PIL import Image

In [10]:
def apply(img,aug,num_rows=2,num_cols=4,scale=1.5):
    Y=[aug(img) for _ in range(num_rows * num_cols)]
    print(type(Y))
    show_images1(Y, num_rows, num_cols, scale=scale)
    

In [33]:
from PIL import Image
import numpy as np

#### 将plt转换成PIL类型,可以转换,但是在 plt.imshow中,要先转成 np.array,在用plt.imshow,看 show_iamges2

In [30]:
trans=torchvision.transforms.Compose([torchvision.transforms.ToPILImage(),torchvision.transforms.RandomHorizontalFlip()])
type(trans(img))

PIL.Image.Image

In [37]:
trans(img).show()

In [35]:
img_test=trans(img)
plt.imshow(np.array(img_test))
plt.show()

In [23]:
from PIL import Image

In [24]:
img1=Image.open(r'F:\study\ml\LM\image\13\cat1.jpg')

In [25]:
type(img1)

PIL.JpegImagePlugin.JpegImageFile

In [58]:
show_images1(img1,2,4)

In [70]:
import numpy as np

In [71]:
def show_images2(imgs,num_rows,num_cols,titles=None,scale=1.5):
    figsize=(num_cols*scale,num_rows*scale)
    plt.subplots(num_rows,num_cols,figsize=figsize)
    for i in range(num_cols*num_rows):
        plt.subplot(num_rows,num_cols,i+1)
        plt.imshow(np.array(imgs[i]))
    plt.show()

In [72]:
def apply2(img,aug,num_rows=2,num_cols=4,scale=1.5):
    Y=[aug(img) for _ in range(num_rows * num_cols)]
    print(type(Y[0]))
    show_images2(Y, num_rows, num_cols, scale=scale)
    

In [73]:
apply2(img1, torchvision.transforms.RandomHorizontalFlip())

<class 'PIL.Image.Image'>


In [67]:
torch.Tensor([[1,2,3]]).numpy()

array([[1., 2., 3.]], dtype=float32)