In [1]:
import torch
import matplotlib.pyplot as plt
%matplotlib auto

Using matplotlib backend: Qt5Agg


In [2]:
img_path=r'F:\study\ml\LM\image\13\catdog.jpg'
img=plt.imread(img_path)
plt.imshow(img)
plt.show()


In [3]:
def box_corner_to_center(boxes):
    x1,y1,x2,y2=boxes[:,0],boxes[:,1],boxes[:,2],boxes[:,3]
    cx=(x1+x2)/2
    cy=(y1+y2)/2
    w=x2-x1
    h=y2-y1
    boxes=torch.stack((cx,cy,w,h),axis=-1)
    return boxes

In [4]:
def box_center_to_corner(boxes):
    cx,cy,w,h=boxes[:,0],boxes[:,1],boxes[:,2],boxes[:,3]
    x1=cx-0.5*w
    y1=cy-0.5*h
    x2=cx+0.5*w
    y2=cy+0.5*h
    boxes=torch.stack((x1,y1,x2,y2),axis=-1)
    return boxes

In [5]:
dog_bbox,cat_bbox=[60.0,45.0,378.0,516.0],[400.0,112.0,655.0,493.0]

In [6]:
boxes=torch.tensor((dog_bbox,cat_bbox))
box_center_to_corner(box_corner_to_center(boxes))==boxes

tensor([[True, True, True, True],
        [True, True, True, True]])

In [7]:
def box_corner_to_center(boxes):
    """从（左上，右下）转换到（中间，宽度，⾼度） """
    x1, y1, x2, y2 = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
    cx = (x1 + x2) / 2
    cy = (y1 + y2) / 2
    w = x2 - x1
    h = y2 - y1
    boxes = torch.stack((cx, cy, w, h), axis=-1)
    return boxes

def box_center_to_corner(boxes):
    """从（中间，宽度，⾼度）转换到（左上，右下） """
    cx, cy, w, h = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
    x1 = cx - 0.5 * w
    y1 = cy - 0.5 * h
    x2 = cx + 0.5 * w
    y2 = cy + 0.5 * h
    boxes = torch.stack((x1, y1, x2, y2), axis=-1)
    return boxes

In [8]:
dog_bbox, cat_bbox = [60.0, 45.0, 378.0, 516.0], [400.0, 112.0, 655.0, 493.0]

In [9]:
boxes = torch.tensor((dog_bbox, cat_bbox))
box_center_to_corner(box_corner_to_center(boxes)) == boxes

tensor([[True, True, True, True],
        [True, True, True, True]])

In [10]:
def box_center_to_corner(boxes):
    """从（中间，宽度，⾼度）转换到（左上，右下） """
    cx, cy, w, h = boxes[:, 0], boxes[:, 1], boxes[:, 2], boxes[:, 3]
    x1 = cx - 0.5 * w
    y1 = cy - 0.5 * h
    x2 = cx + 0.5 * w
    y2 = cy + 0.5 * h
    boxes = torch.stack((x1, y1, x2, y2), axis=-1)
    return boxes

In [11]:
boxes

tensor([[ 60.,  45., 378., 516.],
        [400., 112., 655., 493.]])

In [12]:
boxes[:, 0]

tensor([ 60., 400.])

In [13]:
boxes[:, 1]

tensor([ 45., 112.])

In [14]:
torch.stack((boxes[:, 0],boxes[:, 1]),axis=0)

tensor([[ 60., 400.],
        [ 45., 112.]])

In [15]:
torch.stack((boxes[:, 0],boxes[:, 1]),axis=1)

tensor([[ 60.,  45.],
        [400., 112.]])

In [17]:
torch.stack((boxes[:, 0],boxes[:, 1]),axis=-1)

tensor([[ 60.,  45.],
        [400., 112.]])

In [16]:
box_corner_to_center(boxes)

tensor([[219.0000, 280.5000, 318.0000, 471.0000],
        [527.5000, 302.5000, 255.0000, 381.0000]])

In [43]:
dog_bbox

[60.0, 45.0, 378.0, 516.0]

In [44]:
cat_bbox

[400.0, 112.0, 655.0, 493.0]

In [48]:
def bbox_to_rect(bbox,color):
    return plt.Rectangle(xy=(bbox[0],bbox[1]),width=bbox[2]-bbox[0],height=bbox[3]-bbox[1],
                        fill=False,edgecolor=color,linewidth=2)

In [53]:
plt.imshow(img)
plt.gca().add_patch(bbox_to_rect(dog_bbox, 'blue'))
plt.gca().add_patch(bbox_to_rect(cat_bbox, 'red'))
plt.show()

In [54]:
plt.imshow(img)