In [1]:
import numpy as np

In [2]:
a=np.arange(12).reshape(3,4)
b=np.arange(12).reshape(3,4)

In [3]:
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [4]:
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [5]:
a*b

array([[  0,   1,   4,   9],
       [ 16,  25,  36,  49],
       [ 64,  81, 100, 121]])

In [6]:
import torch

In [8]:
aa=torch.Tensor(a)
bb=torch.Tensor(b)

In [9]:
aa*bb

tensor([[  0.,   1.,   4.,   9.],
        [ 16.,  25.,  36.,  49.],
        [ 64.,  81., 100., 121.]])

In [11]:
torch.dot(aa,bb.reshape(4,3))

RuntimeError: 1D tensors expected, but got 2D and 2D tensors

In [13]:
a.dot(b.reshape(4,3))

array([[ 42,  48,  54],
       [114, 136, 158],
       [186, 224, 262]])