In [1]:
import torch

In [2]:
X,W_xh=torch.randn(3,1),torch.randn(1,4)
H,W_hh=torch.randn(3,4),torch.randn(4,4)

In [4]:
torch.matmul(X,W_xh), torch.matmul(H,W_hh)

(tensor([[ 0.4037,  0.6762, -0.3210, -1.7064],
         [-0.1816, -0.3042,  0.1444,  0.7676],
         [ 0.2229,  0.3733, -0.1772, -0.9420]]),
 tensor([[ 1.5516,  2.6309,  2.3101,  0.4633],
         [ 0.2890, -0.8426,  0.8402,  0.0683],
         [ 0.2233,  0.5814,  0.0466,  1.2033]]))

In [3]:
torch.matmul(X,W_xh) + torch.matmul(H,W_hh)

tensor([[ 1.9552,  3.3071,  1.9891, -1.2431],
        [ 0.1074, -1.1468,  0.9846,  0.8359],
        [ 0.4462,  0.9547, -0.1306,  0.2612]])

In [11]:
X

tensor([[ 0.8963],
        [-0.4032],
        [ 0.4948]])

In [12]:
H

tensor([[-0.7134,  0.8885,  1.3775,  0.8124],
        [-0.5252, -1.2430,  0.6284, -1.2926],
        [ 0.8359,  0.1685, -0.1721, -0.9005]])

In [13]:
W_xh,W_hh

(tensor([[ 0.4504,  0.7545, -0.3581, -1.9038]]),
 tensor([[ 0.2162,  0.6455,  0.0340,  0.3662],
         [ 0.4071,  1.2577,  0.3820,  0.9533],
         [ 1.0805,  1.4895,  1.5982,  0.4435],
         [-0.1777, -0.0958, -0.2542, -0.9027]]))

In [6]:
torch.cat((X,H),dim=1),torch.cat((W_xh,W_hh),dim=0)

(tensor([[ 0.8963, -0.7134,  0.8885,  1.3775,  0.8124],
         [-0.4032, -0.5252, -1.2430,  0.6284, -1.2926],
         [ 0.4948,  0.8359,  0.1685, -0.1721, -0.9005]]),
 tensor([[ 0.4504,  0.7545, -0.3581, -1.9038],
         [ 0.2162,  0.6455,  0.0340,  0.3662],
         [ 0.4071,  1.2577,  0.3820,  0.9533],
         [ 1.0805,  1.4895,  1.5982,  0.4435],
         [-0.1777, -0.0958, -0.2542, -0.9027]]))

In [5]:
torch.matmul(torch.cat((X,H),dim=1),torch.cat((W_xh,W_hh),dim=0))

tensor([[ 1.9552,  3.3071,  1.9891, -1.2431],
        [ 0.1074, -1.1468,  0.9846,  0.8359],
        [ 0.4462,  0.9547, -0.1306,  0.2612]])